### ISSUE TITLE
Simbrief Random Passenger Volumes wrong

### ISSUE THREAD

**Issue by arobsco** [nabeelio/phpvms#1001]
**Describe the bug**
When you generate a Simbrief the passenger volumes are meant to be randomly generated using the max passenger volumes and the load percentages however they always only seem to generate with very low numbers (0-5 passengers total)

**Version**
Latest dev branch

**To Reproduce**
Create new simbrief
Select aircraft
Simbrief config form shows with very low passenger volumes
Refreshing has no effect

**Expected behavior**
Should generate passenger volumes in line with the load percentages and aircraft passengers limits.

**Screenshots**
![image](https://user-images.githubusercontent.com/18175536/105480857-3218b400-5c9e-11eb-9c85-042c1372578c.png)
![image](https://user-images.githubusercontent.com/18175536/105480991-570d2700-5c9e-11eb-90f1-bffda187b36d.png)

**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)

**Comment by FatihKoz** [comment]
Would you please be so kind and provide Load Factor and Load Factor Variance of this flight (not the general settings), if not set please set something in the flight itself for testing.

Seems like you are hitting the below limit for min-max load.

**Comment by arobsco** [comment]
They are set to blank to inherit the default
![image](https://user-images.githubusercontent.com/18175536/105481570-28438080-5c9f-11eb-84b7-aa578ae1613a.png)

**Comment by FatihKoz** [comment]
Yes ... Seems like the flight model or flight repo is not reading your general settings and thus reporting 0/0 to simbrief controller.

I can provide a quick fix for the simbrief side but this needs to handled on the flight model/repo too (to prevent further or different issues)
