### ISSUE TITLE
Departure and Arrival Time not updated when importing with CSV

### ISSUE THREAD

**Issue by warathand** [nabeelio/phpvms#1007]
Both the departure and arrival time of the route will not be updated when routes are importing with CSV. 

Such timing will only be updated when the checkbox "Delete Existing Data" is ticked 

![](https://cdn.discordapp.com/attachments/709879103918047262/803059688006615051/unknown.png)

![](https://cdn.discordapp.com/attachments/709879103918047262/803059736374542406/unknown.png)

**Comment by nabeelio** [comment]
Can you include the csv?

**Comment by warathand** [comment]
Current PHPVMS: Version: 7.0.0-dev+210122.101b32 

[flights - Copy.zip](https://github.com/nabeelio/phpvms/files/5863595/flights.-.Copy.zip)

**Comment by nabeelio** [comment]
Can you try the linked branch?
