### ISSUE TITLE
Allow PIREP deletion

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1014]
I have seen that there are occasions when a pirep is prefiled by Acars and never completed, in my case I had a power cut part way through.  This left the prefiled pirep on the database and the live map was showing me enroute.  I have seen this now many times when the flight is not completed by the pilot.  (Sim crashes, aircraft crashes, power cuts, loss of network)

I have had to manually go into the database table and remove pireps that are not completed.

I do not know if this is the same situation with manual prefiled pireps.

It would be nice to be able to manage the pireps from admin allowing the removal of rejected and prefiled unreported pireps without having to go into phpmyadmin.

**Comment by nabeelio** [comment]
I will need to do some debugging why this is happening, thanks

**Comment by macofallico** [comment]
after crash/closed, try going back to acars again when it loads will tell you that you have a current flight if you want to continue it, press no, and check de DB/Map, flight should not be there anymore.

**Comment by dougjuk** [comment]
Thanks, I am aware of this but it does not always work.  Also it means the users has to reopen straight away and close the flight to get it off the map.  I have several users who just leave it until next flight so they stay on the map for long periods.  Would be better if it was automatic.

**Comment by macofallico** [comment]
ok!  but just a hint to nabeel that issue might be around that function, maybe cron job should wipe  it too.

**Comment by nabeelio** [comment]
> Thanks, I am aware of this but it does not always work. Also it means the users has to reopen straight away and close the flight to get it off the map. I have several users who just leave it until next flight so they stay on the map for long periods. Would be better if it was automatic.

The problem is that it's impossible to tell if it crashed and someone is just having a problem and restarting. I guess I can clear it after an hour or something, I know I've had instances where I've resumed a half-hour later or something because I was just having other issues. How do you suggest getting around that?

**Comment by nabeelio** [comment]
- Button to delete PIREP (frontend "cancel" button will be changed to "delete")
- Going to add a cron to remove prefiled PIREPs after 6 hours
- Setting/cron delete canceled PIREPs after x hours
- Setting/cron to delete rejected PIREPs after x days
