### ISSUE TITLE
ACARS App - pilots can fly different aircraft than the one selected

### ISSUE THREAD

**Issue by arobsco** [nabeelio/phpvms#1023]
**Describe the bug**
An issue exists where a pilot can select an aircraft on the acars app but fly a completely different one in the simulator. The acars app does not seem to check the aircraft chosen in sim against what was picked in the flight setup screen in acars

**Version**
Latest beta

**Expected behavior**
The pilot should not be able to start a flight when acars detects a different aircraft is in use in the simulator. Acars should throw an error and inform user they need to select the correct aircraft

**Comment by nabeelio** [comment]
Are you talking about the aircraft selected in the simbrief briefing screen?

**Comment by arobsco** [comment]
No within the acars app itself. I can select an aircraft but fly a completely different one and it lets me. I wasn't sure if it needed raised here so apologies if not.

**Comment by nabeelio** [comment]
I see - it's very difficult to detect that. There's no type/registration data that comes across, certainly nothing that's uniform across the simulator. I report the aircraft "title" but that is depending on the livery/developer on how they title it.

**Comment by arobsco** [comment]
Ok no problem thanks, i thought maybe the ICAO was always passed. Happy to close off then
