### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#1029]
Maybe need to update Laravel

**Comment by Jannis-D** [comment]
It's working with a recent dev-version for me. I also ran composer.

**Comment by nabeelio** [comment]
Strange, there weren't changes there. Did you run composer update? Maybe something updated which fixed a bug. The Laravel, etc, versions are quite behind

**Comment by Jannis-D** [comment]
That's interesting. I only ran `composer install` after drap & drop and overwrite the files on my webroot.
