### ISSUE TITLE
SimBrief download not working

### ISSUE THREAD

**Issue by DerHero** [nabeelio/phpvms#1033]
When trying to download the SimBrief plan from the dispatch page, nothing will happen.

Tried with different browsers.

**Comment by nabeelio** [comment]
Is the popup being blocked? Any errors in the logs? Which page are you trying to download from, which link, etc, etc. Need more details

**Comment by DerHero** [comment]
It's from a briefing page after planning the flight with simbrief. At Chrome, a new tab is opening for a half of a second with some simbreif link. Donwload isn't starting anyway. At Internet-Explorer nothing happens.
[laravel-2021-02-15.log](https://github.com/nabeelio/phpvms/files/5982744/laravel-2021-02-15.log)

**Comment by nabeelio** [comment]
It sounds like the browser is blocking the pop-up

**Comment by macofallico** [comment]
common problem with chrome,  working with edge

**Comment by nabeelio** [comment]
I don't think they're related, but you do have some weird errors in your logs:

> [2021-02-15 00:37:39] prod.ERROR: file_get_contents(php://filter/write=convert.iconv.utf-8.utf-16le|convert.quoted-printable-encode|convert.iconv.utf-16le.utf-8|convert.base64-decode/resource=../storage/logs/laravel.log): failed to open stream: operation failed {"exception":"[object] (ErrorException(code: 0): file_get_contents(php://filter/write=convert.iconv.utf-8.utf-16le|convert.quoted-printable-encode|convert.iconv.utf-16le.utf-8|convert.base64-decode/resource=../storage/logs/laravel.log): failed to open stream: operation failed at /var/www/fly/vendor/facade/ignition/src/Solutions/MakeViewVariableOptionalSolution.php:75)

**Comment by DerHero** [comment]
Which extension of php do you mean?

Update: On Firefox and Opera, the download is working fine!

**Comment by FatihKoz** [comment]
Today, Chrome just did the same thing to me ... Which was working fine before, suddenly it stopped downloading the files while other browsers was just fine. So i checked my Chrome version and updated it (actually it updated itself) and then downloads returned to normal.

Most probably it was/is a Chrome error, it was somehow blocking the downloads.

**Comment by DerHero** [comment]
I can agree that!
