### ISSUE TITLE
(SimBrief) Wrong cruising ALT and wrong speed integer on prefile (VATSIM)

### ISSUE THREAD

**Issue by DerHero** [nabeelio/phpvms#1036]
![Screenshot 2021-02-18 221741](https://user-images.githubusercontent.com/42517031/108422680-28e81c00-7237-11eb-9208-2196eeb62815.png)

Recent dev Version of phpVMS

**Comment by nabeelio** [comment]
@FatihKoz is this something with simbrief?

**Comment by FatihKoz** [comment]
Speeds are always reported with trailing zeros in flight plans, this is what simbrief reports and we pass that info to VATSIM prefile form too without a change but seems like they want it in their style. Anyway we can fix it and make the VATSIM prefile fully compatible with VATSIM.

For the altitude part i need to check what simbrief returns and what we use. What is the problem or the expectation of VATSIM here ? Should it be 23000 or something else like FL230, need more info to process
