### ISSUE TITLE
Remove "remove bid after accept" setting

### ISSUE THREAD

**Issue by GAE074** [nabeelio/phpvms#1039]
**Describe the bug**
A bid, corresponding to a pirep has not been cleared after flight

**Version**
Version 7.0.0-dev+210213.4e652c

**To Reproduce**
1. bid a flight in phpVMS
2. create a simbrief OFP out from that bid
3. in vmsAcars go to search
4. then click on bid in the lower right corner
5. load that flight
6. start the flight, and end the flight after landing
7. send the pirep of that flight from out of vmsAcars
8. check pirep has been accepted
9. Error: bid is still activ

**Expected behavior**
bid should been cleared after pirep has been accepted

**Screenshots**
database table "pireps"
![image](https://user-images.githubusercontent.com/79332639/108548819-a0c44e00-72ec-11eb-843b-b7aa712f8375.png)

database table "bids"
![image](https://user-images.githubusercontent.com/79332639/108548934-cbaea200-72ec-11eb-8019-34d24e26fb76.png)

**Additional context**
none

**Comment by FatihKoz** [comment]
I will check the issue with latest dev 'cause i think we fixed this along with attaching pirep id's to simbrief table ... Also i do not see any leftover bids in my live site

**Comment by nabeelio** [comment]
Note: Remove the "remove bid on accept" setting - make that the default behavior
