### ISSUE TITLE
Cancelled pireps counting towards hours

### ISSUE THREAD

**Issue by arobsco** [nabeelio/phpvms#1041]
**Describe the bug**
When a pilot files a pirep and it is cancelled the flight is still counting towards the users flights and hours. Additionally I also believe a pilot can hit the file pirep on the acars app multiple times and increment the flights and hours that way as well.

**Version**
Latest dev

**Expected behavior**
Only accepted and approved pireps count towards pilots hours.

**Screenshots**
Will upload.

**Additional context**
Still gathering all logs will upload.

**Comment by nabeelio** [comment]
The plan is to refactor some of this to delete PIREPs that are canceled instead. Though it's weird that the hours are counting.

**Comment by arobsco** [comment]
I discovered the issue. There was an error in an awards code I wrote so the server was returning 503 on this error and not submitting the pirep however the hours and flights were incrementing every time file flight was clicked

**Comment by nabeelio** [comment]
Ah got it, good to know.
