### ISSUE TITLE
Cannot install with Composer 2

### ISSUE THREAD

**Issue by BaradineAllawa** [nabeelio/phpvms#1057]
I've tried to install a clean version on debian testing, and since testing now contains composer 2, the command

composer install

returns this.
`$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - joshbrw/laravel-module-installer is locked to version v0.1.4 and an update of this package was not requested.
    - joshbrw/laravel-module-installer v0.1.4 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - oomphinc/composer-installers-extender is locked to version v1.1.2 and an update of this package was not requested.
    - oomphinc/composer-installers-extender v1.1.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
`

Following what it says (composer update), returns this.

`$ composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - joshbrw/laravel-module-installer[v0.1, ..., v0.1.4] require composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires joshbrw/laravel-module-installer 0.1.* -> satisfiable by joshbrw/laravel-module-installer[v0.1, ..., v0.1.4].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
`

So can we get updated to composer 2?

**Comment by nabeelio** [comment]
Yes, I'm fixing this as part of the updating to Laravel 8 and updating those other dependencies.

**Comment by arobsco** [comment]
Think this has been solved now. I used composer 2 to install my vendor folder today

**Comment by nabeelio** [comment]
Great!
