### ISSUE TITLE
Finances Calculation

### ISSUE THREAD

**Issue by LNR4** [nabeelio/phpvms#1061]
Hello Nabeel,
I just had 2 flights, one with a Cessna, the other with a B738
As you can see, there is a problem with finances.

Finances-B738
Light

for this proposal, we must forget the flight rules (IFR, VFR).
In fact, we would base ourselves on MTOW, wake turbulence.
In the end, we would have 3 categories: Light, Medium, Heavy.
Light: MTOW <7000 Kg
Medium MTOW 7000-136000
Heavy> 136,000
At this time, as soon as the pirep
Finances-B738
Light

is created, the acars will see which category the device belongs to.
and at the end of the theft, so he could calculate the finances based on that.
For this calculation, two solutions:
the first, to be able to enter the various parameters independently.
Example: GroundHandling:
LIGHT: 30
MEDIUM: 1200
HEAVY; 1500
or then, all these financial parameters would concern only one category, example LIGHT, and one would proceed to a calculation according to this parameter.
HEAVY = LIGHTx50
So much for this proposal, if you have any questions, I am at your service !!

**Comment by nabeelio** [comment]
I'm closing this for now until the finances stuff is more fleshed out
