### ISSUE TITLE
JET A and 100LL

### ISSUE THREAD

**Issue by LNR4** [nabeelio/phpvms#1062]
Hello,
Currently, the price of fuel is fixed at airports and in the general category.
In our company, we use planes that use 100 LL fuel.
Would it be possible to add it? Because the operating costs are not the same.

**Comment by nabeelio** [comment]
I believe I have it in the database, just need to expose the entry box

**Comment by FatihKoz** [comment]
Should be closed, both MOGAS and 100LL is now recognized by Pirep Finances / PR #1172
