### ISSUE TITLE
Delete Pirep Cron Error

### ISSUE THREAD

**Issue by arobsco** [nabeelio/phpvms#1068]
**Describe the bug**
Received below error on cron logs:
`[2021-03-08 09:00:01] dev.ERROR: Argument 1 passed to App\Cron\Hourly\DeletePireps::deletePireps() must be of the type int, null given, called in /var/www/phpvms/app/Cron/Hourly/DeletePireps.php on line 28 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Cron\\Hourly\\DeletePireps::deletePireps() must be of the type int, null given, called in /var/www/phpvms/app/Cron/Hourly/DeletePireps.php on line 28 at /var/www/phpvms/app/Cron/Hourly/DeletePireps.php:38)`

Further hourly runs seem to have been successful. Unsure what caused this one

**Version**
Latest Dev

**Comment by nabeelio** [comment]
That's weird, was `/update` run? Do you have two settings in your in admin for delete rejected/deleted canceled times?

**Comment by arobsco** [comment]
It happened just after I migrated to new server and moved the database so may have been related to that. /update wasn't run

**Comment by nabeelio** [comment]
Ok sounds good
