### ISSUE TITLE
Expense per time. Airport parking fees per staying time.

### ISSUE THREAD

**Issue by airnubeiro** [nabeelio/phpvms#1070]
It would be great if we can add "expenses depending on time". For example if a pilot leave the airplane at an airport that isn't the hub, the system will start a counter until the airplane leaves again. The time that the plane has been parked there will be multipyed by a variable factor that we can set. 
Also the crew payment. We could set a variable amount of money that would be multiplyed by the flight time and then again per number of crew... There will be a lot of options. 

Thanks in advance.

**Comment by arv187** [comment]
@airnubeiro check the issue #776  #957  see if you want to comment more on those issues or add something.

**Comment by nabeelio** [comment]
I'll close this since those other issues are open already and cover this.
