### ISSUE TITLE
Disable activity checks for some pilots

### ISSUE THREAD

**Issue by exciler** [nabeelio/phpvms#1078]
Some pilots/users are very active creating flightplans, organizing events, developing or painting but not very active in flying. We should be able to exclude those pilots from activity checks.

In my opinion there are 3 variants of implementation:
a) bool/checkbox for user
b) bool/checkbox on role
c) dedicated "permission" assignable to a role

First discussion on discord seems to prefer variant b)

I will start developing in the next days... if anybody has other ideas or arguments for another variant, let´s discuss.

**Comment by FatihKoz** [comment]
I would vote for B ;)

Better having it assigned to a role, so it can be shared by multiple users having the same role. (like admin, fleet manager, dispatcher, painter etc etc)

**Comment by nabeelio** [comment]
B is fine with me.

**Comment by GAE074** [comment]
also B for me
