### ISSUE TITLE
Database Structure / Airport Table

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1086]
**Describe the bug**
Fields for costs (Ground Handling and Fuels) have defaults set to _0.00_ , which is braking the code of checking their existence in functions (like the one we use for PirepFinances).

When you insert airports via csv you will face another bug ( #1084 ) but when inserted by flight import or manually via admin/airports/add new, airport table uses the field defaults to populate data.

**Version**
7.0.0-dev+210319.707242

**Expected behavior**
Field default values should be NULL not 0.00

**Screenshots**
![db_structure](https://user-images.githubusercontent.com/74361521/111770819-f2480480-88bb-11eb-8fd5-f900279fe3d9.png)

**Additional Info**
When using `if($airport->ground_handling_cost) { ... ;} else { ... ;}` or `{[ $airport->ground_handling_cost ?? $another->thing }}` checks always return true 'cause we have 0.00 being read from the database.

**Comment by nabeelio** [comment]
That code should if `if(empty($airport->ground_handling_cost))` - that should check for 0/0.0 IIRC

**Comment by FatihKoz** [comment]
Will use that if empty logic at PirepFinances and check.

**Comment by FatihKoz** [comment]
Used the suggested if logic at PirepFinances, thus closing this issue.
