### ISSUE TITLE
Unable to Connect to MySQL from the app Container

### ISSUE THREAD

**Issue by benmaxlevy** [nabeelio/phpvms#1096]
**Describe the bug**
The title says it all. Connection refused.

**Version**
be63329 commit on the dev branch.

**To Reproduce**
1. Follow the installation procedure 

**Expected behavior**
Being able to access the MySQL container from the app container.

**Screenshots**
n/a

**Additional context**
`Failed! SQLSTATE[HY000] [2002] Connection refused`

**Comment by nabeelio** [comment]
Is this with docker compose? Are you using "mysql" as the hostname?

**Comment by benmaxlevy** [comment]
The host was wrong. Ty!

**Comment by erikmevis** [comment]
Hello,

I have an issue with step2 with the DB setup. After following the above, i get this error:

https://pastebin.com/FfCqTndJ

**Comment by erikmevis** [comment]
> Hello,
> 
> I have an issue with step2 with the DB setup. After following the above, i get this error:
> 
> https://pastebin.com/FfCqTndJ

`nginx_1 | 172.21.0.1 - - [25/Jun/2021:05:36:46 +0000] "POST /install/envsetup HTTP/1.1" 302 378 "http://localhost/install/step2?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

mysql_1 | 2021-06-25T05:36:46.466362Z 39 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.467314Z 40 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.467946Z 41 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.475747Z 42 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.476332Z 43 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.481102Z 44 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.482642Z 45 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.483663Z 46 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

nginx_1 | 172.21.0.1 - - [25/Jun/2021:05:36:46 +0000] "GET /install/step2 HTTP/1.1" 200 16531 "http://localhost/install/step2?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

app_1 | 172.21.0.5 - 25/Jun/2021:05:36:46 +0000 "GET /index.php" 200`
