### ISSUE TITLE
Wrong values for fuel price, groundhandling and timezone when airport created by acars

### ISSUE THREAD

**Issue by GAE074** [nabeelio/phpvms#1109]
**Describe the bug**
If a user does a freeflight from/to an airport, which is not maintained in phpvms yet, the airport will be created automaticly when user sends pirep. But the airport will be maintained with the Value "0.00" for ground_handling_cost and fuel_jeta_cost, both should be set with "NULL". For "timezone" will allways be set the value "GMT" and not the correct timezone.

**Version**
7.0.0-dev+210328.ed146b

**To Reproduce**
1. Do a freeflight to an airport not maintained in phpvms
2. Send pirep for the flight
3. Look in Admin/Airports or in DB for the airport
4. See error like in the example screenshot

**Expected behavior**
Airport maintained after sending a pirep should be set up with the same values than maintaining it via manual klick on "lookup" in Admin/Airports

**Screenshots**
Example LTBS in DB
![2021-03-29 08_32_42-Clipboard](https://user-images.githubusercontent.com/79332639/112796948-fc5fc500-906a-11eb-8a83-c819d4b9af0f.jpg)

**Comment by dougjuk** [comment]
Completely agree, I have been watching for new airports and editing them, also it does not enter the correct timezone.  You have to go into the airport in admin and lookup to get it sorted.

**Comment by nabeelio** [comment]
There's no fuel price or ground handling - those need to be set manually.

**Comment by GAE074** [comment]
The "problem" is not that there is no fuel or groundhandling price is set, the "problem" is, that there is set a value of "0.00". In that case the default value for fuel and groundhandling will be used anyway, it is just not consistent, as if you do the airport lookup manualy, the database field is set to "NULL" (you see it in the screenshot for LTBF and LTBZ)

**Comment by nabeelio** [comment]
Well, the ground handling should use the default now, that was fixed in this PR: https://github.com/nabeelio/phpvms/pull/1088. I'm not sure what you mean by not consistent; those values just need to be entered manually, there's no way to look them up/I don't have a datasource for those. The airport add is just a fallback.

Fuel price - I guess we need a default to be used/set too. The timezone should be fixed in that PR hopefully.
