### ISSUE TITLE
Event Hook For PreFile

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1110]
disabling free flights is on my list
the blocking usually will have to happen in the prefile phase
i can maybe add an event hook for prefile so you can have a module which listens to that and then can block a preflight

=====

This is what @nabeelio (you) wrote when we were chatting about free flights etc.

This is just a reminder here

**Comment by nabeelio** [comment]
Ok this was a quick one... though I had this already... and it was there, just in the wrong place. So I moved it. See if it works. To abort a prefile, use:

```php
throw new \App\Exceptions\PrefileError('failing prefile because of something');
```

And that message should go up to ACARS

**Comment by FatihKoz** [comment]
I need to prepare some code for it first, i have nothing defined at the moment. Will try to build some after finishing airline/subfleet pr.
