### ISSUE TITLE
Cost Index

### ISSUE THREAD

**Issue by LNR4** [nabeelio/phpvms#1114]
Hello,

Would it be possible to add the cost index to the aircraft database?
It would be possible in this way to check if the device had the correct cost index compared to the one requested by the company.

Francois

**Comment by FatihKoz** [comment]
How do you plan to check the cost index value used by your pilots ?

If it is a pirep field you defined manually, then it has no practical use to define something at database side for check/validation 'cause a pilot may use any cost index value during the flight and then manually enter the value you will accept to his pirep.

But if you have a special software (like acars) reading sim cost index value and reporting it back to your phpvms/pirep, then it makes sense of course.

**Comment by nabeelio** [comment]
You can add a custom PIREP field that's required and they'll have to enter it in acars and then you can verify the value however you want

**Comment by LNR4** [comment]
Hello, 
The goal is to assign a Cost index for the company, cost index not to be exceeded. After the pilot can take whatever he wants, as long as it does not exceed that indicated by the Company.

**Comment by LNR4** [comment]
Precision, we do not want to assign a general cost index, but a different cost index for each aircraft, as in the real world

**Comment by LNR4** [comment]
ok, ok,
Thank's for your answer !

**Comment by nabeelio** [comment]
So I mean if you still want it, add a flight field for it and enter it there. There isn't a place to see it in ACARS (yet) but you can at least specify it there if you want.

**Comment by LNR4** [comment]
For each Company, there is a different cost index according to each device, and according to the distance it travels. It is normal not to have the same cost index on an A319 as on B 787. I thought that it was perhaps possible to add this parameter in the aircraft fleet, as for the parameter of the cost of fuel, ground handling , etc.
But if it's not possible, that's not a problem

**Comment by nabeelio** [comment]
It's not possible right now, not per-airline.
