### ISSUE TITLE
Admin - Pirep Update / Save Error

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1115]
**Describe the bug**
After editing a pirep from Admin / Pireps and clicking save phpvms displays below error. (also theme is not correct, i do not use default theme but the error message is displayed within it)

![admin_pirep_save](https://user-images.githubusercontent.com/74361521/113142296-65923480-9233-11eb-844a-37ed3f3195fc.png)

Is this related to latest changes about pirep edit rights ?

**Version**
7.0.0-dev+210329.50e8f2

**To Reproduce**
1. Go to admin / pireps
2. Click edit to any of your pireps
3. Just click save

**Expected behavior**
Admins should be able to edit pireps

**Comment by nabeelio** [comment]
Yeah I'll fix this one real quick I wasn't paying full attention when looking at the PR
