### ISSUE TITLE
IATA code is required in airport list

### ISSUE THREAD

**Issue by VahidNZ** [nabeelio/phpvms#1125]
**Describe the bug**
Since IATA code is mandatory to import airport list and some airports in the real world do not have them, we will be getting an error or I've to put some invalid characters such as X, and in this case, we have some airports the same IATA code.

Is it possible to change the logic and remove the mandatory IATA code?

**Version**
currently, I'm using version 7.0.0-beta.4.

Regards,
Vahid NZ

**Comment by nabeelio** [comment]
Yes, what @macofallico said.

**Comment by VahidNZ** [comment]
Sure, I will check it 
Thanks
