### ISSUE TITLE
Added specific expenses are added everywhere

### ISSUE THREAD

**Issue by SkygroupVirtual** [nabeelio/phpvms#1126]
I added an expense to a specific aircraft just to try it out. 

[Image of the added expense](http://prntscr.com/116qx1w)

The problem is, the expense is now applied to every aircraft in every subfleet - even in a different one. Please see the attached screenshot of a pirep containing the false expense.

[Image of wrongly applied expense](http://prntscr.com/116qy7q)

**Comment by nabeelio** [comment]
Hi, I think this is a known issue already, there might be an issue opened for it already, I'll have to look

**Comment by SkygroupVirtual** [comment]
That would be great – it was suggested to me on discord to open an issue and I didn’t check the opened ones for any same issues. Thank you for your continued support and work.

**Comment by macofallico** [comment]
Yep i reported it #915, can close this one.

[https://github.com/nabeelio/phpvms/issues/915](url)

**Comment by nabeelio** [comment]
Closing for #915, if you can add your post into there that'd be great thanks!
