### ISSUE TITLE
Mails Not Working after switching from config to env

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1129]
**Describe the bug**
New ENV file has wrong mail settings. Instead of getting mail server, sender name, sender email from config.php and inserting correct values, they are being read from default config, thus after update emails stop working.

Exp;
server in config    : mail.turksim.org
server in new env : smtp.mailgun.org 

user in config : noreply@turksim.org
pass in config : somepassword

user in new env : (nothing)
pass in new env : (nothing)

**Version**
7.0.0-dev+210411.498d5b

**Expected behavior**
Old config values should be passed to new ENV

**Workaround**
User have to re-do their mail settings.

**Comment by FatihKoz** [comment]
Also app name is being read from config\app instead of user's own config.php

**Comment by FatihKoz** [comment]
Add Google Captcha to the list ... Old config had settings for it to be defined, new env does not and new config/captcha.php is not pointed at env (+ get overwritten by update)

**Comment by FatihKoz** [comment]
Sent a pr to fix the captcha ...

**Comment by nabeelio** [comment]
Are the settings correct in the `env.php` file?

**Comment by nabeelio** [comment]
And where did you setup the mail config?

**Comment by nabeelio** [comment]
Ok I added a note in the Discord about this. I forgot - this was expected and one of the problems I was solving with moving to the `env.php` file.

**Comment by FatihKoz** [comment]
How were they defined ?

Every setting was in the config, and it was working from the day i added
them.

Type, server, user, pass, sender name, sender address, port, encription ...

Was using smtp with my own mail server settings, now no matter what i do,
it is not working.

Will dig deeper to find which setting from the env is not being read/used.
-- 
B. Fatih KOZ

Sent from mobile device / Mobil cihaz ile gonderildi.

**Comment by FatihKoz** [comment]
Fixed ...
