### ISSUE TITLE
phpVMS Classic Importer

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#114]
### commit refs

- 6181fb0388d74d8b02ec5209b7d011a1db46c86b
- f58f4fdc39e3889ed27d3e1c20cf10d179e313e9
- 507ce5f24f7a74348e7946fbe771373e07c170d3

**Comment by nabeelio** [comment]
@web541 I made a bunch of changes, the lookup and stuff should work. I'm deferring the password stuff for the user at the moment. I have to study the reset password code, at the very end we can probably send out reset password emails, but only if a password token hasn't been sent yet. But it can cause some problems when testing, so I'm thinking about how to do it and handle the configuration

**Comment by nabeelio** [comment]
507ce5f24f7a74348e7946fbe771373e07c170d3

**Comment by web541** [comment]
I'll give it a quick test.

**Comment by nabeelio** [comment]
Basic flight import should be working too

**Comment by web541** [comment]
Yep, all working so far

**Comment by nabeelio** [comment]
Cool. If you want to take a pass at the PIREP import, you can. Seems like a few ENUM types need to be added for different ACARS programs, though I'm not sure if that's the best way.

I see a `log` column, separated out by new lines... that would need entries in the ACARS table, with the `AcarsType::LOG` type. Though I might have some more work to do around that.

The flight import still needs converting of the `route_details` data structure, also going into the `acars` table, with `AcarsType::ROUTE` (see the `PirepService::saveRoute()` method.
