### ISSUE TITLE
User set on leave after failed pirep

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1142]
If the user has a failed pirep such as from a simulator crash etc, the pirep gets deleted and the user is listed as having no recent pirep.   The the cron sends the pilot on leave ignoring the list of previous pireps.  In my case it happened to me so I saw the issue.  It has also happened to my most active pilot today.

**Version**
Version 7.0.0-dev+210414.bffc4f
ACARS beta release, version 1.0.0.1343

**To Reproduce**

1. Somehow get a failed Acars pirep  -  from sim crash etc
2. Wait till it is deleted then check users last pirep
3. Wait for cron to work though user is set on leave

**Expected behavior**
I would expect the last pirep to drop back to the last filed pirep rather then no pirep

[cron-2021-04-13.log](https://github.com/nabeelio/phpvms/files/6311065/cron-2021-04-13.log)
[laravel-2021-04-14.log](https://github.com/nabeelio/phpvms/files/6311070/laravel-2021-04-14.log)

**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)

**Comment by nabeelio** [comment]
Just a note for myself or whoever wants to fix this:

- UserService needs a new method to get the latest user PIREP
- This should be called whenever a PIREP is deleted
- The pilot leave check should see if the latest user PIREP exists, if it doesn't call the above method to update it

**Comment by nabeelio** [comment]
I think this is fixed now. If not, let me know I'll reopen
