### ISSUE TITLE
MOGAS or 100LL prices are not being used

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1145]
**Describe the bug**
Even though we have the ability to enter MOGAS and 100LL fuel prices for airports, we do not have safety defaults for them and if any of them are selected at subfleet level they are not being used for pirep finance / fuel costs.

JETA1 is used regardless of subfleet fuel type settings.

**Version**
7.0.0-dev+210415.61739c

**To Reproduce**
1. Add 100LL price to an airport
2. Edit a subfleet to use 100LL as fuel type
3. File a manual pirep departing from the airport you edited in step 1 and use an aircraft of the subfleet you edited at step 2
4. Accept that pirep
5. Check finances, you will see that JETA1 price is used for fuel cost

**Expected behavior**
Pirep Finances should follow subfleet fuel type settings and we should have some safety defaults for all fuel types to prevent errros.

**Comment by dougjuk** [comment]
I agree, I should have pointed this out also.  I have set all my sub fleet to JetA no matter what type
