### ISSUE TITLE
News entry issue

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1152]
**Describe the bug**
I am not sure if this is just my system or a bug in phpvms.  But if you make a new news item in the menu and press add nothing happens.  However it does post but the admin page does not refresh and show the addition.  I ended up pressing 5 times last night and making 5 entries of the same thing.  Today I I pressed once and waited, nothing happened again.  So I opened another tab and called my website up to see it had posted.  I had to refresh the admin page for it to show it was posted.

**Version**
dev 210421.254532
**To Reproduce**
1. Go to admin section
2. enter new news item and press add
3. wait to see if screen updates.  If it does not open another browser to check if item has posted
4. If it has posted refresh admin page to check.

**Expected behavior**
Once you press add the page should refresh showing the news item in the list above

**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)

**Comment by FatihKoz** [comment]
Similar issue happened to me, but it was not adding news, instead it was updating a flight ... I ended up clicking save 5 or 6 times, suspecting myself misclicked.

SimBrief form was not getting the updated data even though I was sure that fields were updated from admin side.

I think this may be a kind of caching issue, where updates/new entries does not update the cached data somehow.

**Comment by dougjuk** [comment]
I have an update, I wrote a news item pressed add then left it.  It did add the news item as above but rather than refresh it I waited.  It did refresh about 1 to 1.5 minutes after pressing add.  So it looks like it is related to the message Nabeel has posted about email delay.

**Comment by dougjuk** [comment]
Just confirmed that this is the issue described by Nabeel.  Just set email back to default.  Although email is not working there is now no delays on adding news.

**Comment by FatihKoz** [comment]
I think this issue is closed with the improvements applied for mail/notifications.
