### ISSUE TITLE
Error when trying to add new flights (schedule) after clean install

### ISSUE THREAD

**Issue by oudrun** [nabeelio/phpvms#1156]
After clean install and adding airports, subfleet,fare and aircraft I try to add a "flight" and get this error showing up in reference below.

https://flareapp.io/share/VP6kd237#F65

**Version**
Latest dev. Version 7.0.0-dev+210423.ec6cb4

**Comment by nabeelio** [comment]
![image](https://user-images.githubusercontent.com/99736/116007654-e1875e80-a5de-11eb-905c-e7375150af5a.png)

**Comment by ollimaz** [comment]
@nabeelio or @oudrun this issue could be closed too
