### ISSUE TITLE
Add to "Frontpage"or module from admin

### ISSUE THREAD

**Issue by supernovasurfer** [nabeelio/phpvms#1162]
Using phpVMS for approx 11 years... Thanks to Nabeel 

**Is your feature request related to a problem? Please describe.**
Not related to a problem as such , but for ease of use on admin side

**Describe the solution you'd like**
Publish to "frontpage" or "navbar" etc options via admin
perhaps with a feature rich editor.

When pages and links are created on admin , to be deployed to the site module as needed

**Describe alternatives you've considered**
Reading up and trying to add to the blades as needed. 

**Additional context**
Like we had via the earlier phpVMS admin, perhaps enhanced.

**Comment by FatihKoz** [comment]
When you add pages from backend (admin) their links are automatically published at frontend (navbar) , also modules "can" put their links to your navbar if they are designed to use that feature (or have a frontend blade/view) ...

For having rich text editor and being able to insert nicely formatted news/pages is what I want too, hopefully it will arrive some day but for links to navbar/sidebar I think we already have it (if I am not mistaken your request).

Best wishes

**Comment by supernovasurfer** [comment]
Ah yes understood , I did add to navbar via admin and the link was added.

We have a publish to "front page" on admin ? where a Document gets published to the mainpage ( say above the new pilots
 in your skin) 
Regards

**Comment by nabeelio** [comment]
Hey. For now, you need to modify that template in your skin to add whatever you want. I purposefully haven't really done anything with that page and most of the content that was there before is on the pilot dashboard after you log in.

**Comment by supernovasurfer** [comment]
Hey Nabeel, Oh yes understood , super ! Thanks
