### ISSUE TITLE
Undefined constant 'INTL_IDNA_VARIANT_UTS46' 

### ISSUE THREAD

**Issue by supernovasurfer** [nabeelio/phpvms#1175]
**Describe the bug**
When attempting to change a setting in the vmsAcars settings via the site admin panel........ an error is thrown
**Undefined constant 'INTL_IDNA_VARIANT_UTS46'** 

**Version**
phpVMS version 7.0.0 -dev

**To Reproduce**
1. Go to 'admin' >>>> 'addons'>>>>'VMSacars'

2. Click on : Fare entry is required
Entries for the fares are required to be entered .......checkbox 

3. Scroll down to 'Stacktrace error page line 141'

**Expected behavior**
The setting change in the vmsAcars module is applied.

**Screenshots**
Attached Here

![issue1](https://user-images.githubusercontent.com/83442181/117391233-29768180-af0d-11eb-803c-f9f6aaa7906f.png)
![issue2](https://user-images.githubusercontent.com/83442181/117391241-2da29f00-af0d-11eb-98b3-41ef5e47f900.png)

**Comment by nabeelio** [comment]
Hmm I will have to research this - this looks like a problem with the PHP install, maybe a missing extension

**Comment by supernovasurfer** [comment]
Thanks Nabeel

I have'nt yet checked if the setting change does get applied to the pireps( The checkbox ticked or unticked does happen though)

**Comment by nabeelio** [comment]
This looks like it could be related to an older version of the intl extension. Can you check with your host that the latest is installed? Can you provide your PHP version and a also the version of that ext?

**Comment by nabeelio** [comment]
This also looks like something with parsing the domain. Is the APP_URL set in your `env.php` and doesn't have any non-ASCII characters?

**Comment by nabeelio** [comment]
On Discord, if you can DM me that value, I can see if I can duplicate it tomorrow.

**Comment by supernovasurfer** [comment]
Sure..will get on it and try and get the details

**Comment by supernovasurfer** [comment]
> 
> 
> This looks like it could be related to an older version of the intl extension. Can you check with your host that the latest is installed? Can you provide your PHP version and a also the version of that ext?

So I've got php version 7.3 installed , INTL enabled ...attaching the screenshot


![INTL](https://user-images.githubusercontent.com/83442181/117451987-daf2d280-af60-11eb-95ed-4bc4257f4303.png)

**Comment by nabeelio** [comment]
Ok, that's an older INTL version. Trying to find a fix for that but can you see if you can get intl updated?

**Comment by supernovasurfer** [comment]
I'm on a shared host, not sure I can manage...going to try

**Comment by nabeelio** [comment]
Though I'm adding a polyfill now which should address this

**Comment by supernovasurfer** [comment]
Ah great

**Comment by nabeelio** [comment]
Yeah, that would a problem on shared hosts. Wait for the pull request to be merged into the latest dev and that should show up in the Discord as being ready, then try that one out.
