### ISSUE TITLE
laravel-helpers is outdated and causes errors on .../admin/flights/create

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#1180]
**Describe the bug**
Old version of sebastiaanluca/laravel-helpers causes errors. Can't run composer install and https://royalevest.de/admin/flights/create returns an error

**Version**
latest dev

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Flights'
3. Click on 'Add Flight'

Error on composer install:
    - sebastiaanluca/laravel-helpers is locked to version 6.0.0 and an update of this package was not requested.
    - sebastiaanluca/laravel-helpers 6.0.0 requires php ^7.3 -> your php version (8.0.5) does not satisfy that requirement.
Other error:
    Unsupported operand types: array & int

`if (!function_exists('in_mask')) {

    /**

     * Return true/false if a value exists in a mask

     *

     * @param $mask

     * @param $value

     *

     * @return bool

     */

    function in_mask($mask, $value)

    {

        return ($mask & $value) === $value;

    }

}`

**Comment by nabeelio** [comment]
Please try the latest dev. I removed the library that was holding back PHP 8 compatibility

**Comment by ollimaz** [comment]
Yes the installation with composer is working now. But there are still errors when trying to create a new flight at https://....net/admin/flights/create

**Comment by nabeelio** [comment]
Can you supply the logs/those errors?

**Comment by FatihKoz** [comment]
#1156 has some more info about the issue, even a flare share link (caused by php8 / operand type)

@oudrun was using php8 when he faced that error, recently switched back to 7.4.xx series I think.

**Comment by ollimaz** [comment]
Well I think I fixed that issue. But now the script isn't beeing loaded, because the script is made for the edit fields.blade

**Comment by FatihKoz** [comment]
What you did is not fixing the problem, you just removed a necessary
dynamic array, put a fixed value (zero) instead ...

Of course that will broke the schedule days logic :(
-- 
B. Fatih KOZ

Sent from mobile device / Mobil cihaz ile gonderildi.

**Comment by ollimaz** [comment]
No it seems that the days are saved in a mask. The enum sets monday to a 1 and sunday is representing a 64. The days acutally arent saved in an array, they are saved in an int. The in_mask operation makes a bitwise comparison. So 127 represents all days beeing selected. In PHP 7 an empty array was representing an 0 and a bitwise operation was successful. Since in PHP8 they change that its important to set it to 0 or null. 
1 = 1            monday
2 = 10          Tuesday 
4 = 100        Wednesday 
8 = 1000     Thursday 
16 = 10000 Friday 
...

Soo
1000101
Represents Monday, Wednesday and Sunday beeing selected.

The sripts aren loading because only the edit.blade.php imports them. The create.blade.pho in /resources/views/admin/flights doesnt.

**Comment by FatihKoz** [comment]
Yes, you are right, my mistake sorry ... I just thought that you are returning 0 for all, in fact you were returning 0 only for the create view :)

**Comment by nabeelio** [comment]
It's happening only under PHP 8? I need to install PHP 8 and see if I can duplicate it

**Comment by nabeelio** [comment]
Pushed a couple of fixes, see if that helps

**Comment by ollimaz** [comment]
Yes. For me this happend in PHP8 before we had no issues with that or maybe an extension had overwritten that function 🤷‍♂️

**Comment by ollimaz** [comment]
The error has been cleaned. Thank you @nabeelio 

But there is still the issue with no scripts beeing loaded. They are only loaded in 
phpvms/resources/views/admin/flights/edit.blade.php and not in 
phpvms/resources/views/admin/flights/create.blade.php

**Comment by nabeelio** [comment]
I don't know what "no scripts being loaded" means. Is there an error? Example? Screenshots?

**Comment by ollimaz** [comment]
This is how it looks. No datepicker and no fancy days selector
![grafik](https://user-images.githubusercontent.com/62832771/118856484-49c41a00-b8d7-11eb-9fd5-c337ce6382cd.png)

This is how it looks when editing and how it should look like:
![grafik](https://user-images.githubusercontent.com/62832771/118856684-82fc8a00-b8d7-11eb-9220-c06d8f743a11.png)

**Comment by nabeelio** [comment]
Is this on the default skin? And what's in the error console?

**Comment by ollimaz** [comment]
Jep. Its the default skin! Well there is no error. In [https://github.com/nabeelio/phpvms/blob/352f1ee9f8c7fed02aea619e2dad822af114b0ae/resources/views/admin/flights/edit.blade.php](url) at line 31 the scripts are included in [https://github.com/nabeelio/phpvms/blob/352f1ee9f8c7fed02aea619e2dad822af114b0ae/resources/views/admin/flights/create.blade.php](url) they aren't

**Comment by ollimaz** [comment]
I think this is what causes this "error" but this is just a shot. Idk

**Comment by nabeelio** [comment]
I see what you mean now. Thanks for pointing that out. Pushing a new update to dev.

**Comment by ollimaz** [comment]
Thanks. Jep I didn't know how to explain it in a better way than showing the lines :|
