### ISSUE TITLE
PHP Version (issues with php8)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1181]
**Describe the bug**
Although php8 is not fully or officially supported by phpvms, [https://docs.phpvms.net/requirements](url) does not contain this info. And the requirements page is misleading people.

`PHP 7.3 or up, extensions required (most of these are installed by default):`

**Version**
All

**Expected behavior**
Either docs should clearly indicate php8 situation or it should be fully supported.
`PHP 7.3 or up (but NOT PHP8), extensions required (most of these are installed by default):`

**Screenshots**
![req](https://user-images.githubusercontent.com/74361521/117867460-15ca7280-b2a1-11eb-8527-58477a88d676.png)

**Comment by nabeelio** [comment]
Good call, I'll amend the docs
