### ISSUE TITLE
Email definition

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1196]
**Is your feature request related to a problem? Please describe.**
At the moment I believe all admin emails go to admin users in particular user 1.  (I stand to be corrected)
(The Admin email setting that is in settings was used to let us know about backups which have been stopped.)
My CEO has admin access and does not want the admin emails every time a pirep is submitted etc

**Describe the solution you'd like**
To be able to use the settings section to configure who gets any admin emails and stop the auto sending to admin users.
Also that would enable me to send admin emails to the admin mailbox rather than my personal email.

**Comment by nabeelio** [comment]
I'll address this as part of https://github.com/nabeelio/phpvms/issues/433
