### ISSUE TITLE
Unable to create a new flight

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1199]
**Describe the bug**
When you want to create a flight manually `trying to get propery 'id' of non object` error is displayed, `admin.flight.scripts` is the source.

**Version**
Any version after commit #e3c3c81
https://github.com/nabeelio/phpvms/commit/e3c3c81d19d6577e7555f4d50a55666a6518b0b2

**To Reproduce**
1. Go to **admin -> flights**
2. Click on **Add Flight**
3. See error

**Expected behavior**
Manual flight entry should be working

**Comment by dougjuk** [comment]
Yes I agree I get error 500 when trying to create a flight

**Comment by FatihKoz** [comment]
![error](https://user-images.githubusercontent.com/74361521/119220228-3771f800-baf2-11eb-9368-1f2f5905ad85.png)

Working on it for a quick fix

**Comment by dougjuk** [comment]
Its odd I don't get the error like you I get a error 500 blank screen

**Comment by FatihKoz** [comment]
It is the debug option controlled by env.php ... What you see is ok for production (live site) 'cause debug should be **false** there, I am getting the same on too.

But for development (my local server) it is set to **true**, so I get the full details with stacktrace etc.
