### ISSUE TITLE
API Items need

### ISSUE THREAD

**Issue by lorathon** [nabeelio/phpvms#120]
Some of the following would be nice to have.  Some may be pointless.  Some may come later 

- [x] GET All Airports
- [x] GET Aircraft info (based on id | reg | tail number)
- [x] GET All Aircraft
- [ ] POST Schedule Search (based on dep/arr/aircraft/etc...  One, two or all....)
- [ ] GET users on line
- [ ] On POST of ACARS update data return time remaining?  (this may not be needed)
- [x] POST PIREP Prefile return is missing arr airport data.  Only dep airport data included

**Comment by nabeelio** [comment]
Why a `POST` for the flight search?
There is a `GET` for it, I haven't documented it yet, but it's `/api/flights/search`,  [see this for the URL params](https://github.com/nabeelio/phpvms/blob/master/app/Repositories/FlightRepository.php#L44)

So `/api/flights/search?depicao=KJFK`. I need to add more parameters, I have a ticket for distance/level parameters maybe

**Comment by nabeelio** [comment]
RE: Users online - is this more the currently active flights, or you want to know who's actually logged in? For active flights, I have that built already, just needs the REST interface. For who's actually on, that'd be a bit more involved and would need some updates, but doable.

**Comment by lorathon** [comment]
The POST should have been a GET (sorry)

Time remaining not really necessary but was with the old phpvms.  Live flights for the GET on users would be fine.

**Comment by lorathon** [comment]
List of users with pirep

**Comment by nabeelio** [comment]
I've added the aircraft list, I'm going to update the docs once I push it up, but you probably want another one that I haven't added yet (I will this weekend)... it will be like `/api/user/flight`, which will return to you the the aircraft that the user has permission to (as-per what's assigned to their rank)

**Comment by nabeelio** [comment]
The other thing for the flights search, I'm adding in the day-of-week specifier. I'm also adding a setting to be strict about "flights for today", which, if it's enabled, if today is a Tuesday, it will only return flights that are available on Tuesdays. 

There's another setting that is a restriction on flights only from their hub being available, it will further restrict based on that. You won't have to do anything to handle those, but just so you're aware of if you're doing a flight search and those settings are enabled, then you might not get results back.

The same filtering will apply on the web interface.

**Comment by nabeelio** [comment]
Added a few more APIs:

- `/api/airlines` - Paginated list of the airlines
- `/api/airlines/{ID}` - Get info about a specific airline
- `/api/flights` - Paginated list of all of the flights
- `/api/settings` to retrieve the VA settings, like the weight units, etc.

**Comment by nabeelio** [comment]
Closing this to consolidate tickets
