### ISSUE TITLE
API GET Flight

### ISSUE THREAD

**Issue by lorathon** [nabeelio/phpvms#121]
How does this work?  I can not get anything but a 404

`GET /api/flight/{FLIGHT ID} - Return details about a given flight`

Tried
table id = elY5mQ5Q4Q1a
airline_icao.flight_number
flight_number
1 (only one flight in table)
airline_id.flight_number

**Comment by nabeelio** [comment]
Sorry, typo in the doc. should be `/api/flights/{ID}`. BTW, the list is here:

https://github.com/nabeelio/phpvms/blob/master/app/Routes/api.php

**Comment by nabeelio** [comment]
The lookup via code + flight number doesn't work yet, that's on my list.
