### ISSUE TITLE
Give an option to disable storing of user IP address

### ISSUE THREAD

**Issue by Simssmith** [nabeelio/phpvms#1217]
**Is your feature request related to a problem? Please describe.**
Privacy/complaint concern regarding collecting and storing user IP. 

**Describe the solution you'd like**
Provide an option where phpVMS will not store user IP in user table or anywhere else in the database.  This way whole the database access can be given to other admin for troubleshooting or creating analytics without worrying about user privacy. 

**Describe alternatives you've considered**
encrypt the IP in the database, so when DB is shared it will not provide IP of its users. 

**Additional context**
In the event the IP is needed (security breach/abuse by some users), the webhost can provide this as this already logged by webserver/load balancer/firewall/etc.

**Comment by nabeelio** [comment]
I forgot about this - I'll remove the IP completely
