### ISSUE TITLE
Simbrief rendering errors on PHP 8

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#1229]
```
[previous exception] [object] (TypeError(code: 0): round(): Argument #1 ($num) must be of type int|float, App\Models\SimBriefXML given at /home/***/***/app/helpers.php:372)
[stacktrace]
```
[1622987267_8B5A7C95B6.zip](https://github.com/nabeelio/phpvms/files/6604339/1622987267_8B5A7C95B6.zip)

**Comment by lunairdev** [comment]
I saw this error im my logs. I thought it was only me, I solved by modifying the sectohhmm function of app/helpers.php : 
`if (!function_exists('secstohhmm')) {
    /**
     * Convert seconds to hhmm format
     *
     * @param $seconds
     */
    function secstohhmm($seconds)
    {
        $seconds = round((float)$seconds);
        $hhmm = sprintf('%02d%02d', ($seconds / 3600), ($seconds / 60 % 60));
        echo $hhmm;
    }
}`

**Comment by nabeelio** [comment]
You removed the type specifier?

**Comment by FatihKoz** [comment]
He added I think, default/current helper function does not have `(float)` before `$seconds`

**Comment by FatihKoz** [comment]
Just added it as a pr, to see the current file and solution together.
