### ISSUE TITLE
Unable to access user screen in admin if user is associated to an inactive airlines

### ISSUE THREAD

**Issue by Simssmith** [nabeelio/phpvms#1231]
**Describe the bug**
We deactivated few airlines in our VA. Then when we tried to edit a user associated to a deactivated airlines the user section in admin broken. It gives following 500 error

ErrorException
Trying to get property 'icao' of non-object (View: /phpvms/resources/views/admin/users/table.blade.php);

```
    public function getIdentAttribute(): string     {
        $length = setting('pilots.id_length');
        return $this->airline->icao.str_pad($this->pilot_id, 
                 $length, '0', STR_PAD_LEFT);
    }
```
The fix was to go to backend/database and move all the user from deactivated airline to a activated airline with a SQL like this.  

`UPDATE phpvms.users SET airline_id = '1' WHERE (id = 3);`

Admin / User screen started to worked normal

**Version**
Version 7.0.0-dev+210603.ad86e9 

**To Reproduce**
1. Have user associated to an airline
2. Deactivate the airline
3. Go to admin / user section and edit this user
4. admin / user screen will throw a 500 error as described above. 

**Expected behavior**
admin  / user screen should work normal if airline is deactivated user there are user still associated to this airline. 

**Screenshots**

**Additional context**
none

**Comment by nabeelio** [comment]
Thanks. This is related to https://github.com/nabeelio/phpvms/issues/434. The way I'm doing the inactive/soft deletes now needs to change. I will see about addressing this next since it seems to come up kind of often.

**Comment by FatihKoz** [comment]
Should be closed. That merged commit fixes this too (tried on local env by de-activating an airline and also by deleting it)
