### ISSUE TITLE
Phpvms V5 to V7 Importer

### ISSUE THREAD

**Issue by warathand** [nabeelio/phpvms#1235]
Doing a legacy import from v5 to v7 produces a server 500 error and the database is not imported are required.

**Comment by nabeelio** [comment]
Need more details. Any logs? If you look at the database afterwards, any clues as to where the import might have stopped or errored out?

**Comment by warathand** [comment]
Based on larvael logs, 

 `[2021-06-09 07:12:00] production.INFO: Table groups doesn't exist`
 `[2021-06-09 07:12:00] production.INFO: Table airlines doesn't exist `

The importer is unable to detect or sense the existing db table to be imported

`[2021-06-09 07:12:06] production.ERROR: View [home] not found. {"exception":"[object] (InvalidArgumentException(code: 0): View [home] not found. at /home/singap08/public_html/test/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)
[stacktrace]`

A fresh db has been used with the default theme. 

Not sure if they are any help
