### ISSUE TITLE
Trait "Kleemans\AttributeEvents" not found 

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#1239]
After getting the newest dev I tried to login and got following error on **every site**
`Symfony\Component\ErrorHandler\Error\FatalError Trait "Kleemans\AttributeEvents" not found`

Note I am using PHP8. Don't know if this has an effect

Error:
https://flareapp.io/share/67O6LevP

**Comment by arobsco** [comment]
How did you update? Have you tried running composer update on your server?

**Comment by ollimaz** [comment]
Hi @arobsco. I did run 'composer install' this however changed noting. What I did was deleting the vendor directory and I run composer install again. And now it works. Thanks for your Input :)
