### ISSUE TITLE
Abandoned packages

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#1240]
Running composer gives the user a warning about abandoned packages:
`Package akaunting/money is abandoned, you should avoid using it. Use akaunting/laravel-money instead.
Package semver/semver is abandoned, you should avoid using it. No replacement was suggested.`

Maybe this packages should be replaced/removed for stability and lifecycle of the app.

**Comment by nabeelio** [comment]
I can look into using laravel-money but semver has no alternative.
