### ISSUE TITLE
E-Mail wrong title on reject

### ISSUE THREAD

**Issue by Jannis-D** [nabeelio/phpvms#1246]
**Describe the bug**
When a pilot got an email for a rejected PiRep, the title still says: PirRep accepted!

**Version**
Recent

**To Reproduce**
1. Reject a PiRep and have a look at the mail.

**Expected behavior**
Title should be: "PIREP rejected!"

**Screenshots**
![image](https://user-images.githubusercontent.com/42517031/122080837-e27a8680-cdfe-11eb-9026-be1823c6174d.png)

**Comment by nabeelio** [comment]
Haha
