### ISSUE TITLE
Blank subfleet created when importing a bad csv file

### ISSUE THREAD

**Issue by Tayrael** [nabeelio/phpvms#1250]
**Describe the bug**

Caused by import of an incorrect csv file which lacks the closing comma for the subfleets, the system creates a blank subfleet which cause the 500 Server Error when try to edit the flights from the admin panel

**Version**
Version 7.0.0-dev+210620.cde6fb

**To Reproduce**
1. Create a new flight using the CSV flight Template
2. Do not include the comma after last subfleet
3. Import the Flights from CSV created
4. After importing you will see a new "Blank" subfleed created on the subfleet page

[FlyItaly Flights.ods](https://github.com/nabeelio/phpvms/files/6686301/FlyItaly.Flights.ods)

**Comment by macofallico** [comment]
Just delete the subfleet and you are good to go.....

**Comment by nabeelio** [comment]
That should be valid - what's the 500 error message? Need some more information. It seems to have imported correctly.

**Comment by Tayrael** [comment]
> 
> 
> That should be valid - what's the 500 error message? Need some more information. It seems to have imported correctly.

Please find the attached log.
[laravel-2021-07-21.log](https://github.com/nabeelio/phpvms/files/6859280/laravel-2021-07-21.log)
