### ISSUE TITLE
Unable to pass step2 from Docker container VMS

### ISSUE THREAD

**Issue by erikmevis** [nabeelio/phpvms#1252]
Hello,

I have an issue with step2 with the DB setup. After following the above, i get this error:

https://pastebin.com/FfCqTndJ

_Originally posted by @erikmevis in https://github.com/nabeelio/phpvms/issues/1096#issuecomment-868212239_

**Comment by erikmevis** [comment]
> Hello,
> 
> I have an issue with step2 with the DB setup. After following the above, i get this error:
> 
> https://pastebin.com/FfCqTndJ
> 
> _Originally posted by @erikmevis in [#1096 (comment)](https://github.com/nabeelio/phpvms/issues/1096#issuecomment-868212239)_

nginx_1 | 172.21.0.1 - - [25/Jun/2021:05:36:46 +0000] "POST /install/envsetup HTTP/1.1" 302 378 "http://localhost/install/step2?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

mysql_1 | 2021-06-25T05:36:46.466362Z 39 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.467314Z 40 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.467946Z 41 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.475747Z 42 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.476332Z 43 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.481102Z 44 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.482642Z 45 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

mysql_1 | 2021-06-25T05:36:46.483663Z 46 [Note] Access denied for user ''@'phpvms_app_1.phpvms_default' (using password: NO)

nginx_1 | 172.21.0.1 - - [25/Jun/2021:05:36:46 +0000] "GET /install/step2 HTTP/1.1" 200 16531 "http://localhost/install/step2?" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"

app_1 | 172.21.0.5 - 25/Jun/2021:05:36:46 +0000 "GET /index.php" 200

**Comment by ollimaz** [comment]
Seems like phpvms couldn't save your credentials to env.php. Does the user who is running the webserver has needed permissions for /var/www/ ?

**Comment by erikmevis** [comment]
I am not sure a what user that could be since I am using docker.

My local account is an admin.

**Comment by erikmevis** [comment]
Checking in on this, Like I said, I am trying the docker setup and was run as admin.

**Comment by nabeelio** [comment]
Mac or Windows host?

**Comment by erikmevis** [comment]
Windows,

I'm at a point also, that it gets the bootstrap error.

**Comment by nabeelio** [comment]
You'd have to look that up for Docker on Windows. I don't know how those permissions work. I never got it working quite right on my Windows machine
