### ISSUE TITLE
Unable to Access Public Folder

### ISSUE THREAD

**Issue by benmaxlevy** [nabeelio/phpvms#1254]
Hello, I'm attempting to use `storage:link` to create a symlink between my storage/public directory to the public folder. It works, however, I cannot access the files within the public folder via either A) `asset()` or B) `/storage/uploads/...` in the browser. Thank you.

**Comment by nabeelio** [comment]
You might have to consult the Laravel docs on this one. Where are you trying to do this? What is the error?

**Comment by benmaxlevy** [comment]
I did. I uploaded files to the storage folder, and then I did `storage:link`, but even with the symlink, I cannot access these public files through a simple route, nor through `asset()`

**Comment by benmaxlevy** [comment]
Any ideas?

**Comment by nabeelio** [comment]
Where are you trying to do this? What's the exact error?

**Comment by nabeelio** [comment]
I think it would depend on how your webserver is set up. I don't know - you have to look at the Laravel docs. phpVMS isn't doing anything special with storage, it's all stock Laravel.

**Comment by benmaxlevy** [comment]
I'm doing this in a blade. I'm using the default docker settings.

**Comment by nabeelio** [comment]
I have not tested that in Docker. You haven't answered about the error or what exactly you're seeing.

**Comment by benmaxlevy** [comment]
It's just 404.

**Comment by nabeelio** [comment]
Okay. You need to provide more information. Logs? Have you researched about Laravel in Docker and how storage links will work? Or if symlinks would work right? I think this is more of a Laravel issue so I'd ask for some guidance on their forums about those links in Docker

**Comment by benmaxlevy** [comment]
You led me on the right track. I had to `docker-compose exec`, and then run `php artisan storage:link` in the container. Thank you.
