### ISSUE TITLE
Install Step 2 Issue

### ISSUE THREAD

**Issue by benmaxlevy** [nabeelio/phpvms#1286]
When I go to press "Setup Database" on page 2 of the setup, it just brings me to the top of the page. It was able to connect to the DB, and I get no error message. Thanks!

**Comment by FatihKoz** [comment]
Any more details ? Maybe logs , the server setup maybe local with docker or live , some versions ... Those may help people trying to figure out what is going on at your end ! Without them your input in meaningless at best :(

https://docs.phpvms.net/help/#information-required

**Comment by benmaxlevy** [comment]
My bad!
