### ISSUE TITLE
Flight type not matching Acars flight type | Acars (Bug Report)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1305]
When a flight is loaded via vmsAcars, flight type is not loaded correctly (or not considered at all).   
Also flight types do not match in text and number. phpVMS has 15 flight types, while vmsAcars offers only 10.

**Version**
Non-relevant

**To Reproduce**
1. Pick a flight, edit its Flight Type to something like Charter Cargo/Mail or VIP etc'
2. Run vmsAcars, find that edited flight and click load
3. See the error, even though you load a Cargo flight, vmsAcars will say it is a Passenger flight.

**Expected behavior**
1. Correct flight type should be selected when a flight gets loaded.
2. vmsAcars flight type list should match phpVMS flight types.

**Screenshots**
![FlightType_NotMatching](https://user-images.githubusercontent.com/74361521/132600772-befbe148-c340-4d0c-9a3f-2a48dd072d64.png)

![FlightType](https://user-images.githubusercontent.com/74361521/132600791-cc253aa1-40e4-4e6f-a07d-664483b348d3.png)

**Comment by FatihKoz** [comment]
Missing ones at vmsAcars;

G : Scheduled Pax (Additional)
O : Charter Pax (with Special Handling)
A : Cargo (Additional)
H : Cargo (Charter)
X : Technical Stop

**Comment by nabeelio** [comment]
Should be fixed now
