### ISSUE TITLE
Error on subfleets after importing flights

### ISSUE THREAD

**Issue by eugenio-vsn** [nabeelio/phpvms#1319]
**Describe the bug**
I started getting an error on Flights page of the pilot page. The issue was caused by some fleets that were created after I imported a list of flights. Important to mention I had no fleet created before importing the flights.

**Version**
7.0.0-dev+210923.f99af4

**To Reproduce**
1. Have no fleets registered
2. Import flights with subfleets on the CSV file
3. Once upload is completed, fleets will be created with no ICAO code
4. To see the error, visit Flights page

**Expected behavior**
There should be an exception handling to avoid having error 500 being shown on the Flights page.

**Additional context**
Log entry:
[error.txt](https://github.com/nabeelio/phpvms/files/7247903/error.txt)

**Comment by nabeelio** [comment]
Thanks - need to set the ICAO of any airlines that are imported/check that they're set on an import (in the case of an airline that's generated from the import)

**Comment by nabeelio** [comment]
Add `airline_id` to https://github.com/nabeelio/phpvms/blob/dev/app/Services/ImportExport/FlightImporter.php#L223 
And check other fields
