### ISSUE TITLE
Avoid calling MySQL executable for creating database

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#132]
Some (shared) hosts can potentially have the `proc_open` method blocked for security:

```
The Process class relies on proc_open, which is not available on your PHP installation.
```

- Rewrite the database creation code, and skip it in total during the installer for mysql (assuming that the user already creates the database)
- Including trying to connect to the database in the connection check code

**Comment by brent11292** [comment]
@nabeelio I am getting this error now: Wrong COM_STMT_PREPARE response size. Received 7 (SQL: select * from information_schema.tables where table_schema = id4231794_phpvms and table_name = migrations)

**Comment by nabeelio** [comment]
I found this, I can look into it as well, I see someone suggested a fix but I have to do some research if there are any side effects. They suggest contacting support, though. If you do that, can let me know what their answer is and if they have a fix?

https://www.000webhost.com/forum/t/wrong-com-stmt-prepare-response-size-received-7/66868/7

**Comment by nabeelio** [comment]
There's a new build up. I've forced disabled the emulation parameter, though the recommendation is to enable it, though enabling seems to have some other side effects. Give that a try. If that doesn't work and you get the same error, I'll come up with something.

**Comment by nabeelio** [comment]
@brent11292 Can you let me know what MySQL version they're running?

**Comment by brent11292** [comment]
@nabeelio Where would I find that? Currently using phpMyAdmin to manage the database.

**Comment by nabeelio** [comment]
@brent11292 if you can create a page called `info.php` and then upload it somewhere accessible; in it, put:

```php
<?php
phpinfo();
```

And shoot the link over.

**Comment by brent11292** [comment]
@nabeelio How would I do that? Sorry just new to all of this.

**Comment by nabeelio** [comment]
Create a new file that has that in it, upload it to your server, in the same folder as the index.php file

**Comment by brent11292** [comment]
Found out how to do it another way. Heres the version: 10.1.29-MariaDB

**Comment by nabeelio** [comment]
Interesting you're seeing it on Maria. Do you have the option for MySQL? Or is Maria the only variant?

**Comment by brent11292** [comment]
Maria is the only one showing up

**Comment by nabeelio** [comment]
There's a new build going up, should show up in the development channel when it's available. If an `env.php` was created, delete it, and try reinstalling

**Comment by brent11292** [comment]
Where would env.php show up if it was created?

**Comment by nabeelio** [comment]
The root folder for wherever you uploaded phpvms

**Comment by brent11292** [comment]
I found something called env.blade.php; should I delete it?

**Comment by nabeelio** [comment]
No, that would break things. It's in the root folder, next to the index.php file. It'll be in the folder that you uploaded everything into.

**Comment by brent11292** [comment]
Theres a env.php.example next to index.php

**Comment by nabeelio** [comment]
If you can download then upload the latest version that was just built, that has some extra logging too, so if you have issues, you can at least send me the log files so I can examine.

And ok, so the `env.php` didn't get written, so you should be able to just run the installer.

**Comment by brent11292** [comment]
Alright I will run it tomorrow and I will comment again if I run into anything. Thanks for the help!

**Comment by brent11292** [comment]
@nabeelio Same message comes up: Wrong COM_STMT_PREPARE response size. Received 7 (SQL: select * from information_schema.tables where table_schema = id4240382_phpvms and table_name = migrations)

**Comment by nabeelio** [comment]
Hey, can you tell me what's in the file called `VERSION`. And, can you download the files in the `storage/logs` folder, zip them up, and then upload them here? Thanks!

**Comment by brent11292** [comment]
Where would I find those?

**Comment by brent11292** [comment]
And are you talking about MySQL?

**Comment by nabeelio** [comment]
No, it's the phpVMS logs. Go to the folder where the index.php is, there's a storage folder, and then a logs folder inside of that. Just send me all the files in there in one zip.

**Comment by brent11292** [comment]
[Logs.zip](https://github.com/nabeelio/phpvms/files/1620864/Logs.zip)

**Comment by nabeelio** [comment]
I believe you might have the latest version. Can you redownload and reupload?

**Comment by brent11292** [comment]
Yeah tried that twice now and nothing seems to be working

**Comment by nabeelio** [comment]
Can you tell me what's in the VERSION file, that's in the same directory as the index.php?

**Comment by brent11292** [comment]
v7.0.0-8aacd8

**Comment by brent11292** [comment]
Alright, will continue tomorrow. Hope it gets fixed by then

**Comment by nabeelio** [comment]
I found a mistake I made, noticed it in the logs. Hopefully this next version will work.

**Comment by brent11292** [comment]
@nabeelio Still same error: Wrong COM_STMT_PREPARE response size. Received 7 (SQL: select * from information_schema.tables where table_schema = id4240382_phpvms and table_name = migrations)

**Comment by nabeelio** [comment]
Can you attach the latest log files, please?

**Comment by brent11292** [comment]
[Logs.zip.zip](https://github.com/nabeelio/phpvms/files/1624432/Logs.zip.zip)

**Comment by brent11292** [comment]
whoops included .zip by mistake

**Comment by nabeelio** [comment]
Is this still MariaDB? And do you know what version? Because it seems to be IDing itself as mysql 5.5

**Comment by brent11292** [comment]
10.1.29-MariaDB - MariaDB Server

**Comment by nabeelio** [comment]
I'd contact your support. According to the log, it's reporting:

```
[2018-01-11 22:57:51] dev.INFO: Detected DB Version: 5.5.30  
```

5.5.30 is a MySQL Version. The Maria DB version would read like the one you said, with `-mariadb` in it.

**Comment by brent11292** [comment]
Ok

**Comment by brent11292** [comment]
@nabeelio I got it to work. Just needed to change hosts.

**Comment by nabeelio** [comment]
Cool, can you send me the logs again, just so I can see if the tweak I made took effect?

**Comment by brent11292** [comment]
[logs.zip](https://github.com/nabeelio/phpvms/files/1624684/logs.zip)

**Comment by nabeelio** [comment]
Interesting, it still gives the DB version as `Detected DB Version: 5.7.20-log`, but it's ok, as long as it's working now.

**Comment by brent11292** [comment]
Yeah thats the version now.

**Comment by nabeelio** [comment]
But running on Maria still gives issues? Well it's alright, if it comes up again, I'll deal with it then. Thanks for your patience!
