### ISSUE TITLE
Show flight/pirep finances in pirep page

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#1326]
Actually to see a pirep/flight finances you must edit the pirep in admin panel.
![imagen](https://user-images.githubusercontent.com/16170732/135733637-3842a550-ae85-48a7-8558-66f401274612.png)

this information should be displayed in pirep too.
![imagen](https://user-images.githubusercontent.com/16170732/135733628-ce73931b-2349-4019-acac-01b74ebd6530.png)

**Comment by FatihKoz** [comment]
If somebody wants to add it to default theme, or his/her own duplicate/theme `$pirep->transactions` will give you all transactions for that pirep.
