### ISSUE TITLE
ICAO and IATA Code on PIREPS 

### ISSUE THREAD

**Issue by warathand** [nabeelio/phpvms#1346]
**Describe the bug**
Both ICAO and IATA codes would appear on PIREP when filed as shown on the screenshot 

Version: 7.0.0-dev+211103.358f0b

PIREP should only have either a single ICAO code or IATA instead of ICAO and IATA together / IATA and IATA together 

![Screenshot_1](https://user-images.githubusercontent.com/5642632/140439230-1c53a298-baee-4cc9-97d4-f0e62098b078.png)
![Screenshot_2](https://user-images.githubusercontent.com/5642632/140439258-027ac216-2f5d-48be-b4dd-d591417b6d80.png)

**Comment by FatihKoz** [comment]
:) latest commits fixed the “pirep ident” attribute but did not changed the blade files using it and designed for its old format.

Probably that blade file (and many more others) are using $pirep->airline->icao and $pirep->ident togetger.
