### ISSUE TITLE
Aircraft stays in state 2 (IN AIR) when Pirep deleted after sim CTD

### ISSUE THREAD

**Issue by jmconde** [nabeelio/phpvms#1362]
After a sim crash to desktop I was forced to delete the ongoing pirep, after that I was unable to start a flight again, peeking at the database the aircraft was in state = 2, IN AIR

**Comment by FatihKoz** [comment]
This does not look like a phpvms issue because v7 does not change aircraft states at all.

Either contact the module developer [if you are using Disposable Airlines (old module) or Disposable Basic (new one) it is me] or check your code controlling aircraft states.

**Comment by FatihKoz** [comment]
Should be closed, op not responding and this is not a core bug
