### ISSUE TITLE
Rank Up & Awards | Discord Notifications

### ISSUE THREAD

**Issue by Baba-IF** [nabeelio/phpvms#1367]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
So, it could be great to have a discord notification for `rank-up` & `award awarded`. In the same way that is done for the pirep notifications. 

**Describe alternatives you've considered**
Using the same way that is done for pirep & new user notification. Emeded.

**Additional context**
*Nothing to add*

**Comment by arv187** [comment]
@nabeelio With the discord notifications function working now, Can this now be easily implemented?

**Comment by nabeelio** [comment]
Yes, I'll take a look soon

**Comment by ArthurHetem** [comment]
We may need to close this one @nabeelio
