### ISSUE TITLE
Needing to approve pirep even when it is auto on

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1420]
**Describe the bug**
I have noticed that in certain circumstances I am having to go in an approve some of the maunal submitted pireps even when the system is set to auto approve.

**Version**
7.0.0-dev+220225.9d368e - Dispo theme V3 with both basic and special modules

**To Reproduce**

1. Select a flight from the schedule 
2. Go to manual pirep 
3. Fill in some basic details and save as draft
4. Go back to the pirep add the rest of the data and submit

**Expected behaviour**
It should auto accept the pirep as it does if you just file it without saving as draft

**Comment by FatihKoz** [comment]
Tried to replicate the steps.

Rank Settings;
![d1](https://user-images.githubusercontent.com/74361521/155972547-58756c35-5b92-4eed-8b99-e5961e9da567.png)

Step 2;
![d2](https://user-images.githubusercontent.com/74361521/155972722-0b96226a-5431-45b8-b7b6-ebd35f800038.png)
Step 3;
![d3](https://user-images.githubusercontent.com/74361521/155972764-38cc2e58-b0df-4c4a-bda1-1897c3cb16ac.png)
Step 4;
![d4](https://user-images.githubusercontent.com/74361521/155972517-e9d52a96-adb6-4176-a137-fcdefe95ce79.png)
![d5](https://user-images.githubusercontent.com/74361521/155972529-047b62aa-e2ee-4d66-811c-f7256494a4d3.png)

Here is the log;
[laravel-2022-02-28.log](https://github.com/nabeelio/phpvms/files/8152781/laravel-2022-02-28.log)

Disposable addons (including the theme) does not interfere with core's pirep processing stage and according to the log, looks like they do their jobs and cause no errors.

Will try do check core code step by step to see/find where it fails to read (or skip) reading the rank settings.

**Comment by FatihKoz** [comment]
Additional info,

- Directly submitting a manual pirep works just fine, **so there is definitely something going wrong when a pirep gets saved then submitted from the create/edit form.**

![d4](https://user-images.githubusercontent.com/74361521/155984568-2712ce06-00da-4301-9f05-c059e6a3f3b7.png)

- It even gets auto approved if it gets submitted from pirep details page after being edited.

![d6](https://user-images.githubusercontent.com/74361521/155984528-eab35889-ea64-480a-9325-7cd9a48beff2.png)
