### ISSUE TITLE
Laravel9 | Pirep Finance Service > Undefined Method

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1424]
https://github.com/nabeelio/phpvms/blob/9622657336dd95cc92276863731c2580fccbfae8/app/Services/Finance/PirepFinanceService.php#L243

`->value()` causes an exception of `production.ERROR: Call to undefined method App\Support\Units\Fuel::value()`

`->internal()` would be nice there ;)

**Comment by nabeelio** [comment]
Just add these issues to the PR
