### ISSUE TITLE
Introduce Semantic Release

### ISSUE THREAD

**Issue by cristianocasella** [nabeelio/phpvms#1432]
**Is your feature request related to a problem? Please describe.**
The last release is 2yrs old, also if the repo is still maintained, this is forcing people to use the dev release, that make hard to track progress and upgrades available.

**Describe the solution you'd like**
We could introduce in the GitHub Action a step for Semantic Release: https://github.com/marketplace/actions/action-for-semantic-release
More info on what Semantic Release is can be found here: https://semantic-release.gitbook.io/semantic-release/

**Describe alternatives you've considered**
Manually manage the release of new versions, instead relying on dev release.

**Additional context**
Semantic Release make the release process automated, you have just to add prefix to your commit to identify feat:(ure), fix: and other kind of changes, depending from the prefix used a new release, minor o major will be self-released.
Having a more structured release process could help also new contributor to have a clear overview about the project progress.
Once we decided that this could be a nice to have, I'm happy to send a Pull Request for introducing Semantic Release, I just would like to align first.

**Comment by FatihKoz** [comment]
I think another "alternative" solution is already being used, we get notices on every dev build.

![dev_release](https://user-images.githubusercontent.com/74361521/156922527-ed8e1ee7-b533-40af-919e-18c1cff20b6b.png)

And yes, the repo is still maintained actively :) Also using the dev release is required for many other things like acars support and core improvements, not using beta.4 is advised.

**Comment by cristianocasella** [comment]
I know that, but I don't consider this as a real alternative, you don't have a real changelog and you don't have evidence of eventual breaking changes.
At the same time having a release lifecycle is letting you to be able to plan conflicting changes on diverse releases

**Comment by cristianocasella** [comment]
And, you will be still able to use the dev branch and your current method, it's actually an addition, not a swap.

**Comment by FatihKoz** [comment]
Yeah it is being handled like this for a long time :) You always have a single "latest dev" , no in between versions or separate releases to download each dev build.

I do agree with you about the change log part though, it is hard to track the commits and important (probably code breaking) changes compared to beta4 (even compared to previous dev build).

**Comment by nabeelio** [comment]
Hi @cristianocasella yes, that's the goal. Just got a bit out of hand. I'm trying to get a full release out soon and then moving onto point releases after that. That was the goal with the betas and stuff

**Comment by cristianocasella** [comment]
That's great  @nabeelio, let me know if I can help you and/or if you are interested in the PR with semantic release

**Comment by nabeelio** [comment]
It's already configured in Github Actions and part of the build already. It's just a matter of fixing a few blocking bugs
