### ISSUE TITLE
Getting error on submitting or view manual pirep

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1444]
**Describe the bug**
I saw a divide by zero error in the logs the other day.  Today I forgot Acars and submitted a manual pirep.  I got an error when submitting it.  With app debug on it is a divide by zero error
**Version**
Version 7.0.0-dev+220314.128480 

**To Reproduce**
1. Submit manual pirep you get error
2. to clear it edit the pirep and add to planned distance

**Expected behavior**
Should submit and view the pirep even if no planned distance entered.

**Screenshots**
![error](https://user-images.githubusercontent.com/75090523/159064793-20bdee68-19e3-4020-b8b9-afbdcc04d934.png)

**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)

**Comment by nabeelio** [comment]
I think this is fixed
