### ISSUE TITLE
Message confirming that new news has been added

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#1451]
**Is your feature request related to a problem? Please describe.**
If you create a news and click on +add button nothing happen, so you do click again, finally if you go to admin dashboard realize that there are a news for each click that you did.

**Describe the solution you'd like**
Add a confirmation message when a news is added ¿And refresh admin dashboard?

**Describe alternatives you've considered**

**Additional context**

**Comment by dougjuk** [comment]
There was a bug with this way back, it all has to do with the task queue.  I think is you set the queue to the database it adds the news straight away.  I cannot recall the details right now.  If you search it is in discord.
