### ISSUE TITLE
Additional PIREP fields don't save correctly

### ISSUE THREAD

**Issue by RRJustin** [nabeelio/phpvms#146]
When marking an extra PIREP field as required, it does not save as being required.

**Comment by nabeelio** [comment]
Should also be fixed, let me know how this looks!

**Comment by RRJustin** [comment]
I installed the latest version. Still does not work for me. Also, when on the submit PIREP page, it shows "required" after the custom field name but does not actually make it required to be filled out. Still submits without error. This is also the case when manually changing the required value from 0 to 1 in the database. Still allows it to be submitted without error.

Also, there is a "Source" table column on the filed flights page.
![extra_fields](https://user-images.githubusercontent.com/35641891/35199718-c30aaa96-fec7-11e7-8e59-f5600dc56dc5.png)

**Comment by nabeelio** [comment]
Is this fixed now?
