### ISSUE TITLE
Incorrect text on ADD New AIRPORT

### ISSUE THREAD

**Issue by lesmar54** [nabeelio/phpvms#1460]
**Describe the bug**
This is a minor cosmetic bug that has occurred when using the ADD NEW AIRPORT module in that the FUEL cost inputs are referred to as a cost for lbs. The error is that on the virtual airline configuration I set units to kgs and litres and as such I would have expected the display to show the same 

**Version**
7.0.0-dev+220328.e2226b

**To Reproduce**
1. Go to 'Admin '
2. Click on 'settings '
3. Scroll down to 'Fuel Units'
4. Set Fuel Units to kgs. 
5  Click on 'airports'
6  Click on 'Add New '
see the error
**Expected behavior**
I would expect the text on the screen regarding fuel cost to reflect what the virtual airline has selected in the settings

**Screenshots**
Screen Shot added

**Additional context**
![Screenshot 2022-06-11 at 18 13 36](https://user-images.githubusercontent.com/22278416/173191936-2c0ca240-1663-4f87-a3e3-6ecab83498b5.png)

**Comment by lesmar54** [comment]
This should be an easy fix where the setting configuration is used to format the text for the fuel cost

**Comment by FatihKoz** [comment]
I do not think that this is a bug or typo... Database (or say core) unit types are fixed, so as far as I know that field is also fixed to lbs ('cause the core fuel unit is fixed to lbs/pounds)

Units you select at admin settings are for visual display, for the frontend in other words. So no matter what you select at settings, core unit requirements and core units will not change.

Hope this explanation helps

**Comment by lesmar54** [comment]
Thank you for the reply 
So if you set the fuel units to kg then any calculation and display should use the 1kg = 2.2 lbs to be correct 

If you input  a price for fuel of say 1.00 € per lb  you would expect any fuel display to show as such 2.20€  or  will it still say 1.00€ 

Hopefully you can answer this with your expert knowledge of V7

**Comment by FatihKoz** [comment]
All calculations made by the core will use LBS (regarding fuel and weight), no matter what you select in settings.

The displayed results however, if needed, can be converted to your local units.

I think it is more clear now.

Some examples for you, from a completed pirep of a live site;

![image](https://user-images.githubusercontent.com/74361521/173198550-9ca8b29c-cbf0-4f07-8162-45dccd35db25.png)

![image](https://user-images.githubusercontent.com/74361521/173198668-9ace6cc7-2196-4eb3-9e12-017c8d85f8b6.png)

![image](https://user-images.githubusercontent.com/74361521/173198604-c41b11c0-85c6-4581-8b63-3a3e8b5a2661.png)

![image](https://user-images.githubusercontent.com/74361521/173198632-faf53b0d-5989-4bf7-9869-5ed1cd96bc6e.png)
