### ISSUE TITLE
Fare notes not being returned in collections

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1465]
Even though the fare has notes, it is not being returned in the collection `"notes":""`

**Version**
7.0.0-dev+220328.e2226b

**To Reproduce**
1. Go to Admin > Fares
2. Edit one of your fares, add a note to it
3. Find a suitable place to dump the fare (like a pirep or a flight or simbrief form etc)
4. Check the dumped collection

**Expected behavior**
Notes should be visible in the collection and we should be able to use it

**Additional context**
This was working before, probably before laravel9 switch

![image](https://user-images.githubusercontent.com/74361521/178123306-0d744c7a-7008-4a77-8607-381c56c9ac68.png)

```
{"id":1,"code":"Y","name":"Economy","price":75,"cost":10,"capacity":189,"type":0,"notes":"","active":true,"created_at":"2022-07-09T14:27:23.000000Z","updated_at":"2022-07-09T21:23:23.000000Z","pivot":{"subfleet_id":"1","fare_id":"1","price":null,"cost":null,"capacity":"189"}},
```

**Comment by FatihKoz** [comment]
I checked the model and it looks ok. Also admin > fares work fine. 

Could not find the root cause why it's value is not being returned back with collections or relationships.

**Comment by FatihKoz** [comment]
Any news or clues for this @nabeelio ?

**Comment by nabeelio** [comment]
Hmm... I think it's probably `Services/FareService:172`
