### ISSUE TITLE
ChartFox Integration

### ISSUE THREAD

**Issue by ghost** [nabeelio/phpvms#1468]
During the flight planning stage, particularly after the OFP output from SimBrief, it would be a welcome feature to be able to offer to pilots the respective departure, arrival and alternate airport charts.

Now, since all charts are copyright protected, for the most part, this falls on the responsibility of the user, to either have them or know how to access them.

ChartFox is a free website providing a consolidated library of publicly available charts, thus, offering a possibility for phpVMS pilots to quickly access the necessary reference material.

I don't believe that ChartFox offers any specific integration capability. I would simply see it as an admin option (to turn on/off the integration) and then, on the flight planning page, offer an external link to the departure, arrival and alternate ICAO airports (since ChartFox uses a straightforward URL structure.

https://chartfox.org/KLAX (example)

**Comment by FatihKoz** [comment]
This can be done at theme stage, I see no core changes needed here. 

- You can have your charts uploaded to your server (if you wish to go that way and take copyright risks), then work for endless updates
- Or you can have the above link in your template (specially at SimBrief Briefing page or any page you want, with some javascript to check if the link is alive or not etc)

You have the airport code in all pages you may need to display that link, or any link related to an airport ICAO code.

Btw, just to mention that ChartFox link needs VATSIM membership, considering that phpvms v7 is not online platform specific or tied, this is another reason for not having it in the core and shipped to all users.

**Comment by FatihKoz** [comment]
My pleasure, as an example, in my theme (Disposable Theme v3) I have some modals (kind of pop-ups)... One in SimBrief Form (to open RouteFinder), another one in SimBrief Briefing (to open the OFP for editing).

That logic can be used for departure and arrival airport charts with ChartFox or any other source if you need to. As the theme is your own and not effected by core updates, it will be totally under VA Admin control ;)

Technically this is why I have "non-core" related stuff in my theme and modules.
