### ISSUE TITLE
Extra numbers on flights page

### ISSUE THREAD

**Issue by RRJustin** [nabeelio/phpvms#148]
![extra_numbers](https://user-images.githubusercontent.com/35641891/35188824-5ad81dc4-fe03-11e7-89ec-6ffa46b84cc0.png)

Just noticed extra numbers after distance and flight level.

**Comment by RRJustin** [comment]
Also, when manually changing the "required" field in the table on the database from 0 to 1, it shows HUB under the required box.
![pirep_fields](https://user-images.githubusercontent.com/35641891/35188878-acc8619c-fe04-11e7-84bc-545488421138.png)

**Comment by nabeelio** [comment]
For the extra numbers, can you do a show me what's in your settings table in mysql, specifically the distance unit and the altitude unit? And then show me the settings page in the admin what those values are?

**Comment by nabeelio** [comment]
Ah I see the problem. It's from when you hit save in the settings page.

**Comment by nabeelio** [comment]
This should be fixed now, just hit save again on the settings page.

**Comment by RRJustin** [comment]
![distance_flight](https://user-images.githubusercontent.com/35641891/35199671-c1a76c9e-fec6-11e7-8af4-1066719adbb5.png)

Flight level shows correctly on the flights page but there still an extra "1" at the end of the distance. Attached is what it shows in the database.

**Comment by nabeelio** [comment]
If you go to the settings page in the admin and then hit save, does that
fix it?

**Comment by RRJustin** [comment]
Negative. Still shows the extra number.

**Comment by RRJustin** [comment]
Issue resolved in build 180123-a3ed7f.
