### ISSUE TITLE
Error when sending /api/pireps/prefile

### ISSUE THREAD

**Issue by vangelisb** [nabeelio/phpvms#149]
![image](https://user-images.githubusercontent.com/4341073/35192186-c918c0f8-fe95-11e7-897f-b7fea4da0fc5.png)
When sending prefile request error ocures on website part 

also please confirm response is correct 

> {"user_id":1,"state":0,"status":0,"id":"Pdyo3QjgE6Va","updated_at":"2018-01-21 08:30:05","created_at":"2018-01-21 08:30:05","airline":null,"dpt_airport":null,"arr_airport":null,"position":null}

**Comment by nabeelio** [comment]
Do you have the request that was sent?

**Comment by vangelisb** [comment]
> [2018-01-21 17:22:06] dev.INFO: PIREP Prefile, user 1 {"_airline_id":"1","_aircraft_id":"1","_flight_id":"flightid_1","_dpt_airport_id":"KAUS","_arr_airport_id":"KJFK","_level":"25000","_planned_flight_time":"120","_route":"KAUS SID TNV J87 IAH J2 LCH J22 MEI J239 ATL J52 AJFEB J14 BYJAC Q60 JAXSN J14 COLIN J61 HUBBS J55 SIE STAR KJFK","user":"[object] (App\\Models\\User: {\"id\":1,\"name\":\"Admin User\",\"email\":\"admin@phpvms.net\",\"api_key\":\"testadminapikey\",\"airline_id\":1,\"rank_id\":1,\"country\":\"us\",\"home_airport_id\":\"KAUS\",\"curr_airport_id\":\"KJFK\",\"last_pirep_id\":\"pirepid_3\",\"flights\":3,\"flight_time\":0,\"balance\":null,\"timezone\":\"America/Chicago\",\"status\":0,\"state\":1,\"active\":null,\"last_ip\":\"62.1.92.13\",\"created_at\":\"2018-01-21 08:25:58\",\"updated_at\":\"2018-01-21 14:58:11\",\"deleted_at\":null})"} 
[2018-01-21 17:22:06] dev.INFO: PIREP PREFILED  
[2018-01-21 17:22:06] dev.INFO: 1aMwrOM9673d  

This is from the log in laravel 

also i saw that when the prefile happens a record is added in mysql pireps table where only an id exists

![image](https://user-images.githubusercontent.com/4341073/35196870-afa350e8-fee0-11e7-9095-084175641a69.png)

**Comment by nabeelio** [comment]
Do you have the request that you sent in? The fields with the underscore in front are interesting, looks like the null fields are also weird. I'm assuming the IDs and stuff you passed in were ok, right?

**Comment by nabeelio** [comment]
This error seems to indicate that the airline ID isn't correct. I'll add some more checks in the API code that makes sure those IDs are valid, but let me know if that seems like it's the case?
