### ISSUE TITLE
Soft delete user

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#1490]
**Is your feature request related to a problem? Please describe.**
To comply to the GDPR regulation about:
Right of withdrawal ('the right to be forgotten'): request its deletion when the data is no longer necessary.

We need to manage that data without delete user, to avoid possible problematic records about mandatory relationships, airline stats, etc.
I am not sure if this already works like this. In any case, it could be useful if a pilot wants to go back and recover all his progress after asking for his data to be deleted.

Currently when we change the user's state to "deleted" both their name and email remain in the system.

**Describe the solution you'd like**
By changing the state of the pilot to "deleted" the system could overwrite his name in the database to something like john doe, or take just the first letters, his initials, "JDD" (John Doe Doe) of his full name.
For email I don't know what would be the perfect solution. ¿And password?

**Describe alternatives you've considered**

**Additional context**
![imagen](https://user-images.githubusercontent.com/16170732/197788340-7d3ec21d-4c1e-4578-a0ff-c5700b36b950.png)

**Comment by nabeelio** [comment]
This should be a quick change, since we do this already if the user has PIREPs

https://github.com/nabeelio/phpvms/blob/dev/app/Services/UserService.php#L153-L161

**Comment by FatihKoz** [comment]
Don't we have it already?

Just click the delete button, if the user has a pirep in the system this happens (name/mail/password change), if not it gets deleted.

I do not think that we need to click edit, select deleted and then click save to do the same thing.

**Comment by nabeelio** [comment]
Yeah, it could be to soft-delete always, but it's essentially already done

**Comment by FatihKoz** [comment]
"_Soft delete always_" ? I do not think that is needed, even with GDPR. 

Technically for GDPR compatibility a user can request data removal and our current system covers regulation requirements pretty well;

1. User has "non personal data" (pireps, acars records, finance records etc) in the system : 
   *Remove personal data (change name, mail, password, ivao/vatsim id etc) , make non personal data non-identifiable / trackable*
2. User has NO "non personal data" in the system : 
    *Delete the user directly*

For scenario 2 we do not need to "soft delete", we just need to delete the record that's it.

In short, **just click the delete button from admin area** v7 will take care the rest.
(_or if needed we can allow the users to delete themselves from user profile directly_)

So again, I really and honestly do not understand the feature request or the logic behind it. @arv187 is technically requesting the same thing we already have but wants it to have with more clicks ? Either he is unaware of the current system or wanting something different like;

`... In any case, it could be useful if a pilot wants to go back and recover all his progress after asking for his data to be deleted.`

Second part of this request is not possible and should not be possible. 

Once you request a GDPR removal **there is no way of going back** . It is a removal decision and it is a serious act, not something you change two days later. So if the person wants to join back he/she needs to start from the beginning like every other **new member**.

**Comment by arv187** [comment]
So it's implemented, great.
Mainly, the issue came from not understanding the difference between the option "state = deleted" and using the delete user "X" button.

I thought that deleting user completely deletes everything, pireps, stats and could have unwanted behaviour that could cause system errors.

About going back, it is possible, you delete those personal data. If he comes back, for the initials or the pilot ID, you could edit by hand the email address that the person gives you, so that he could ask the system for a new password "because he forgot it".

But you are right, if he leaves and asks to delete his data (name and email), he should think twice before leaving and losing his achievements and stats.

So what is the function of changing the "state" to "deleted" when editing a user?

You can close this issue.

**Comment by FatihKoz** [comment]
For me "Manual Recovery" is not an option @arv187 :) Two reasons;

1. I will never work (spend my time) for someone who can not stand after their decision and want to come back after requesting data removal.

2. Because of the above, I already wrote my own cron powered code which removes every single record of a pilot (or created by that pilot) once it gets gets deleted. I do not care the numbers they left behind, I am not after some shiny stats ;)

I would advise the same for every other admin, time is important and we should be enjoying our hobby, not spending it for babysitting :)

Safe flights
