### ISSUE TITLE
Changing a flight status does not save

### ISSUE THREAD

**Issue by RRJustin** [nabeelio/phpvms#150]
When creating a new flight for the airline even if it is not checked as active it still saves as active. Also, when editing the flight, unchecking active does not save and the flight still shows as active.

**Comment by nabeelio** [comment]
These active/inactive are driving me nuts lol

**Comment by RRJustin** [comment]
This issue turned into when unchecking Active and hitting save gives an error.

> Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause' (SQL: select * from `flights` where `0` = id != dL98wvKw6Wwe and `flight_number` = 910)

**Comment by nabeelio** [comment]
Is this fixed now?
