### ISSUE TITLE
New registrations are auto-accepted and put as active

### ISSUE THREAD

**Issue by RRJustin** [nabeelio/phpvms#151]
May not be a bug but that's how it is set up now and in the settings I did not see an option for pilots to need to be verified or manually accepted into the airline. 

Just a heads-up.

**Comment by nabeelio** [comment]
The option does exist: 

<img width="1229" alt="screen shot 2018-01-21 at 11 44 34 pm" src="https://user-images.githubusercontent.com/99736/35206858-1c229f7a-ff05-11e7-8bd2-bbc798b9670f.png">
