### ISSUE TITLE
Pilot Settings

### ISSUE THREAD

**Issue by sgraypgh** [nabeelio/phpvms#1514]
Add under the Pilot section:

- Restrict Aircraft to Ranks
  --Aircraft restricted to user's rank

- Restrict Aircraft by Type Ratings
  --Aircraft restricted to user type ratings

- Restrict Aircraft At Departure
  --Only allow aircraft that are at the departure airport

These would allow greater control over the pilot's selection of aircraft and flights.

**Comment by dougjuk** [comment]
they are already there under settings

**Comment by sgraypgh** [comment]
No, those are under the Pirep section.

**Comment by dougjuk** [comment]
Yes but they apply to the pilots unless you want to apply it to certain pilots ???

**Comment by sgraypgh** [comment]
According to Dispo they do not apply to the pilots and he suggested I make
the suggestion to add them to the Pilot section.

**Comment by sgraypgh** [comment]
Here is the Forum post about it.

https://forum.phpvms.net/topic/29023-type-ratings/?do=findComment&comment=150610

**Comment by dougjuk** [comment]
Ah ok, I do not use them so did not fully understand..

**Comment by sgraypgh** [comment]
Yea, I didn’t either until Dispo explained it. I was pulling my hair out to get things working. I finally just turned off the Type Rating stuff. From: DougSent: Friday, January 20, 2023 06:57To: nabeelio/phpvmsCc: sgraypgh; AuthorSubject: Re: [nabeelio/phpvms] Pilot Settings (Issue #1514) Ah ok, I do not use them so did not fully understand..—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> Virus-free.www.avast.com

**Comment by FatihKoz** [comment]
Simply you want to have those rank and type rating filters applied to schedule/flight list page :)

I will provide a solution for this, which will consider those rank and type rating checks but be advised, it will NOT work as you initially thought (forum post).

If there are no subfleet assignments for a flight (which simply means: that flight is open to all subfleets), they will be hidden too. Combine this to rank and type rating assignments to both pilots and subfleets, this will easily be a mess (specially during setup for those who are new to v7)

Enjoy ;)

**Comment by sgraypgh** [comment]
My initial thoughts (maybe not very clearly stated previously) were that pilots with a certain rank that had specific subfleets not included wouldn't be able to see or select those aircraft. As part of that is the type rating piece, so rank included the subfleet but the pilot didn't have the required a type rating, then those would also not be seen or be selected.

You certainly understand the logic of what is in place and if this idea makes any sense, so I don't want you to spend a lot of time on it if not of value to others as well. I am certain that you have plenty of issues you are likely looking at addressing.

**Comment by FatihKoz** [comment]
Looks like you are still mixing up things, aircraft filtering works as long
as you enable their settings... Nobody can use something not allowed, this
is a solid feature of v7.

What you were talking about at forum was limiting flights according to
aircraft rank/type rating restrictions. (At least this is what I understood
from your post and replied with some details)

And think you still want it 'cause otherwise there will be no need to open
this issue/feature request :)

Either way, it is now a decision for the developer to accept/reject (or
maybe improve) my humble solution.

Safe flights

Sent from mobile device / Mobil cihaz ile gönderildi

23 Oca 2023 Pzt 23:44 tarihinde sgraypgh ***@***.***> şunu
yazdı:
