### ISSUE TITLE
News is being sent to "pending" members.

### ISSUE THREAD

**Issue by DeshMindER** [nabeelio/phpvms#1518]
**Describe the bug**
If a member's approval is still pending (new member) he received the e-mails messages. I believe that only active members should receive news. (Or previously approved members).

**Version**
7.0.0-dev+221103.00918f

**To Reproduce**
1. Create a new member
2. Leave it pending
3. Send news to all pilots
4. See e-mail received in pending member's mailbox

**Expected behavior**
Pending members should not receive news.

**Comment by FatihKoz** [comment]
I think they should be sent only to ACTIVE and ON LEAVE pilots, nothing more... 

Right now, news are being sent to all members (whom wanted to be informed of course) except DELETED ones :)
