### ISSUE TITLE
Select multiple aircraft when configuring ranks

### ISSUE THREAD

**Issue by Strider2** [nabeelio/phpvms#1534]
It would be nice to be able to select multiple aircraft subfleets when configuring the ranks, as selecting one by one is tedious.

A simple change to the current drop down to allow multiple selections would work perfect, and make configuring them much faster.

No other alternatives can really replace this.

**Comment by FatihKoz** [comment]
Maybe a multi select capable dropdown (select2) can solve this... 

(Api routes may need to be updated to handle an array instead of a single id)
