### ISSUE TITLE
The database tester in installer uses the wrong IP address.

### ISSUE THREAD

**Issue by ajh123** [nabeelio/phpvms#1548]
**Describe the bug**
A clear and concise description of what the bug is. Please upload the Laravel logs as well from `storage/logs/laravel.log` (or the file with the correct date)

I am trying to install phpvms but can't get pass the database stage in the installer. I have entered the correct information but when the database connection is tested it tries to connect to a database on the wrong IP.

The logfile is simply.
```
[2023-06-08 18:32:24] dev.INFO: Testing Connection: mysql::phpvms:<hidden>@10.0.0.174:3306;phpvms  
[2023-06-08 18:32:24] dev.INFO: Connection string: mysql:host=10.0.0.174;port=3306;dbname=phpvms  
```

**Version**
The version at the commit (as it appears in `git log`) `3828b89fdb1b5c70c855d79d54373331283ae58b` (the latest 'dev branch' as of now which the `git clone` defaulted to).

**To Reproduce**
1. Complete the php module testing of the installer
2. Go to the database setup page.
3. Enter the correct database information. For me it's the `IP(host): 10.0.0.174, User: phpvms, Databsae: phpvms`
4. Click the test connection button.
5. See error

**Expected behavior**
The database test uses the IP entered in step 3 and the test passes successfully. 

**Actual behavior**
The database test uses the IP `127.0.0.1` (which is the webserver) instead of the one in step 3 and the test fails successfully. 

**Screenshots**
Step 3:
![phpvms1](https://github.com/nabeelio/phpvms/assets/41990982/c8576a03-c913-4a42-8da8-d002a29fbe57)

Step 5

![phpvms2](https://github.com/nabeelio/phpvms/assets/41990982/e53f363f-a657-46f7-ba39-453a94a28885)

**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)
There's only the first log.
Also `10.0.0.160`(which is the same as `127.0.0.1`) has a database but I do not want to use that one. Instead I need to `10.0.0.174` which other software can connect to perfectly even when using the same username/password.

Using the browser's dev tools it appears that the browser is sending the right data.

![phpvms3](https://github.com/nabeelio/phpvms/assets/41990982/a51d3619-f466-4116-b040-5b85f1b2753b)

**My diagnosis**
I think the installer is remembering the `127.0.0.1` that it prefilled in initially instead of using the one I gave (`10.0.0.174`). Since `127.0..0.1` and `10.0.0.160` are the same machine it ends up trying to connect the to wrong database.

**Comment by nabeelio** [comment]
That error message shows that it's connecting. You need to grant privileges to that user to connect from that host. That is the IP it's connecting from, so that's probably correct. See [this post](https://stackoverflow.com/a/8348560)

**Comment by ajh123** [comment]
Thanks for letting me know, I will have to test tomorrow.

**Comment by ajh123** [comment]
I have fixed the problem now but using a different way. I had the create the user like `'phpvms'@'%'` instead of `'phpvms'@'localhost'` and then grant permissions to database.
