### ISSUE TITLE
Awards

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#155]
### Base features

- [x] New module/addon class? 
- [x] Base class constructor sets award id, etc
  - `check()` uses those internal IDs
- [x] Add new subscribe listener - `AwardEventListener`
  - Run dynamically when `UserStatsChanged` event is called.
  - Pass the user in, after last pirep, etc is set
  - Runs all award add-on classes
- [x] Award classes are assigned to record - so images, etc can be set in the admin
  - Admin uses the `$name` var to show list in panel
  - Allow a parameter to be set in the award row
- [x] Installer method - creates a new award that acts as the default for the class
  - For a module, just use the migrations to create a new award
  - Needs documentation!

**Comment by youngbuckscrew** [comment]
`Trait 'App\Repositories\Traits\CacheableRepository' not found`

am sure you meant to use `Prettus\Repository\Traits\CacheableRepository` instead

Error is found on`App\Repositories\AwardRepository.php Line 6`

**Comment by nabeelio** [comment]
@youngbuckscrew Thanks, fixed in this commit. I haven't added tests for this stuff yet, or changed the admin UI yet to allow selecting the custom award class stuff, just fleshing out how the awards class will work. I'm guessing you're messing with it

**Comment by youngbuckscrew** [comment]
Yes i'm looking over and testing. I found another errors
 
on `App\Http\Requests\UpdateAwardRequest.php` on the rules functions it's returning 
`return Fare::$rules` instead of `return Award::$rules` which is causing an issue on update.

**Comment by nabeelio** [comment]
Yep, just saw that one. I'm working on it as well as getting the award class selector working.

**Comment by nabeelio** [comment]
@youngbuckscrew Alright, give it a shot now. The award class selection and parameter description stuff should work now. You should also be able to create your own award class, and place it in a new module or right in the `app/Awards` directory. It should also run when UserStatsChange is called.

I haven't added any tests yet so stuff might be broken. I'll work on adding those today, since I don't like having stuff left around without tests :)

**Comment by youngbuckscrew** [comment]
Okay ill test now, ill report when finished

**Comment by nabeelio** [comment]
Found a few issues on the actual running of the class. I'm working on it, though I need to step out for a bit, so I'll have it fixed

**Comment by nabeelio** [comment]
Added tests and fixed a few things, seems to work properly now

**Comment by youngbuckscrew** [comment]
Yes its working correctly. Can we come up with a way to automate the conditional awards?  such as the 100 flights one? I got a few ideas.

**Comment by nabeelio** [comment]
What do you mean by automate? Because every VA is different. So for the
award, you can pass a custom parameter and have multiple awards using the
same class, just passing in different parameters.

I have an idea for automatically creating the award with the class on first
run, so if you download one, it can install itself with some default
parameter

What're the ideas you have?

**Comment by youngbuckscrew** [comment]
Ahh i get what you mean now, lol sorry! i guess the next feature is make the award image an upload method with maybe intervention.

**Comment by nabeelio** [comment]
Intervention?

**Comment by youngbuckscrew** [comment]
[https://github.com/Intervention/image](url)

**Comment by nabeelio** [comment]
Thanks, I'll check it out
