### ISSUE TITLE
Update erases admin user and replaces the main airlines name

### ISSUE THREAD

**Issue by Strider2** [nabeelio/phpvms#1561]
When updating, it will replace the Owners name and will replace the name of the main airline, also will add one or two fictional accounts.

Happened in all versions I have used so far up to and including the most recent

Create a VA with an older version then update it.

Update without changing names.

**Comment by FatihKoz** [comment]
Are you trying to use v7 on development/local settings, check your env.php and be sure using production.

What you describe is the behavior of local/development install (and updates, which runs the seeders for testing)

**Comment by nabeelio** [comment]
What are they replaced with? Like @FatihKoz said, you might be in 'dev' mode

**Comment by FatihKoz** [comment]
I think this should be closed as the OP is not responding 
(and only way to re-create the behavior is using 'dev' mode, which then will make this the expected result)
