### ISSUE TITLE
After a pirep is filed, pilot location is updated prior to pirep approval

### ISSUE THREAD

**Issue by AV8ROwen** [nabeelio/phpvms#1567]
**Is your feature request related to a problem? Please describe.**

Yes. After a pilot completes a flight, their location is not updated until after the pirep has been accepted. 

**Describe the solution you'd like**

Basically, when a pilot submits a pirep, their location in the pirep is their new location within the VA.

**Describe alternatives you've considered**

Only alternative solution I have found is to allow pireps to be auto accepted so their location will be updated unless the pirep is auto rejected.

**Additional context**

**Comment by BossOfGames** [comment]
A potential problem with this request is where if you have the pilots must fly from the last location, their location will be in limbo until someone goes in and manually approves the flight.

What you desire could be done, but, if combined with other features, it could cause severe user experience problems.

**Comment by FatihKoz** [comment]
I tried to explain the logic and risks behind this via discord, but looks like OP missed that conversation or still wants it to be done. **Honestly considering the complexity of other systems and relationships, what v7 offers currently is ok.**

Currently it offers relaxed setup options (no location checks, no aircraft checks) and offers controlled setup options (location and/or aircraft checks, availabilities etc.). Mixing two and/or removing some parts of one will only bring in new problems.

There was a request before, in which pirep checks was kept intact but flight search page settings was separate and can be adjusted to show all/more flights (regardless of pilot location). Maybe implementing that with some improvements will be useful, imagine a scenario/solution where pilots will be able to see current location departures and possible departures from where they recently landed while waiting for their pirep to accepted.

Anyway, our conversion about this is below, if someone wants to read it is available at discord too ;)

![image](https://github.com/nabeelio/phpvms/assets/74361521/3a97f29f-583d-4a65-9fb2-38c571cf1a19)

**Comment by nabeelio** [comment]
I'll close this for now. It can actually be accomplished through a module, if you look for the PIREPFiled event, you can look up the user and update their location
