### ISSUE TITLE
Admin Role Issues

### ISSUE THREAD

**Issue by AV8ROwen** [nabeelio/phpvms#1570]
**Describe the bug**
A clear and concise description of what the bug is. Please upload the Laravel logs as well from `storage/logs/laravel.log` (or the file with the correct date)

"Admin" role in PHPVMS is not discoverable on the role page. However, non Admins can assign the "Admin" role to themselves. Giving them all permissions.

**Version**
Please enter the version

7.0.0-dev+230630.d76389

**To Reproduce**
1. Go to Roles
2. See error, Admin does not show up.

**Expected behavior**

I expect non admins to not be able to make themselves an admin.

**Comment by FatihKoz** [comment]
There is no "Admin" role under roles, never been.

Did you followed latest issues and latest pull requests ?

**Comment by FatihKoz** [comment]
![image](https://github.com/nabeelio/phpvms/assets/74361521/06b9f71d-2455-48cd-9e49-0f1009e7fac4)
