### ISSUE TITLE
Admin search still not right

### ISSUE THREAD

**Issue by dougjuk** [nabeelio/phpvms#1585]
The drop down search for hub and location in new aircraft page are not functioning

**Version**
Latest dev 30fa5c

**To Reproduce**
1. Fleet select a subfleet
2. Click on add new aircraft
3. look in top right 
4. the hub and location field do not function.

**Expected behavior**
To be able to select a hub and location

**Screenshots**

<img width="1262" alt="Screenshot 2023-08-17 at 09 36 45" src="https://github.com/nabeelio/phpvms/assets/75090523/203351c6-f517-4a37-b977-8aed2957bd24">

**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)

**Comment by dougjuk** [comment]
I also notice that the airport drop down is not working in the register page.

**Comment by ArthurHetem** [comment]
Fixed by #1588
