### ISSUE TITLE
404 Page Loads Default Template on /api

### ISSUE THREAD

**Issue by BossOfGames** [nabeelio/phpvms#1586]
**Describe the bug**
When using a custom skin, which is not the default, when a 404 error is encountered, it loads the default

**Version**
7.0.0-dev from GitHub. Don't know the exact commit, but it was from last week.

**To Reproduce**
1. Navigate to /api

**Expected behavior**
The skin selected in phpVMS to load properly.

**Screenshots**
<img width="1033" alt="Screenshot 2023-08-17 at 18 52 20" src="https://github.com/nabeelio/phpvms/assets/2882332/1ecbe2d4-870b-4758-97ab-6a51e53fab0c">
<img width="1043" alt="Screenshot 2023-08-17 at 18 52 42" src="https://github.com/nabeelio/phpvms/assets/2882332/685ad526-6175-4e03-8630-4b712f570a55">

**Additional context**
None

**Comment by nabeelio** [comment]
Other 404 pages are working correctly, right?
