### ISSUE TITLE
Disabling > Enabling modules generate exception (Bug Report)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1591]
Even though the module gets enabled technically an exception is generated when enabling modules.

**Version**
7.0.0-dev+230818.7f346a

**To Reproduce**

1. Go to admin > addons / modules page
2. Select a module and click `Edit Module`
3. Uncheck Enabled checkbox and click `Save` (Disable the module)
4. Now go back to the same page by clicking `Edit Module` again
5. Check enabled checkbox and click `Save` (Enable the module)
6. Click Save to see the error (or check your logs)

_Just go back to admin dashboard and then visit addons / modules, it will be enabled and working_

**Expected behavior**
It should not generate the exception about migrations (which are already applied during module install and update phases)

**Screenshots**
![image](https://github.com/nabeelio/phpvms/assets/74361521/4845d18f-6adb-48c0-97dc-af5434762ad1)

**Comment by nabeelio** [comment]
I can't replicate this, is it happening for you with the acars module?

**Comment by FatihKoz** [comment]
Yes, happens with vmsAcars module too.

![image](https://github.com/nabeelio/phpvms/assets/74361521/5a038ff7-dfaf-41b9-9340-9e5430966ef9)

```
[2023-08-23 18:54:37] production.ERROR: The command "module:migrate VMSAcars" does not exist. {"userId":1,"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): The command \"module:migrate VMSAcars\" does not exist. at /home/turksim.org/flightops/vendor/laravel/framework/src/Illuminate/Console/Application.php:159)
[stacktrace]
```

**Comment by nabeelio** [comment]
Weird, this isn't happening for me

**Comment by FatihKoz** [comment]
Happens to me and lots of users always, this is why I added a note for this
in my readme files and advising people via discord when they face this
during disable/enables.

Sent from mobile device / Mobil cihaz ile gönderildi

29 Ağu 2023 Sal 20:53 tarihinde Nabeel S. ***@***.***> şunu
yazdı:

**Comment by FatihKoz** [comment]
@nabeelio re-producable at demo.phpvms.net too... 

![image](https://github.com/nabeelio/phpvms/assets/74361521/44157294-7dd8-4abc-883e-06d3703e5ced)

Installed my own module to your demo site (by add modules > select release zip file > proceed), it directly generated the error...

Then disabled it from addons, cleaned application cache etc and then re-enabled from same page (by visiting it again)

![image](https://github.com/nabeelio/phpvms/assets/74361521/7281f580-0472-4b4a-9c02-07660f408dcd)

So why it is not happening on your local development environment but effecting live sites (including the very basic demo) I have no idea, but this error is still live.

**Comment by nabeelio** [comment]
This could be a cache thing
