### ISSUE TITLE
Aircraft Type is Already assigned Bug, when it is not in the subfleet.

### ISSUE THREAD

**Issue by CaptainGodual** [nabeelio/phpvms#1614]
**Describe the bug**
A clear and concise description of what the bug is. Please upload the Laravel logs as well from `storage/logs/laravel.log` (or the file with the correct date)
When adding a Subfleet with a Type A320, PHPVMS7 Reports that the type is already in use even though it is not listed in the list of subfleets. 
**Version**
Please enter the version
7.0.0-dev+230907.7c98bf
**To Reproduce**
1. Goto Fleet
2. Click on Add New Subfleet
3. Enter the information for the Airbus A320-200 Type is A320
4. When submitted it should say the Type is already assigned when it's not

**Expected behavior**
Expected the Subfleet type to be added to the database and become available to setup aircraft in. 

**Screenshots**
![image1](https://github.com/nabeelio/phpvms/assets/31859651/650d9cf1-3871-4157-9210-9e5dca248097)
![image2](https://github.com/nabeelio/phpvms/assets/31859651/c551f13b-75bf-458d-ab49-9d08cd29eaba)
**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)

**Comment by FatihKoz** [comment]
This is happening because of `SoftDeletes` @nabeelio ... Probably a subfleet with code A320 was created and then deleted, it is still in the database but with deleted_at field populated (so not being used directly), when OP tries to create another one with the same code, it fails because of `unique` check for that field.

I think we need to implement a `trash` view with the ability to permanently delete / restore records for main models.

**Comment by CaptainGodual** [comment]
@FatihKoz I think this is a good idea, but I would suggest maybe implementing a check to make sure deleted aircraft and what not are not linked to a pirep and if so prevent it from being deleted permanently in the Recycle Bin.

**Comment by FatihKoz** [comment]
What you report here is deleting a subfleet and it has some checks, you can not delete a subfleet when it has aircraft assigned to it.

What you are offering about aircraft deleting is something different, please do not mix aircraft and subfleet logic.

Technically speaking deleting an aircraft will not cause much trouble, it still has its risks but you are being asked 2 times when you click that delete button and one should be able to really delete something. So if that fellow va owner wants not to delete an aircraft, then he/she can avoid doing this :)

Anyway, this needs to be in a new issue, your subfleet issue can be closed after the solution gets implemented :)

**Comment by nabeelio** [comment]
I'm pushing a fix for this, it will check that the type doesn't exist among the deleted items

**Comment by FatihKoz** [comment]
So we will not have a trash display and restore ability, only a check for
deleted duplicate records ?

Sent from mobile device / Mobil cihaz ile gönderildi

9 Eki 2023 Pzt 22:56 tarihinde Nabeel S. ***@***.***> şunu
yazdı:
