### ISSUE TITLE
Airports table - add elevation and region

### ISSUE THREAD

**Issue by ProAviaAZ** [nabeelio/phpvms#1616]
**Is your feature request related to a problem? Please describe.**
Airport lookup returns airport elevation and region. Airports table is missing these two items. 

**Describe the solution you'd like**
Add airport elevation and region to airports table, back end (admin, airports) and front end. 

**Describe alternatives you've considered**
None

**Additional context**
API data returned for KAUS

{"icao":"KAUS",
"iata":"AUS",
“name":"Austin Bergstrom International Airport",
"city":"Austin",
"country":"US",
"region":"Texas",
"tz":"America/Chicago",
"elevation":542,
“lat":30.1945,
"lon":-97.6699}

**Comment by FatihKoz** [comment]
Something like this ?

![image](https://github.com/nabeelio/phpvms/assets/74361521/d46112f4-14a9-4406-8ba1-6b363e84c3fb)

![image](https://github.com/nabeelio/phpvms/assets/74361521/1c7e1a6c-7513-46e1-b9f2-bc6fe0a0a635)

with some sorting improvements maybe...

**Comment by ProAviaAZ** [comment]
Yes - something like that.
Maybe more condensed. Don't really need a big space for ICAO, IATA, Latitude, Longitude, Elevation or Country.
I have no idea how the formatting is set up for that page though, so no clue how easy changing that would be.

The second image looks good. 
GH and fuel may not need to be displayed. Maybe Lat/Lon can be easily put there.

My intent was to have elevation and region in the table. However it is displayed in the admin side is fine with me.

And maybe the info can be added to the airports display the pilots/users have access to.
I think Lat/Lon and elevation could be important for them to see.

**Comment by FatihKoz** [comment]
Theming is just theming, v7 uses blade so it is not that hard to edit but I am more than focused on the feature not the visual style.

As the images are from admin side, I think having the costs and fuel there visible (fuel is editable directly from that view too)

For user/frontend we can display those data too, I can add them to default theme too (same theming logic applies)

**Comment by FatihKoz** [comment]
![image](https://github.com/nabeelio/phpvms/assets/74361521/3e587b62-f245-4803-b8b8-bb59bf9cb3b1)

**Comment by ProAviaAZ** [comment]
Agreed - having the data available is what  is most important.
I was only thinking of a way to condense the real estate that area takes.

Whatever you think is most important to display on the other admin page is fine with me.

Adding the data to the front end is important as well.

**Comment by nabeelio** [comment]
I'm adding this on the API side in the database atm
![image](https://github.com/nabeelio/phpvms/assets/99736/be7aa612-17f9-4de9-a42c-fdf626f36e22)

**Comment by nabeelio** [comment]
Sorry, it's already in the API, but I'm migrating it to something more easily updatable by me. So it just needs the frontend stuff.
