### ISSUE TITLE
Weather data import not working

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1639]
Weather widget is not getting latest wx reports (metar/taf) also built in maps with wx data not displaying weather symbols and page loads are affected.

**Version**
Not version specific

**To Reproduce**
Check your weather widget or built in airspace maps

**Expected behavior**
It should work like before :)

**Comment by wbox** [comment]
Apparently the [URL](https://github.com/nabeelio/phpvms/blob/dev/app/Services/Metar/AviationWeather.php#L17-L21) in use is not available anymore according their [website](https://aviationweather.gov/help/#url). 

I see the request set xml as the format so this service might need to be refactored if XLM is not an option from AWC website.

**Comment by FatihKoz** [comment]
PR already sent and fix in place, everything works as like before.
