### ISSUE TITLE
Flight Import | firstOrNew Fails

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1661]
During flight import, `**firstOrNew**` fails to match existing flights and always creates a new model instance, which results in duplicate flights if same file is imported again.

**Version**
7.0.0-dev+231027.67ef30

**To Reproduce**
1. Go to admin > flights > import from csv
2. Import a file with some new flights
3. Go back to admin > flights > import from csv again
4. Import the same file
5. Check your flights, you will see the duplicated flights

**Expected behavior**
We should update matching records, not re-create new flights on every import

**Screenshots**
![duplicate flights](https://user-images.githubusercontent.com/74361521/278861228-c4323853-9273-4b76-838a-b45ab33bdff6.png)

[test.csv](https://github.com/nabeelio/phpvms/files/13198582/test.csv)

**Comment by EpicHax7** [comment]
Having this issue too 
hope its fixed soon 
Thank you
