### ISSUE TITLE
Users | Change ID

### ISSUE THREAD

**Issue by fequesada** [nabeelio/phpvms#1664]
**Describe the solution you'd like**
In version 5, there was an option for 'change ID,' but today, if we change the ID in the database, it clears all the information.

**Describe alternatives you've considered**
None

**Comment by FatihKoz** [comment]
You should **NOT** change the ID of a user, never... Technically it is still possible but you need to change tons of other stuff and this will definitely harm your v7 if you simply forgot one step (pireps, transactions, journals, field values etc. etc.)

You can however, define IDENTS for your pilots, change them as you wish. 

- ID is internal use only > For example 48 is my internal id)
- IDENT is public > THY978 is my ident, in which THY is the icao code of the airline (you can fix this), 978 is my ident

Hope this helps.

And please, do not expect v7 to be same as v5 :) You will encounter more changes and differences within v7.

**Comment by fequesada** [comment]
I made a mistake, it was indeed the IDENT, not the Table ID. It's already resolved here.
