### ISSUE TITLE
Legacy Importer - v5 transfer hours are not being imported to v7 transfer hours

### ISSUE THREAD

**Issue by ProAviaAZ** [nabeelio/phpvms#1667]
**Describe the bug**
v5 pilot transfer hours are not being imported to v7 users, transfer_time

**Version**
Latest v7 dev and v5.5.2.72

**To Reproduce**

**Expected behavior**
Transfer hours from v5 should be converted to minutes (v7 format) and imported to v7.

**Screenshots**
Same pilot/user - total hours computation is close, but transfer_time is missing in v7.

v5 - phpvms_pilots table
![image](https://github.com/nabeelio/phpvms/assets/24687699/a569f65f-b924-46c5-95b8-ac8233a10def)

v7- users table
![image](https://github.com/nabeelio/phpvms/assets/24687699/14ec7b5e-821c-4ae8-87de-6c2ecfa72e5e)

**Additional context**
I think the following will allow transfer hours to be imported in v7
But since I am not 100% sure, I didn't send a PR.
In /app/Services/LegacyImporter/UserImport.php - after line 71, add
 'transfer_time'       => Time::hoursToMinutes($row->transferhours),

**Comment by FatihKoz** [comment]
Maybe a little bit more safer like

```php
'transfer_time' => filled($row->transferhours) ? Time::hoursToMinutes($row->transferhours) : null,
```
