### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry Error when importing CSV of Aircraft

### ISSUE THREAD

**Issue by CaptainGodual** [nabeelio/phpvms#1668]
**Describe the bug**
When Importing Aircraft Specifically CRJ9 for new aircraft import, deleting the existing aircraft as we are redoing our fleet as we have yet to do any PIREPS or our first flight as we setup operations with the VA. I get an error about Integrity constraint violation: 1062 Duplicate entry being in the aircraft database. This Aircraft to my knowledge has not been in our PHPVMS7 VA's fleet yet.

**Version**
7.0.0-dev+231022.d69a3b

**To Reproduce**
1. Log into the PHPVMS7 with admin log in
2. Click on admin to get to the admin dashboard
3. to specifically get to the entire list of Aircraft since we were removing them and redoing our fleet we went to <url of the PHPVMS7 admin dashboard>/admin/aircraft
4. Click Import From CSV
5. Select the Aircraft CSV File Being Imported, Check Delete Existing Data and Click Submit. 

**Expected behavior**
Existing aircraft deleted from database and new imported,

**Screenshots**
![image](https://github.com/nabeelio/phpvms/assets/31859651/0c823384-2a10-4bde-ab51-17b1dd4a0c3b)
**Additional context**
none

**Comment by FatihKoz** [comment]
Update to latest dev, this issue was identified (#1650) and fixed at 30th October.

**Comment by CaptainGodual** [comment]
Wil Do Thanks @FatihKoz Closing this issue
