### ISSUE TITLE
500 Error when Restoring or Deleting from Trashbin of Aircraft

### ISSUE THREAD

**Issue by CaptainGodual** [nabeelio/phpvms#1669]
**Describe the bug**
When restoring or deleting from the trashbin aircraft, a 500 error is thrown nothing is restored or deleted.  

**Version**
7.0.0-dev+231022.d69a3b
**To Reproduce**
1. Goto Admin Dashboard
2. Click on Fleet Click on a subfleet to get into the aircraft list
3. Click on restore or delete of aircraft in Trashed Aircraft Records.
4. See 500 Error

**Expected behavior**
The Aircraft to be restored or permanently deleted depending on what is being clicked Restore or Delete.

**Screenshots**
![image](https://github.com/nabeelio/phpvms/assets/31859651/2b86e944-2f34-43cc-a1cb-62fef6211f2d)

**Additional context**
POST https://skywardair.xyz/admin/aircraft/trashbin 500 (Internal Server Error) - Uncertain if this is a issue with my server or is code problematic.

**Comment by FatihKoz** [comment]
Update to latest dev, test again and please provide laravel logs as described in official documents

https://docs.phpvms.net/help#information-required

https://docs.phpvms.net/help#logs

**Comment by CaptainGodual** [comment]
So far, I see nothing of error in the Larvel Logs, but I will post them here for further review. Have my Server Admin pulling my PHP error logs to see if it might be something on the server. 
[laravel-2023-11-08.log](https://github.com/nabeelio/phpvms/files/13301367/laravel-2023-11-08.log)

**Comment by KemalOues** [comment]
Can confirm this, only solution is to delete the ac from the database

**Comment by FatihKoz** [comment]
Will check this and try to find why it is failing.

But first need some rest, took some pills recently.

Sent from mobile device / Mobil cihaz ile gönderildi

10 Kas 2023 Cum 17:07 tarihinde KemalOues ***@***.***> şunu
yazdı:

**Comment by FatihKoz** [comment]
![image](https://github.com/nabeelio/phpvms/assets/74361521/b5513c49-df7d-461e-88e4-b368b52de4ee)

![image](https://github.com/nabeelio/phpvms/assets/74361521/110137f0-366b-451f-b380-8f81df4698d1)

Looks like it was my logical error while implementing the safety feature :) Will fix it soon

**Comment by CaptainGodual** [comment]
Thank you @FatihKoz and @nabeelio for all your hard work to make this the best Crew center with fixing issues and improvements!
