### ISSUE TITLE
Error Page Occurs When Accessing PIREP via User Dropdown menu to access reports in PHPVMS7

### ISSUE THREAD

**Issue by CaptainGodual** [nabeelio/phpvms#1679]
**Describe the bug**
When attempting to access detailed flight information by clicking on my username in phpVMS7, followed by selecting 'Reports' and clicking on a specific flight number, I encounter a 'Something Went Terribly Wrong' error page. This issue disrupts the intended flow and prevents me from accessing the desired flight details.  Unsure if this is specific to an issue with the server the phpvms7 is hosted on or is an actual bug with phpvms7. This error happens when trying to access the PIREP in both the Pilot side and the Administrator Side for PIREPS

**Version**
Please enter the version
7.0.0-dev+231113.84f6cb
**Steps to Reproduce**
1.Navigate to the user profile by clicking on the user name to open the dropdown.
2.Select "Reports" from the dropdown menu.
3.Click on the desired Flight Number to access the corresponding PIREP.

**Expected Behavior**
The system should smoothly transition to the PIREP page, displaying relevant information without errors.

**Actual Behavior**
Upon clicking on the Flight Number, a "Something terribly went wrong" error page is encountered.

**Screenshots**
I know the error page says sharing the screen error won't help but since it's the screenshot I have I am attaching it. 
![image](https://github.com/nabeelio/phpvms/assets/31859651/83008180-c46f-4ec5-a00e-ada414384a85)

**Additional context**
Lavel Logs are attached below for the issue.
[laravel-2023-11-16.log](https://github.com/nabeelio/phpvms/files/13384742/laravel-2023-11-16.log)

**Comment by CaptainGodual** [comment]
**Additional context**
When using the default theme, originally, we were using the disposable basic theme. The PIREP is viewable, same when we used a custom theme, we had made for our VA we get the same 500 error, so I am not sure if this is theme related or an issue with PHPVMS7.

**Comment by CaptainGodual** [comment]
Updated to recent version of Disposable Basic Theme, and tested viewing of PIREP again. This is not a PHPVMS7 issue it is a known issue of my VA using a out of date Disposable Basic theme, this is my fault sorry >.<.  So again this is not a PHPVMS7 issue and I am closing my issue.

**Comment by ProAviaAZ** [comment]
If it works in the default theme and not in an addon theme, there is a 99% chance it is the addon theme and therefore not a phpVMS v7 issue.
Instead of opening an issue each time something seems incorrect, use the phpVMS discord to post to. Use the 'search' option there or post your issue if 'search' doesn't resolve it.

**Comment by FatihKoz** [comment]
What I found in your log;

1. You have Discord Webhook problems, either define your webhooks properly in your Discord server or do not enable them in v7. 

```
[2023-11-16 19:23:06] production.ERROR: Error sending Discord notification: request: Client error: `POST https://discordapp.com/api/webhooks/` resulted in a `404 Not Found` response:
{"message": "Unknown Webhook", "code": 10015}
```

2. You have a problem with your pirep fares. Do you have imported pireps from v5? How do you use the fare system?

```
[2023-11-16 21:55:53] production.ERROR: Attempt to read property "type" on null {"view":{"view":"/home/malaysi1/skywardair.xyz/resources/views/layouts/Disposable_v3/pireps/show_finance.blade.php"
```

Either in your Tailored Theme or in Dispo Theme, open above mentioned file and add a failsafe check as below. You can also remove that line, as it is just eyecandy information about the type.

```php
@if(filled($fare) && $fare->type === 1) {{ $units['weight'] }} @else pax @endif
```

https://github.com/FatihKoz/DisposableTheme/blob/34c57a3aae874e0592cac801e1301bc89326c49e/resources/views/layouts/Disposable_v3/pireps/show_finance.blade.php#L39C81-L39C81

Good luck
