### ISSUE TITLE
Module Ownership For Flights

### ISSUE THREAD

**Issue by BossOfGames** [nabeelio/phpvms#1681]
**Is your feature request related to a problem? Please describe.**
Right now, I'm creating a trips module with the intention of allowing the module to Add/Remove Flights via the module.

When a trip is completed, I want a clean method of controlling which flights should and shouldn't get deleted. Some of these trips might be a mix of pre-existing Flights, and custom flights.

In addition, when admins are looking at the admin panel, these flights could be easily seen and deleted, which could create problems if that flight is attached to a incomplete trip.

Right now, module controlled/generated flights need to be put in the flights table to allow for the bidding, and pirep logic, to work.

**Describe the solution you'd like**
Add 3 columns, `owner`, `owner_id`, `owner_type`, to designate that the `core` doesn't own the flight. It's module controlled. This will allow for modules to know which flights can be controlled, modified, deleted, without affecting the core flights (i.e. everyone's schedules), or other modules.

Ideally, if the flight is module controlled, these flights could be hidden from the flights page within the admin panel to prevent tampering from admins. Only super admins, with a checkbox, can show ALL flights in the system.

**Describe alternatives you've considered**
In my module's pivot table to link flights to trips, I considered adding a `deletable` boolean so my module knows what's safe and not safe to delete.

This doesn't remove the issue where flights generated could be deleted by admins, which could be considerable problems for foreign relationships, if constraints aren't setup correctly.

**Additional context**

**Comment by nabeelio** [comment]
Good idea, lemme think about it.

**Comment by BossOfGames** [comment]
@nabeelio Has there been any additional thought on this?

I was thinking about going down the path of implementing this on my fork and submitting a PR, if you agree this is a feature that should be put in the project. I definitely need it for my use case. That being said, I don't want to go implement my own solution, when a official solution might be different than what I homebrewed.

**Comment by nabeelio** [comment]
I was thinking of having something a little more robust, like a flight properties table, which then you can store anything related to the flight instead of having every add-on have its own tables and stuff for tracking. This way cleanup is easier.
