### ISSUE TITLE
CKEditor, On Page Edit, Doesn't return all HTML.

### ISSUE THREAD

**Issue by BossOfGames** [nabeelio/phpvms#1685]
**Describe the bug**
When pasting raw HTML into the page editor, the editor saves the html perfectly fine to the server. However, upon reloading the editor, the HTML is drastically simplified and therefore doesn't allow for original editing.

**Version**
7.0.0-dev

**To Reproduce**
1. Go to Admin > Pages/Links > New Page
2. Paste in raw HTML into the editor, using the "Source" Feature
3. Save The Page
4. Visit the page with raw HTML to see that it works fine.
5. Go back to Admin > Pages/Links and edit the page.
6. Click on the "Source" once again to find that CKEditor's HTML is different.
7. If the page is saved, the page will look different.

**Expected behavior**
CKEditor here should return the raw HTML that was submitted originally.

**Screenshots**
Before Edit
<img width="1180" alt="Screenshot 2023-11-26 at 19 07 35" src="https://github.com/nabeelio/phpvms/assets/2882332/6bd68a59-702a-4b38-9223-2910bd6916ec">

<img width="1453" alt="Screenshot 2023-11-26 at 19 04 51" src="https://github.com/nabeelio/phpvms/assets/2882332/9d657e4c-6ca4-469a-b956-b5e4973772a1">

After Edit
<img width="1174" alt="Screenshot 2023-11-26 at 19 06 11" src="https://github.com/nabeelio/phpvms/assets/2882332/fe3c1806-9ce5-415b-a760-a5147fa4a219">
<img width="1435" alt="Screenshot 2023-11-26 at 19 09 02" src="https://github.com/nabeelio/phpvms/assets/2882332/d6eeca3b-6bca-4ae3-b16c-2faca9cf7825">

**Additional context**
None

**Comment by FatihKoz** [comment]
I don't think ckEditor's free version can handle divs and other fancy stuff.

https://ckeditor.com/pricing/

**Comment by BossOfGames** [comment]
Fixed it. Needed to add this:

```js
CKEDITOR.replace('editor', {
      allowedContent: true // This is the magic config option.
    });
```

Now it displays in the editor, and it returns all the HTML like normal.

**Comment by BossOfGames** [comment]
> Do you want to send a PR and contribute or want this change to be done by someone else ?

I can easily take it. The only problem to consider is security. If this option is enabled for all the CKEditor fields, this could become a problem when someone wants to throw in a <script> element. That being said, I have personally never tested it.

@nabeelio are you fine with this change in pages directly? Or would you rather have it controlled by a setting, e.g. a env file entry?

**Comment by nabeelio** [comment]
Enabled is okay
