### ISSUE TITLE
Create PIREP on Flights Doesn't Auto-FIll Airports

### ISSUE THREAD

**Issue by BossOfGames** [nabeelio/phpvms#1708]
**Describe the bug**
When clicking on the Create PIREP button on a flight in the search, the departure and arrival airport fields are not being autofilled.

**Version**
7.0.0-dev latest commit.

**To Reproduce**
1. Go to flights page
2. Click on "File Pirep"
3. See that the airports are not being filled when creating a new pirep.

**Expected behavior**
All the fields from the flight that would be applicable to the PIREP be auto-filled.

**Comment by FatihKoz** [comment]
I think this should be closed
