### ISSUE TITLE
Route Imports

### ISSUE THREAD

**Issue by artccPalmer** [nabeelio/phpvms#1750]
I have recently re-Imported my routes and noticed they are receiving a Leg "0".

So now all my Routes are AAL1406/L.0

How does this get removed

**Comment by FatihKoz** [comment]
Which version you are using ? Issue template asks about this.

![image](https://github.com/nabeelio/phpvms/assets/74361521/5956b1e1-8bb5-44d6-ac30-328c1e7b4d75)

**Comment by artccPalmer** [comment]
<img width="1920" alt="Screenshot 2024-01-16 072004" src="https://github.com/nabeelio/phpvms/assets/100047268/037c258f-f03e-4190-95ca-c49148d07d2e">

**Comment by artccPalmer** [comment]
Okay, thank you....I will let my Web Manager/Pilot Center expert know...
