### ISSUE TITLE
Add news on top

### ISSUE THREAD

**Issue by Strider2** [nabeelio/phpvms#1758]
It would be nice if the add news form on the admin dashboard was always on top 

Instead of having to scroll past all the old news it would be better if the form to add news was always on top and the news items below it.
News items can be long and you might have to scroll a long way down to get to the form.

**Comment by FatihKoz** [comment]
Additionally having a seperate page for news with pagination (instead of admin dashboard) and editing capability would be nice.

**Comment by BossOfGames** [comment]
I am also in favor of just moving news to a separate page. Also:

* Allow drafts to be saved in a "unpublished" state.
* Allow edits to already published articles (this may prevent email spam when there's something left out accidentally, or a spelling mistake)
