### ISSUE TITLE
Hubs as home airports does not show on the registration page

### ISSUE THREAD

**Issue by Strider2** [nabeelio/phpvms#1795]
When you select Hubs as home airport, it does not show on the registration form, it shows all airports in the database.

Version: 7.0.0-dev+240327.d774ff

**To Reproduce**
1. go to admin
2. Click on settings
3. Scroll down to pilots
4. check Hubs as Home airport
5. click on save

Show only the VA's hubs as home airports in the registration form

**Comment by FatihKoz** [comment]
Probably this is an issue with your theme or view cache as it works on my install as designed.

![image](https://github.com/nabeelio/phpvms/assets/74361521/9c4e15b1-cc2a-45e3-a031-e701303288e9)

![image](https://github.com/nabeelio/phpvms/assets/74361521/faf86241-927f-4266-b09d-fbfc25ac5d58)

![image](https://github.com/nabeelio/phpvms/assets/74361521/bfb86bd2-c74c-41aa-8a28-ee2964a98a35)

**Comment by Strider2** [comment]
I use your theme, and i have not made much changes to it, just changed some background images

**Comment by Strider2** [comment]
I dont use that setting myself so it never came up as an issue until i tried it myself

**Comment by FatihKoz** [comment]
Then I would suggest checking + updating your theme if it is outdated 'cause it works on different servers with different settings / hardware etc... 

I can not fix something already working. 
_(This applies to both default and my theme)_
