### ISSUE TITLE
Edit News Items | Feature Request

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1813]
We need to able to edit news items (instead of just deleting and re-inserting them, which causes a new notification sent)

Hopefully before v7.0 release.

**Comment by arthurpar06** [comment]
That's a nice idea
Do you have some time to work on it? I can do it tomorrow or on Monday if you're short on free time right now

**Comment by PaintSplasher** [comment]
I'll request a short addition if it is okay. Why not add a setting if a notification should be sent or not?

For me, I do not want to email every pilot if I post a piece of news.

**Comment by BossOfGames** [comment]
While this is being worked, can wi suggest moving the news to a dedicated page structure in the admin panel with a table and all the trimmings?

I agree that a checkbox should be used to fire off a notification or not, and that the setting key in admin could be removed if done so.
