### ISSUE TITLE
Plane on Map not aligning with route

### ISSUE THREAD

**Issue by AussieVirtual** [nabeelio/phpvms#1836]
**Describe the bug**
As per picture. Plane and flight route don't align. Plane on far left side of picture should be at the end of the blue line not apart

**Version**
7.0.0-dev+240501.2040c9

**To Reproduce**
1. Flight was from NZAA to PHNL

**Expected behavior**
Plane on far left should align with route on far right in blue. Advised in discord that this is a core phpVMS problem, and this is also caused by the Anti-Meridian (where -180 longitude becomes +180). 

**Screenshots**
![image](https://github.com/nabeelio/phpvms/assets/174283354/63360f5f-55d8-463c-85c8-1b768471fcf1)

**Additional context**
N/A

**Comment by FatihKoz** [comment]
This is a limitation of leaflet map being used there. Not a bug of phpvms as it sends the coordinates only :(

**Comment by AussieVirtual** [comment]
I will let them know thanks

**Comment by FatihKoz** [comment]
Let who know ? Leaflet developers ?
