### ISSUE TITLE
Request for aircraft type only to be included in a search field not just a subfleet search with company attached

### ISSUE THREAD

**Issue by AussieVirtual** [nabeelio/phpvms#1851]
**Is your feature request related to a problem? Please describe.**
Currently only way to search aircraft is via sub fleet with a company attached i.e. Airbus A320-232/ANZ

Request code be written for pilots to be able to search for aircraft types only as per previous versions. I.E. A320/B737.

This will enable pilots to see what aircraft types are available to fly from said airport. At the moment pilots are forced to scroll through pages of flights to see if their aircraft is included or go through each sub fleet company available which is time consuming and not user friendly. 

**Describe alternatives you've considered**
Nil available. 

**Additional context**
This was discussed in PHPVMS discord a few days ago with a few ideas included.  Another member also identified the need. See here - https://discord.com/channels/332920618729340929/1126591018997911633/1261052633729470545

Added feature request here so it didn't get lost in discord. 

This would be a huge advantage to our pilots if able to be completed. 

Thank you.

Current search
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/d803528b-bd49-47f0-a6d5-81e8e23167bb">

How a new search would look (older version of PHP VMS)
<img width="206" alt="image" src="https://github.com/user-attachments/assets/b4065b56-91bd-4f22-8220-a29c9ffff548">

**Comment by FatihKoz** [comment]
Even though I do understand the need and idea, which is good to have, please do not try to compare v7 with v5 😄 

v7's fleet/flight relationship logic is totally different from what you are used to use for years.

**Comment by FatihKoz** [comment]
You are right, it does not matter for the people doing stuff behind the scenes 'cause we do not base v7's internals according to v2/v5 series, it only affetcs (or can affect) your expectations and thoughts.

Enjoy your day 😺
