### ISSUE TITLE
"Updating" setting to show a page when you do an update...

### ISSUE THREAD

**Issue by sarcas31** [nabeelio/phpvms#1865]
A blade page to turn on by setting when you perform an update on the system, or turn off when the update or the code modifications are finish and the system its going up again.

PD: Show a message for users to know when its completed the update maybe.

**Comment by FatihKoz** [comment]
Update takes a couple of seconds to complete, why you want something like this for them.

If you are asking a maintenance mode in general, it is already possible but no buttons or settings, can be enabled by command line access.

https://laravel.com/docs/10.x/configuration#maintenance-mode

**Comment by sarcas31** [comment]
The think is to have an option to disable temporary the system durring perform a changes into the system. The user cannot to bid a flight, bid an aircraft, etc.

**Comment by FatihKoz** [comment]
Ok, then you can use the commands explained in the link I shared above.

A site can be disabled (maintenance mode) but you can work on it with the built in "secret code" logic.

Be advised, without that system, both frontend and backend will be down, so it will not be possible to have a button for those commands easily. Command line access is required.

**Comment by sarcas31** [comment]
Ok thanks
