### ISSUE TITLE
Addition of Expenses for Indvidual Flight Routes 

### ISSUE THREAD

**Issue by CaptainGodual** [nabeelio/phpvms#1891]
***Is your feature request related to a problem? Please describe.***
Currently, PHPVMS7 allows for setting expenses at the airline level, for subfleets, and for individual airports, but there is no option to assign specific expenses to individual flight routes. This makes it difficult to simulate realistic operational costs for different types of flights, such as international vs. domestic routes. We are unable to apply differentiated costs based on the nature of the route (e.g., international flights generally have higher operational costs compared to domestic flights), which limits the realism of flight cost simulations for virtual airlines (VAs).

***Describe the solution you'd like***
I would like to request the ability to assign specific operational expenses to individual flight routes in PHPVMS7. This could include using multipliers for different types of flights (e.g., domestic, international, or specific route types). The system should allow for the setting of route-specific expenses, making it easier for virtual airlines to simulate more accurate and realistic operational costs. Ideally, this would integrate seamlessly with the existing expense system already available for airlines, subfleets, and airports.

***Describe alternatives you've considered***
Currently, we just use the existing expense system that applies costs at the airport, airline, or subfleet level. While this works to some degree, it doesn't allow for route-specific cost differentiation, which is essential for simulating realistic operational costs for international and domestic flights. This workaround is not ideal, as it doesn't reflect the varied costs associated with different flight routes.

***Additional context***
Implementing this feature would allow virtual airlines to more accurately simulate real-world operational costs, improving the realism of flight scheduling, route planning, and financial management. It would also streamline the setup process for VAs that operate multiple routes, especially those with differing international and domestic expenses. I do not know if this is possible, but I wanted to submit this as a feature request.

**Comment by FatihKoz** [comment]
![image](https://github.com/user-attachments/assets/7cc2c591-ee69-492f-8f6d-0ed3526b3b0d)

I think you wish something additional to the `Flight` and `Flight Type` selections for expenses, like city pairs (DEP:ARR) or countries (US:US or US:CA) etc. or a checkbox for `Apply To Domestic Flights (same country for DEP:ARR)`... 

I saw airlines defining expenses for specific flight types and building their schedules accordingly but it may not something you are after.

**Comment by CaptainGodual** [comment]
Hi FaithKoz,

Yes, Basically what I am wanting is something that pairs with City's (DEP:ARR) or countries (US:SU or US:CA) or like you said a checkbox to apply to domestic Flights or Interational. I want to be able to have the expenses applied if say I'm landing at a specific Domestic or International Airport and Simulate those Fees as appropriate.

**Comment by FatihKoz** [comment]
They are all different things, you want them all. 

And now you are adding "Domestic Airport" / "International Airport" logic to the equation. For this you can use the airport based expenses, so if someone lands to that airport (or departs from that airport) relevant expenses do apply.

What you first wanted in your initial post was something different, so do you want

1. Flight City Pair Based Expenses (with defined DEP:ARR)
2. Country Based Expenses (with defined countries US:CA)
3. Country Based Expenses (with a checkbox, to apply on to domestic flights)

And as a general fact, you can define your own expenses with your own module/addon, it is possible and in there you can have endless possibilities.

Custom Expenses / Custom Income logic is built for this purpose.

**Comment by CaptainGodual** [comment]
Okay, I will close this request and look at a custom module thanks

**Comment by FatihKoz** [comment]
Yeah, check below files for explanations

Fare (Income) : https://github.com/nabeelio/phpvms/blob/dev/app/Listeners/FareListener.php
Expense : https://github.com/nabeelio/phpvms/blob/dev/app/Listeners/ExpenseListener.php

When you have your own listener (with a simple module) you can create income or expenses as you wish and it will be fully tailored to your VA.

Good luck

**Comment by CaptainGodual** [comment]
Hi Dispo,

Ok I understand the listener, just confused on how to execute it as this is
the first time doing this and kind of all new to me.

Sorry for the hassle

**Comment by CaptainGodual** [comment]
Actually I just found it, so nvm sorry for the hassle guys!

https://docs.phpvms.net/developers/addons
