### ISSUE TITLE
Allow Only Company Aircraft (Flights)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#1898]
**Is your feature request related to a problem? Please describe.**
No, this is a new feature.

**Describe the solution you'd like**
Currently when a flight is created and/or imported without subfleet assignments, all subfleets a user is allowed to fly can be used for that flight. In a multiple airline environment this can cause unwanted results like Airline A's aircraft being used for Airline B's flights. 

As a solution, we should have some control or at least some automation for this. Like a setting, which then loads only the subfleets of that particular flight's airline instead of loading all.

We do have rank/typerating based filters for subfleets so nothing more is needed, rest of system will continue working on as before.

**Describe alternatives you've considered**
Alternatively we can have some admin features, to auto assign airline subfleets to airline flights if they do not have any. With this we can also allow admins to delete all subfleet assignments of an airline etc. But these will require direct model / relationship table interactions and will be partly automated.

**Comment by BossOfGames** [comment]
Accept the PR. I was about to work on this myself. I agree with the implementation.
