### ISSUE TITLE
Multiple-Source Telemetry for PIREPs

### ISSUE THREAD

**Issue by BossOfGames** [nabeelio/phpvms#1903]
**Is your feature request related to a problem? Please describe.**
Right now, the API and phpVMS assumes that there's only one source of information to log for flight from a telemetry and logging perspective. I want to change the behavior of this to allow for multiple sources of telemetry, and logs, information to be stored with a pirep.

This change can:
* Allow for multiple sources to provide telemetry, and not conflict.
* Display multiple sets of logs or multiple telemetry lines for a flight (e.g. see if the VATSIM telemetry matches the ACARS telemetry)

**Describe the solution you'd like**
* Create a new `source` column in the `acars` table as a string that's nullable.
* Modify the API to allow for setting this value.

**Describe alternatives you've considered**
No reasonable alternative has been considered for this.

**Additional context**
I have a online network client module, similar to how IPS worked back in the day, in the wings, and this change is essential so the module can log data and not interfere with vmsACARS or smartCARS logging.

**Comment by BossOfGames** [comment]
> Instead of strings we can use a source column (int) with some enums defined maybe.

Where would the enum be defined? Create another table in the DB?

The reason for a string was so that the full name could be used. Though, I can see why that's also a bad idea because it would be very inefficient on space.

**Comment by BossOfGames** [comment]
Here's what I have so far regarding schema for this. @FatihKoz is this what you were referring to with a integer?

```php
        Schema::table('acars', function (Blueprint $table) {
            $table->foreignId('source_id')->nullable();
        });

        Schema::create('acars_sources', function (Blueprint $table) {
            $table->id();
            $table->string('slug');
            $table->string('name')->nullable();
        });
```

**Comment by FatihKoz** [comment]
Still having the same question, why not having an ENUM defined for sources like others we have.

https://github.com/nabeelio/phpvms/tree/dev/app/Models/Enums

Then you can have a simple field added to the acars table, `$table->unsignedTinyInteger('source');` (we can easily switch to small or normal unsigned integers too if needed)

```php
<?php

namespace App\Models\Enums;

use App\Contracts\Enum;

class AcarsSource extends Enum
{
    public const VMSACARS = 0;
    public const SMARTCARS = 1;
    public const IVAO = 3;
    public const VATSIM = 4;

    protected static array $labels = [
        self::VMSCARS => 'vmsACARS',
        self::SMARTCARS  => 'SmartCARS 3',
        self::IVAO  => 'IVAO Tracker',
        self::VATSIM => 'VATSIM API',
    ];
}
```

And if someone needs to separate something really 3rd party, enum can be updated to have something assigned to that or even that field can be used directly with a value, imagine yourself developing something and using `108` for your specific constant identifier.

With your solution, somebody (the dev of the addon) should write to that acars_sources table, get his/her/its assigned ID and need to use it. Or he/she/it needs to send the slug to get a match for the ID on each request etc. etc.

I do agree on having a field for source but the rest, slugs, additional table looks a bit not necessary at the moment. This is why I asked about enums in the first place @BossOfGames

**Comment by BossOfGames** [comment]
> Still having the same question, why not having an ENUM defined for sources like others we have.
> 
> https://github.com/nabeelio/phpvms/tree/dev/app/Models/Enums
> 
> Then you can have a simple field added to the acars table, `$table->unsignedTinyInteger('source');` (we can easily switch to small or normal unsigned integers too if needed)
> 
> ```
> <?php
> 
> namespace App\Models\Enums;
> 
> use App\Contracts\Enum;
> 
> class AcarsSource extends Enum
> {
>     public const VMSACARS = 0;
>     public const SMARTCARS = 1;
>     public const IVAO = 3;
>     public const VATSIM = 4;
> 
>     protected static array $labels = [
>         self::VMSCARS => 'vmsACARS',
>         self::SMARTCARS  => 'SmartCARS 3',
>         self::IVAO  => 'IVAO Tracker',
>         self::VATSIM => 'VATSIM API',
>     ];
> }
> ```
> 
> And if someone needs to separate something really 3rd party, enum can be updated to have something assigned to that or even that field can be used directly with a value, imagine yourself developing something and using `108` for your specific constant identifier.
> 
> With your solution, somebody (the dev of the addon) should write to that acars_sources table, get his/her/its assigned ID and need to use it. Or he/she/it needs to send the slug to get a match for the ID on each request etc. etc.
> 
> I do agree on having a field for source but the rest, slugs, additional table looks a bit not necessary at the moment. This is why I asked about enums in the first place @BossOfGames

That makes a lot more sense, and 3rd party developers can easily modify that file to add additional clients as needed.

I'll change my draft around to reflect that. Thanks!

**Comment by arthurpar06** [comment]
I understand the idea of using an enum, but I’m not sure if it’s the most easily modular approach. It would mean that people would need to submit a PR here every time they want to add a source linked to one of their modules... I understand that the additional table might seem unnecessary though. Do you think there might be a middle-ground way to manage this?

**Comment by nabeelio** [comment]
Interesting idea. I wouldn't use an enum, in this case. A string is fine. Are you envisioning this to be the same type of data going into the acars columns?

**Comment by BossOfGames** [comment]
> I understand the idea of using an enum, but I’m not sure if it’s the most easily modular approach. It would mean that people would need to submit a PR here every time they want to add a source linked to one of their modules... I understand that the additional table might seem unnecessary though. Do you think there might be a middle-ground way to manage this?

My original thought was to have a sources table with a `slug` and `name` field. That way sources can be added independently and dynamically.

The drawbacks are definitely management. For example, a client source would need to have a slug or would need to know its integer ID when submitting the request. If it provides a slug, then it'll be tapping the DB every request to figure out the integer ID.

I do have this somewhat sorted out, as in the PR, I have created a new API route that allows a client to get the list of supported sources from phpVMS (we could do the same for the FlightType enum to return a "localized list" of types, instead of hardcoding them in clients. Issue for another time)

> Interesting idea. I wouldn't use an enum, in this case. A string is fine. Are you envisioning this to be the same type of data going into the acars columns?

The reason for having an integer, and why I agree with @FatihKoz's implementation is that strings, in this instance, can dramatically increase the size of the DB in the area with easily the most records in the whole system.

Yes, the idea is that you can have two fully independent clients writing to the same flight tables at the same time, whether its telemetry or logs.

**Comment by nabeelio** [comment]
I don't think size is too much of a concern. Let's say it's limited to 3 characters, with only non-phpvms sources being required to set it? Or do you think there might be just as much data?

**Comment by BossOfGames** [comment]
> I don't think size is too much of a concern. Let's say it's limited to 3 characters, with only non-phpvms sources being required to set it? Or do you think there might be just as much data?

Ideally, all sources would set it. For example, on the pireps page, you could have vmsACARS telemetry separated from VATSIM telemetry. If it is limited to 3 characters, how would we go about setting displaying that info with a fancy name easily?

With the above considerations, you begin to go down the path of either enums or database tables with set IDs.

If we implemented only a string to start, it makes it easier for us to define a table with a fancy name, description, etc. if we decide to later. Though, I would rather do a integer for space savings now, if we know we're going to go down that path.

**Comment by FatihKoz** [comment]
Considering the consequences and effects of both methods, I would like to ask some different questions...

What will be that "external" telemetry ? 
Why do we need it in acars table ? 
What will we do with it ?

I mean, if it will be coordinates, speeds, headings, altitudes etc. why do we need it to stay along the acars telemetry side by side ? What will be total gain of having it, if there are some necessities (say for VATSIM or similar), then why in acars table ? 

It is an external source after all, not from a source/client directly connected to the sim/aircraft.

Can't a developer, while creating an addon, create a separate model / db table for that telemetry if it is that much important or required ? 

Then the contents can be displayed along with a pirep, either with extending the current pirep model by adding relationships or by just loading the content whenever required.

I think adding an enum or using a string should be considered/discussed later, after deciding to store non-acars data in acars model :)

**Comment by FatihKoz** [comment]
As an example to an external source, I am providing support for StableApproach plugin (currently only for XP, hopefully will have it in MSFS too in near future).

It is 100% external and optional, I created a model (and a db table as expected), recording the data without any alterations to base models or controllers, displaying it along with the related pirep easily. I never thought storing the data in acars or pirep models for this. It uses a custom enpoint to communicate with v7 whenever needed and stores its own data, that simple was the logic.

Why can't we have something similar for VATSIM Telemetry (or any other external source) but trying to add stuff to current base models ?

**Comment by BossOfGames** [comment]
> As an example to an external source, I am providing support for StableApproach plugin (currently only for XP, hopefully will have it in MSFS too in near future).
> 
> It is 100% external and optional, I created a model (and a db table as expected), recording the data without any alterations to base models or controllers, displaying it along with the related pirep easily. I never thought storing the data in acars or pirep models for this. It uses a custom enpoint to communicate with v7 whenever needed and stores its own data, that simple was the logic.
> 
> Why can't we have something similar for VATSIM Telemetry (or any other external source) but trying to add stuff to current base models ?

The use case I am trying to apply for here is that the VATSIM telemetry will, optionally, take the place of an ACARS client entirely, where I can use a software-less client setup for communities. In effect, creating a free client by utilizing somebody else's infrastructure.

Since VATSIM telemetry provides the same data as ACARS, minus the events and ability to start and stop flights, and there's options and ways to use this telemetry (e.g. building maps), I think it's natural to put this data into the acars table. Also remember, the acars table stores the logs too, which can be utilized (e.g. creating a log entry when a flight enters controlled airspace, checking what COM 1 frequency is tuned to verify they're on the right frequency for the DEP/ARR airport, etc.).

The overall issue I have with the above implementation is that I want a case where my tracking will work in cases where an ACARS client is used or not. I don't think it's productive to write code that writes to two separate places based on if a client is used or not.

**Comment by FatihKoz** [comment]
Users no, developers or a developer will have to put effort for fulfilling your wish :) So here it is you basically, trying to reduce the amount of your time and efforts by skipping at least two steps (model creation and api endpoint creation) in the beginning. Which is fair an understandable, no bad feelings there.

I still think then my first approach, having an enum and sending it with the api should be more than enough ;)

And if in near future somebody else wants to do a similar addon/client/integration for IVAO they can use the predefined enum or request a new item to be added.

Ps: There will more stuff missing with VATSIM telemetry, not just events but in a clientless install all can be acceptable, and this is not the topic of this conversation :)

**Comment by BossOfGames** [comment]
@FatihKoz fair enough. I like the enum implementation the most, especially after you explained it.

@nabeelio since you have the final say here on what gets pulled, given the information above, what is the best course of action? Will you accept a solution that includes a enum?

**Comment by nabeelio** [comment]
An enum is messy and you could get conflicts pretty easily - let's say you decide to use 4 and then an update comes out adding 4. 

A string with a 5 character limit makes the most sense. If you look at it this way - if you create the column with the `latin1` encoding, which will ensure it's 1 byte per char, 100,000 rows at 5 bytes used at max, it's only 500KB of storage extra, with maybe a little more for overhead

I don't think that's worth the hassle and potential conflicts down the road

**Comment by BossOfGames** [comment]
> An enum is messy and you could get conflicts pretty easily - let's say you decide to use 4 and then an update comes out adding 4.
> 
> A string with a 5 character limit makes the most sense. If you look at it this way - if you create the column with the `latin1` encoding, which will ensure it's 1 byte per char, 100,000 rows at 5 bytes used at max, it's only 500KB of storage extra, with maybe a little more for overhead
> 
> I don't think that's worth the hassle and potential conflicts down the road

Ok, that's fair. We can back that with an enum if we decide later. Plus, since MySQL ints are 4 bytes, I won't get hung up on an extra byte.

I'll modify my PR to remove the enum and change the column type to a string with a limit of 5.

**Comment by nabeelio** [comment]
> Ok, that's fair. We can back that with an enum if we decide later. Plus, since MySQL ints are 4 bytes, I won't get hung up on an extra byte.

Yeah, in the grand scheme of that table, if someone really wanted to save space, there's other areas to reduce (lat/lon resolution, etc).
