### ISSUE TITLE
Admin, edit PIREP - error when clicking Save

### ISSUE THREAD

**Issue by ProAviaAZ** [nabeelio/phpvms#1912]
**Describe the bug**
From admin, pirep - select a PIREP and click Edit. Edit a field and click Save.
The Flt. Dist. is shown in 2 decimal places. During the Save, it seems to only allow 1 decimal place.

**Version**
7.0.46 - also occurred on prior versions

**To Reproduce**
1. Go to admin, select a PIREP, click Edit
2. Edit a selected area (not Flt. Dist.)
3. Click Save
5. Error (information popup?) shows 'Please enter a valid value...' directly under Flt. Dist. - changing the value in Flt. Dist. to one decimal place allows the Save to complete successfully.

**Expected behavior**
Either change Flt. Dist. to one decimal place precision or allow a Save with the present two decimal places.
One decimal place (correctly rounded) should be more than enough precision.

**Screenshots**
![image](https://github.com/user-attachments/assets/253a21f6-c7e5-4830-9863-db8c4cdc5c12)

**Additional context**
Nothing in the Laravel log.

**Comment by FatihKoz** [comment]
Check #1913 if you need an urgent fix 😉

**Comment by ProAviaAZ** [comment]
Thanks for the fix. 👍 - it's more of a minor annoyance that I kept forgetting to document. Certainly not urgent.
