### ISSUE TITLE
Auto loader on Line 17

### ISSUE THREAD

**Issue by Jonah0037** [nabeelio/phpvms#215]
Hello, I am getting an error on line 17 for the autoloader.php

**Comment by Jonah0037** [comment]
I believe it is in the bootstrap folder

**Comment by nabeelio** [comment]
Hi. I need more information than that - what is the error? What version of PHP are you on? Who's your host? Apache, nginx?

**Comment by Jonah0037** [comment]
That’s my error and my host is dream host, used to be TFDi

**Comment by Jonah0037** [comment]
My PHP version is 7.1, and I just went to where it said download in the green button on main GitHub page for phpvms

**Comment by nabeelio** [comment]
Try the one on this page:
https://github.com/nabeelio/phpvms/releases

For the one on Github, it just downloads the source and you need to run `composer install` to get all the dependencies.
