### ISSUE TITLE
File/avatar uploads

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#226]
### file uploads

- [x] `files` table that looks like `expenses` - with a `ref_class` and `ref_class_id` to allow attaching files to different assets - aircraft, airports initially
- [x] generic file uploader component and service class

### avatar

- [X] `avatar` column in `user` table
- [ ] avatar upload and change

**Comment by joooseb** [comment]
I'll take this Issue, we'll use the simple upload file method of Laravel?, phpvms have a external package to manage images?

**Comment by nabeelio** [comment]
@joooseb yes, let's use the simple upload... it should upload to `public/uploads/avatars`, and then it should store the path (from the `public/` folder) in the `avatar` column... so just `uploads/avatar/avatar.png`. And then, it'll look like, in a template, `{{ $user->avatar }}`, and that should have the correct link. The `getAvatarAttribute()` on the user model should "just" work.

There should also be a clear avatar button. And then we can do the same thing for the rank table. I was thinking we can use [Intervention/image](https://github.com/Intervention/image) to resize the images. I think we should create a config section in `config/phpvms.php`, for it:

```php
'avatar' => [
  'width': '200px',
  'height': '200px',
],
```
And that can be used to dictate the resizing.

**Comment by nabeelio** [comment]
And once that's working, it should work about the same for ranks, except into `public/uploads/ranks`. Then on the profile page, if there's a rank image, it can be shown there

**Comment by joooseb** [comment]
Ok, thanks you for the information. I worked with intervention package in other Laravel project, I'll install the package into phpvms (so the PR will contain a modification into composer.json) and I'm going to start to work, I will back soon :)!

**Comment by nabeelio** [comment]
Thanks, take your time!

**Comment by nabeelio** [comment]
Hmm, I'm not exactly sure what you mean. Do you mean the link above it what it's creating? The `getAvatarAttribute` is needed because it returns a `File` object, which I use to build the URL - it's needed because some people might be on shared hosting, where the URL root is `/` instead of `/public`. I modified the Laravel bootloader to detect which `index.php` is being called and then re-setting the root public (which is how the helper `public_asset()` that I added works).
