### ISSUE TITLE
Module artisan command bug

### ISSUE THREAD

**Issue by joooseb** [nabeelio/phpvms#234]
It create a Admin controller with incorrectly namespace
for example:
php artisan module:make EventCenter
In AdminController.php shows:
namespace Modules\EventCenter\Http\Controllers;
but should be: 
namespace Modules\EventCenter\Http\Controllers\Admin;
and it create a wrong admin prefix on routes at ServiceProvider:
 /**
         * Routes for the admin
         */
        Route::group([
            'as' => 'eventcenter.',
            'prefix' => 'api/eventcenter/admin',
            // If you want a RESTful module, change this to 'api'
            'middleware' => ['web', 'role:admin'],
            'namespace' => 'Modules\EventCenter\Http\Controllers\Admin'
        ], function() {
            $this->loadRoutesFrom(__DIR__ . '/../Http/Routes/admin.php');
        });
it call a prefix to /api/ should be without /api/:
 /**
         * Routes for the admin
         */
        Route::group([
            'as' => 'eventcenter.',
            'prefix' => 'eventcenter/admin',
            // If you want a RESTful module, change this to 'api'
            'middleware' => ['web', 'role:admin'],
            'namespace' => 'Modules\EventCenter\Http\Controllers\Admin'
        ], function() {
            $this->loadRoutesFrom(__DIR__ . '/../Http/Routes/admin.php');
        });
If you modify these lines the 404 error at admin route of the module will be fix.

Hope this help you!

**Comment by joooseb** [comment]
Solved in dev branch

**Comment by nabeelio** [comment]
Yeah, I need to merge dev into master and will do that soon.
