### ISSUE TITLE
Suggestion: edit pilot ID

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#265]
- [ ] 1. Add a option to edit pilot ID ex:
![Imgur](https://i.imgur.com/ARemTif.jpg)

P.S: I don't know if you want all suggestions in a issue or in multiples.

**Comment by nabeelio** [comment]
Multiple is fine! Easier to track. This exists in the old version, correct?

**Comment by arv187** [comment]
It is right, http://YOUR_WEB_PAGE/admin/index.php/maintenance/changepilotid
With this warning:

> NOTE: Be VERY cautioned when changing a pilot ID. Even though this is 'controlled', problems can still occur. If you change the pilot ID to a number which is HIGHER than the highest pilot ID, all new registered pilots will have an ID starting after that. This WILL change their login ID. This user cannot be logged in while doing the change.
> 
> The PILOT ID is shown in the following format below:
> 
> FORMATTED_PILOT_ID - DATABASE_ID - NAME
> 
> You must enter a new DATABASE_ID. The formatted pilow ID is based on the database ID and the offset. Your current offset is 0.
> 
> For example, you want the pilot ID to be VMS200 - for the new ID you would enter: 200. If your offset is 1000 (meaning all pilot IDs start from 1000), to have a pilot ID of 1030 you would change the DB ID to 30 (that's what you would enter below).
> 
> ID Calculator: Enter the intended pilot ID:

**Comment by nabeelio** [comment]
So you basically just want that same functionality?

**Comment by arv187** [comment]
Yes,

**Comment by nabeelio** [comment]
Just leave some notes for myself:

- add `ident` columns to `users` table (or `callsign`?) - as a string
- Update `getIdentAttribute` to read/format from that column
- When registering, find highest and add 1 (or setting to fill any gaps?)

**Comment by nabeelio** [comment]
@arv187 I'm working on this now. Was there a starting offset for the pilot IDs? I can't remember if there was a setting somewhere

**Comment by nabeelio** [comment]
Nevermind, there wasn't. I think I'll just leave the behavior to be about the same.

**Comment by arv187** [comment]
Hi @nabeelio I don't understand what you mean but I see that you already found out.
There are a text saying "The formatted pilow ID is based on the database ID and the offset. **Your current offset is 0**."
I think that the old behaviour was ok.

**Comment by nabeelio** [comment]
Ah, ok. I might eliminate the offset part because I think it might complicate things.

**Comment by nabeelio** [comment]
@arv187 Please test this in the latest versions and let me know if this works well enough
