### ISSUE TITLE
Suggestion: button to copy aircraft

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#267]
- [ ] Add a button to copy aircraft, for example, you want a 737-8 subfleet with ten 737-800 NG aircrafts, then you do click in copy and after you only need write/modify the registration numer or what you need.
Example:
![Imgur](https://i.imgur.com/sq0yyBw.jpg)

**Comment by nabeelio** [comment]
This one is a little tougher to do - there would need to be an interface to do so. The easiest way would be to just create a new CSV with all of the aircraft and then import it. That way, in the import, you can set the subfleet for all of the aircraft too.

**Comment by nabeelio** [comment]
It's more complex - the registration IDs also need to be set. The easiest way is to do the CSV import
