### ISSUE TITLE
Importing *.csv with special characters

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#282]
v7.0.0-180920-61c7a3
When a csv with special characters (ñ á é í ó) are imported, data isn't being imported correctly:

*.csv uft8 - mysql uft8_unicode_ci

Importing:
icao,iata,name,location,country,timezone,hub,lat,lon,ground_handling_cost,fuel_100ll_cost,fuel_jeta_cost,fuel_mogas_cost
`LEMD,MAD,"Adolfo Suárez Madrid?Barajas Airport",Madrid,Spain,Europe/Madrid,1,40.4719,-3.5626,,4.42,4,`
Result in:
icao,iata,name,location,country,timezone,hub,lat,lon,ground_handling_cost,fuel_100ll_cost,fuel_jeta_cost,fuel_mogas_cost
`"LEMD","MAD","LEMD","Adolfo Su","Madrid","Spain","Europe/Madrid","1","40.4719","-3.5626",NULL,"4.42","4.00",NULL`

**Comment by nabeelio** [comment]
Is it truncating the name?

**Comment by arv187** [comment]
Yes

**Comment by arv187** [comment]
[airports(exported from phpvms7).zip](https://github.com/nabeelio/phpvms/files/2433550/airports.exported.from.phpvms7.zip)

**Comment by nabeelio** [comment]
Ok so I adjusted the exporter to go to utf-8. I'm not sure why I had forced it to iso. The sample file above is trashed (sorry) so you'll need to export from fresh.
