### ISSUE TITLE
Undocumented Extension Required - PHP 7.2 GMP

### ISSUE THREAD

**Issue by Hubok** [nabeelio/phpvms#285]
Just leaving a note for an update to the documentation and the install script. At least for PHP 7.2, the php7.2-gmp extension is required for the add flight menu to work, along with likely other things I haven't discovered yet. Only was able to discover this when enabling debug mode to see the reason for an error.

(1/1) RuntimeException
Missing BC Math or GMP extension.

**Comment by nabeelio** [comment]
Hmm, that's a weird one, well, for that menu at least. Thanks for the heads up
