### ISSUE TITLE
"Hubs as home airport" doesn't work

### ISSUE THREAD

**Issue by flightcode** [nabeelio/phpvms#288]
Selecting this doesn't change what airports show as 'home airports' on the register page. Only hubs show as available home airports on the register page, although you can choose any airport when you edit profile.

**Comment by nabeelio** [comment]
> Only hubs show as available home airports on the register page

This is correct, you can only choose hubs as your home

>  although you can choose any airport when you edit profile.

This one is wrong

**Comment by nabeelio** [comment]
I think this is OK now as of the latest dev, can you please check?
