### ISSUE TITLE
Ability to change interval of cron jobs

### ISSUE THREAD

**Issue by flightcode** [nabeelio/phpvms#289]
Some servers (eg. Namecheap) limit to 5 minute intervals. Is it possible to change a setting, such that the software knows the cron job will be run every 5 minutes, rather than every minute?

**Comment by nabeelio** [comment]
I'll look into this. Having the main cron job run every 5 minutes is OK, laravel will just regulate when it runs the sub jobs according to that timing

**Comment by nabeelio** [comment]
So, just set this to the minimum time that your host requires and it'll be handled by Laravel.
