### ISSUE TITLE
Ability to change tiles of live map

### ISSUE THREAD

**Issue by flightcode** [nabeelio/phpvms#290]
Add a setting where we can select a tileset from the [leaflet tile providers page](https://leaflet-extras.github.io/leaflet-providers/preview/), rather than being restricted to one?

**Comment by nabeelio** [comment]
You can, it's here: https://github.com/nabeelio/phpvms/blob/master/config/map.php#L6
Just hasn't been documented yet

**Comment by nabeelio** [comment]
Adding note to add a setting with different possibilities and those can be passed into the livemap via template
