### ISSUE TITLE
No Staff Groups/ Authorised Permissions

### ISSUE THREAD

**Issue by TomNastovski** [nabeelio/phpvms#296]
Currently no groups/no option to authorise staffing roles or ability to make staff groups and limit and authorise their certain access control to the admin center.

**Comment by nabeelio** [comment]
Adding a note for myself here: https://github.com/spatie/laravel-permission

**Comment by nabeelio** [comment]
@TomNastovski Do you want to be able to create groups and then restrict permissions/pages they can view in the admin?

**Comment by TomNastovski** [comment]
Yes precisely what I'm talking about. Like what the original phpvms uses.

**Comment by nabeelio** [comment]
@TomNastovski Can you try the latest dev version and see if it works out?

**Comment by TomNastovski** [comment]
There is still no way of adding permissions or staff groups. I've been trying for a long time.

**Comment by nabeelio** [comment]
@TomNastovski in the latest dev, under Admin -> Config, go to roles, see if that works.
