### ISSUE TITLE
Extend search schedule options

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#297]
In the new phpvms v7 there are only search by:

- flight num
- dep.airport
- arr.airport

In the old phpvms there were by:

- dep.airport
- arr.airport
- aircraft type
- distance

It would be fantastic to include the old ones in addition to adding the distance by range, between "x" miles and "y" miles. Since the phpvms v2 only has the option of greater than "x" or less than "x", not both.

**Comment by nabeelio** [comment]
Add to here: `app/Repositories/FlightRepository.php::73`
