### ISSUE TITLE
Error with installer - Permission  denied

### ISSUE THREAD

**Issue by RHS-Code** [nabeelio/phpvms#298]
After I've copied the files to the correct directory and tried to open the installer, but it told me Permission denied. I set the Permissions for every file and directory having to do with it to 777 but it's still telling me permission denied. (I've also tried several browsers)
Specs:
Raspberry Pi 3B+ with Fedora ARM 29
Apache 2.4
PHP 7.2.16
<img width="528" alt="Bildschirmfoto 2019-04-06 um 14 42 07" src="https://user-images.githubusercontent.com/47667293/55669653-506bb080-587a-11e9-8669-4fc7d25eeaa8.png">
<img width="476" alt="Bildschirmfoto 2019-04-06 um 14 41 26" src="https://user-images.githubusercontent.com/47667293/55669654-51044700-587a-11e9-8055-6c1a6bf89c1c.png">

**Comment by nabeelio** [comment]
That user and group look wrong. Try running a `chmod -R <user>: .`, replacing `<user>` with the webserver user.

**Comment by RHS-Code** [comment]
Changed the user and group, still the same error (your command didn't work I've used `chown -R <user>:<group> <path>`

**Comment by younesskhinit** [comment]
Try this : chown -R www-data:www-data <path>

**Comment by RHS-Code** [comment]
Thank you it worked.
