### ISSUE TITLE
Errors versión 7.0.0 (compilación 181025-6f7735)

### ISSUE THREAD

**Issue by jftejeiro** [nabeelio/phpvms#332]
Polirom:
version 7.0.0 (build 181025-6f7735)
When you report a PIREP on the DASHBOARd page, the flight is not counted in FLIGHT. But if you add the money to the pilot.
In the Pilot Profile, the flight hours and the number of flights made are not counted

**Comment by nabeelio** [comment]
Has the flight been accepted?

**Comment by jftejeiro** [comment]
Yes. I have it since they are accepted automatically. They are all accepted.

**Comment by jftejeiro** [comment]
https://subefotos.com/ver/?2cf1bfe0e591042d9bd9eece5e66046ao.jpg
https://subefotos.com/ver/?2cd1a9849790ce77d2dbc29db3eaa1c3o.jpg

**Comment by nabeelio** [comment]
Is any caching enabled in the Laravel config?

**Comment by jftejeiro** [comment]
No

**Comment by nabeelio** [comment]
Which dashboard? Admin?

**Comment by nabeelio** [comment]
Please try now with the latest dev version
http://downloads.phpvms.net/phpvms-v7.0.0-dev.tar.gz
