### ISSUE TITLE
Why don't you create a free ACARS for PHPVMS7 testing?

### ISSUE THREAD

**Issue by jftejeiro** [nabeelio/phpvms#336]
You could do a free ACARS so we can try PHPVMS7. If APVAcars fails we cannot continue tested.
  Better than the person who creates PHPVMS 7 do an ACARS that we can use. If someone else does it, every modification you make of PHPVMS 7 does not work APVacars. In a week I talked to Vangelis and I get two updates for APVacars.

Now it fails again for the latest version of PHPVMS7 and we cannot continue using PHPVMS7.

Could you raise the possibility of creating a reduced ACARS to try?
Thank you

**Comment by nabeelio** [comment]
I had thought about it but it's just too much work. I barely get time to work on things as they are. The phpVMS API hasn't been changed for functionality since October. I'm happy to work with Vangelis on any bugs he finds (and have been)
