### ISSUE TITLE
Integration with PACX [Feature]

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#338]
**Integration with PACX - TFDi Design in the future?**

Is possible use this software to send/save pireps in phpvms7?

Development and Asset Creation Guide:
https://forums.tfdidesign.com/index.php?/topic/3800-pacx-development-and-asset-creation-guide

**Comment by nabeelio** [comment]
Sure, that'd be up to them to do

**Comment by arv187** [comment]
https://forums.tfdidesign.com/index.php?/topic/3800-pacx-development-and-asset-creation-guide/

They talk about:
_Using the PACX Web XML System_
uploading xml to phpvms7?
and
_Using the PACX Network API_
I don't understand this, may be to communicate directly with phpvms7?

Anyway we can take a look when the development of phpvms7 and pacx are more advanced.

Thanks!
