### ISSUE TITLE
Fuel cost only allows whole numbers for price

### ISSUE THREAD

**Issue by ProAviaAZ** [nabeelio/phpvms#342]
Presently, fuel cost can only be set to a whole number. As cost is per pound of fuel, should allow setting decimals also. Two decimal places should work.

Jet fuel at $0.85/pound would be approximately $5.69/gallon (0.85 * 6.7lbs/gal).

Possibly all cost can be set to accommodate two decimal places.... ground handling, fuel, and all other costs.

Hopefully, this is possible.

**Comment by nabeelio** [comment]
If you can, check out the `issue/342-fuel-prices` branch

**Comment by ProAviaAZ** [comment]
Prices can now be entered in 2 point decimal format. I have not checked if they are computed correctly, just that they can be entered.

**Comment by nabeelio** [comment]
Great, thanks!
