### ISSUE TITLE
Error Seeing data of pilot profile

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#351]
**Describe the bug**
Recently installed with modifications #349 (except .travis/phpunit.travis.xml I didn't find that file), added country and home, actual airport to user profile. When click on profile (in frontend user side) or on pilots---> pilot "x" (to see his profile) a blank page with error message is shown: 

> Whoops, looks like something went wrong.

In log server say:

> #53 /home/argavirt/public_html/phpvms7/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#54 /home/argavirt/public_html/phpvms7/index.php(18): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#55 {main}
"} 

**To Reproduce**
Described avobe

**Expected behavior**
See data of pilot profile

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: W10
 - Browser: Firefox 
 - Version: 68.0.1 64bits

**Additional context**
[laravel-2019-08-08.log](https://github.com/nabeelio/phpvms/files/3482309/laravel-2019-08-08.log)

**Comment by arv187** [comment]
In case it was a data to take into account, my server uses php5.6 and the phpvms7 directory has this change in the htaccess to work with php7.2
`# Use php7.2
AddHandler application/x-httpd-ea-php72___lsphp .php .php72 .phtml .htm .html
AddType application/x-httpd-ea-php72___lsphp .php .htm .html .shtml`

**Comment by nabeelio** [comment]
Please try the latest dev

**Comment by arv187** [comment]
[2019-08-08 20:25:03] prod.ERROR: Error reading METAR: Trying to get property 'raw_text' of non-object

**Comment by arv187** [comment]
P.D: permissions table is populated

**Comment by nabeelio** [comment]
What airport?

**Comment by arv187** [comment]
There was no airport, after installing

**Comment by nabeelio** [comment]
Give the latest dev a shot. That bug was a total brain fart.

**Comment by arv187** [comment]
It seems that everything is correct now, the log only shows INFO, no errors.
`[2019-08-08 21:56:01] prod.INFO: Update - migration paths {"core":"/home/argavirt/public_html/phpvms7/app/Database/migrations"} 
[2019-08-08 21:56:01] prod.INFO: Migrations available:  
[2019-08-08 21:56:01] prod.INFO: Update - migration paths {"core":"/home/argavirt/public_html/phpvms7/app/Database/migrations"} 
[2019-08-08 21:56:01] prod.INFO: Migrations available:  `
