### ISSUE TITLE
front-end template

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#4]
need something goodie using bootstrap, with widgets, etc.

**Comment by codethirteen** [comment]
Perhaps consider a JS framework to do the heavy lifting on the front-end. Here's a Laravel integration library for React.js: https://github.com/talyssonoc/react-laravel 

It _will_ increase the learning curve for new theme developers, but on the other hand there's quite a few free react themes floating around that can quickly be adapted.

**Comment by nabeelio** [comment]
I was thinking about doing that, but decided against it, simply because of the learning curve, not only for any theme devs, but also for me. Regardless, the API endpoints will be there for whoever wants to do that, though
