### ISSUE TITLE
Distance lookup needs bcmath extension

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#407]
Look it up in geo lib

**Comment by nabeelio** [comment]
@ProAviaAZ were you seeing this?

**Comment by ProAviaAZ** [comment]
@nabeelio - Yes, while helping someone else input schedules on their host. When clicking save, a message near the top said something about the bcmath extension wasn't enabled. I checked his phpinfo and bcmath was off. That's the only place I have seen it. On any other installs I have done, bcmath has been enabled already.

**Comment by ProAviaAZ** [comment]
I don't even remember who's site it was. This occurred over 5 weeks ago. If I remember, I'll let you know.

Only other option would be to set bcmath to off on your hosting and check it there.

**Comment by nabeelio** [comment]
I will close this for now since I can't duplicate it. I don't have bcmath installed and it's not showing up. If we can duplicate it then we can reopen, is that ok?
