### ISSUE TITLE
Allow typing in drop down menus

### ISSUE THREAD

**Issue by ProAviaAZ** [nabeelio/phpvms#409]
When adding a flight - allow typing in drop downs. This would allow typing 'P' in the flight type box for 'Passenger'. And in airport drop down - typing KPHX would select KPHX - Phoenix Skyharbor.

This would allow user to use tab key to move between fields and not need to use mouse to select item from drop down - at least in most cases.

There are probably other menus that may benefit from this also. We had this in prior versions.

**Comment by nabeelio** [comment]
Is this on the flight page? Because it does allow it right now:

![image](https://user-images.githubusercontent.com/99736/65990349-66d57c00-e459-11e9-8d7a-14e749a05a92.png)

**Comment by ProAviaAZ** [comment]
On the Add flight page - I select airline, press Tab key, enter flight number, tab to Flight Type and pressing a letter (p) won't open the drop-down or select Passenger. If I continue to tab to Departure Airport, pressing a letter doesn't open that drop-down either. 

What does work is pressing Enter after tabbing to a drop-down. Then typing or using up/down arrows to navigate the available options.

Previous versions you could just start typing once you tabbed to a drop-down. This version you need to use the enter key first - which will work too.

**Comment by nabeelio** [comment]
What browser and all that?

**Comment by ProAviaAZ** [comment]
Latest Chrome on Win7-64
