### ISSUE TITLE
Add Subfleet, Custom Fields and Fares during initial schedule entry

### ISSUE THREAD

**Issue by ProAviaAZ** [nabeelio/phpvms#410]
Would it be possible to allow adding of subfleet, custom fields and fares during initial entry of route data when manually adding a flight (or at least subfleet and fares)?

As it is now, the route needs to be saved and then edited to allow this.

**Comment by nabeelio** [comment]
I can't because of the way the page is setup (the calls to add etc are done immediately). But would it help to go directly to the edit page after adding it? I think there's another page that does that right now, I can't remember.

**Comment by ProAviaAZ** [comment]
Yes, going to the edit page immediately may help. Or have a note on the Add Flight page to remind to add/edit the subfleet, fare, etc.

**Comment by nabeelio** [comment]
Hmm I just checked the code, it should be forwarding, what's the behavior you're seeing?

**Comment by ProAviaAZ** [comment]
After adding a flight it forward to the flight edit page. Just need to scroll down to add subfleet, etc. - so working as you intended. Guess I'm just used to seeing it all on one page when adding a flight.
