### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by vezza** [nabeelio/phpvms#411]
**Describe the bug**
I'm trying to install the latest beta version (7.0.0) but as soon as I click "Head to the installer" I get the 404 Not Found Error page and the following message:
Not Found
The requested URL was not found on this server.
**Version**
7.0.0 (beta)

**To Reproduce**
1. Go to 'home page'
2. Click on 'Head to the installer'
3. See error: 404 Not found - Not Found - The requested URL was not found on this server.

**Expected behavior**
when you click 'Head to the installer' I'm expecting the installer page

**Screenshots**

**Additional context**

**Comment by nabeelio** [comment]
Hi Vezza. Can you try the latest dev build from this link? http://downloads.phpvms.net/phpvms-7.0.0-dev.tar.gz

What web server are you using?

**Comment by vezza** [comment]
Same error... My web server is a Apache 2.4.41 on Fedora 30 x86_64 linux system. It seems to me that the install folder is missing inside the package...

**Comment by nabeelio** [comment]
It's not missing, it uses mod_rewrite to rewrite the URLs... is Apache configured to use/parse `.htaccess` files?

**Comment by nabeelio** [comment]
So this seems to be working on an Apache/cPanel install:
https://vmsdemo.space/install

Make sure the directory you're pointing to for Apache is the public/ folder, not the root phpVMS folder.

**Comment by nabeelio** [comment]
Actually I'm seeing some issues with loading assets. The easiest is just to point to `/path/to/phpvms/public` as the directory root.

**Comment by cyrussutaria** [comment]
Hi, Which is the last known good version which can be safely deployed on a live server?

**Comment by nabeelio** [comment]
The dev version I linked to above

**Comment by nabeelio** [comment]
BTW it hasn't been released yet, so I wouldn't use it for an active VA. I'm hoping to get this into a 2nd beta and released soon

**Comment by cyrussutaria** [comment]
Thanks. There is definitely room for fixing the install process or the documentation. I have been scratching my head for the last two days trying to set it up, but just cant seem to wrap my head around it. I have it installed in a folder called phpvms. My (sub) domain used for testing is pointing to the /phpvms/public folder. When i launch the site, it goes to the page which says "phpVMS Not Installed" I hit the "Head on to the Installer" button and then i get :
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
However, if I access it as <sitename>/index.php/install it proceeds but with no style and supporting assets etc loaded. 
So i'm not sure what is happening. Any guidance will be appreciated.

**Comment by ProAviaAZ** [comment]
@cyrussutaria - what version of php? I had the same issue with php 7.2.21. After host updated to php 7.2.22 the issue was resolved. Not sure if it was the php version or that the host had mis-configured that php version somehow. Different releases of phpVMS v7 didn't matter.

**Comment by cyrussutaria** [comment]
~$ php -v
PHP 4.4.9 (cgi-fcgi) (built: Aug 29 2019 12:59:15)
~$ php7.3-cli -v
PHP 7.3.10 (cli) (built: Oct  1 2019 07:20:21) ( NTS )

**Comment by nabeelio** [comment]
> PHP 4.4.9 (cgi-fcgi) (built: Aug 29 2019 12:59:15)

Yikes. Is the site using PHP 7.1 or higher? You can control that in cpanel

**Comment by cyrussutaria** [comment]
That is the CLI version. phpinfo would show 7.3. I fixed the alias now. But same problem. 
~/phpvms$ php -v
PHP 7.3.10 (cgi-fcgi) (built: Oct  1 2019 07:21:12)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies

Host is pointing to phpvms/public directory

**Comment by nabeelio** [comment]
I don't think it's related to the PHP versions, is likely that Apache isn't
reading the htaccess file. Any errors in the logs? Without that is going to
be difficult to debug.

**Comment by cyrussutaria** [comment]
Hi, it was an error related to initial htaccess file. fixed with a simple / 
Thanks

**Comment by nabeelio** [comment]
Do you know what exactly you changed, for future reference? Thanks!

**Comment by cyrussutaria** [comment]
RewriteRule ^ index.php [L]
had to be changed to 
RewriteRule ^ /index.php [L]

Funny, but it worked.
