### ISSUE TITLE
Allow logo upload for airline

### ISSUE THREAD

**Issue by bbuske** [nabeelio/phpvms#417]
**Describe the bug**
As requested via Discord: You can enter logos for the airlines when you create / edit them. However, these logos are not visible in the front end, like at the flight page. 

**Version**
7.0.0 including the latest dev release. 

**To Reproduce**
Try to add a logo locally and add a link to it or link to one from an external source like Wikipedia. The logo will not show up. 

**Expected behavior**
After adding a link to the logo, external or local, the logo of the airline should show up at the flights page and on other places. 

Cheers

**Comment by nabeelio** [comment]
Marking this as post-beta. I'm going to come back to this and probably have a logo upload or something like that, and then show it on that page like you said. I guess I just had a logo link there in-case someone wanted to use it in their template

**Comment by nabeelio** [comment]
And should it be an icon-sized thing? What do you invision for this?

**Comment by bbuske** [comment]
Well just airline logos in searches for flights and other listings, where it is mentioned... something like this:
![image](https://user-images.githubusercontent.com/24304433/67899111-fdb85580-fb37-11e9-9063-d657ab42daac.png)

**Comment by nabeelio** [comment]
So allow any size, etc?

**Comment by voipmeister** [comment]
I'd restrict this to 180x40px, which seems a reasonable value. It would be nice if the upload function would preserve the aspect ratio and pad any open space that is left.

**Comment by voipmeister** [comment]
On second thought, it might be wise to have a large version (say 360x80) and a smaller version, so upload at least 360x80 px image and save it twice.
Would be nice to be able to use either version in the code (smaller version in tables for example).

**Comment by bbuske** [comment]
Yes. You can always use CSS to scale the image. 180 x 40 or 180x50 is a great size for the schedules and flight lists. On the detailed list maybe bigger logos should be used. 

The question here is where logos should come up in general? So far with VAs I have been looking at, the logos were only visible in the schedule... but nowhere else.

**Comment by nabeelio** [comment]
Following up on this - do you guys want a logo upload, or is that link to the logo ok?

**Comment by nabeelio** [comment]
@voipmeister @bbuske Following up on this - do you guys want a logo upload, or is that link to the logo ok?
