### ISSUE TITLE
CSS Love needed for the Flights Page 

### ISSUE THREAD

**Issue by bbuske** [nabeelio/phpvms#418]
**Describe the bug**
The Flight page for pilots needs some CSS love. With the new release, the fields for arrival and departure are moving outside of their box. Also the Show Bids field is barely visible as it is. It should be a button. 

**Version**
7.0.0 latest Developer Release but prior releases also need the Show Bids field changed. The Arrival and Departure fields are fine though. 

**Expected behavior**
The search boxes for arrival and departure should have their padding / margin set so that they are remaining within their respective boxes. The Show Bids field on top should be better visible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24304433/67623535-57e1af80-f7f4-11e9-9c94-5a36f83d57b6.png)

**Comment by buske-it** [comment]
I have fixed the CSS issues. I wasn't able to attach the files though. The format is not supported...
Funny, that GitHub does not accept PHP files, being a platform for programmers... :P

**Comment by nabeelio** [comment]
Give this a looksie now

**Comment by bbuske** [comment]
Nice one! Seems to be fixed. 
Thanks!
