### ISSUE TITLE
Pireps page: 'Pending' doesn't show pending PIREPs

### ISSUE THREAD

**Issue by voipmeister** [nabeelio/phpvms#427]
**Describe the bug**
In the admin section of the site, the Pirep page doesn't filter on pending PIREPs.

**Version**
version 7.0.0 (build 191030.70d43e)

**To Reproduce**
1. Make sure there is a PIREP with a status of 'Pending'
2. Log in as admin in phpvms
3. Click on 'Pireps'
4. Click on 'Pending' in the top right corner.
5. See the Pending PIREP disappear

**Expected behavior**
The pending PIREP should still be shown.

**Screenshots**
Added.

**Additional context**
The URL shown is https://<site>/admin/pireps?search=status:0
I have tried with 1 and -1 as well, no change. Haven't looked at the code yet, sorry.

URL: https://<site>/admin/pireps 
Result:
<img width="1440" alt="Screenshot 2019-10-30 at 22 03 45" src="https://user-images.githubusercontent.com/12763807/67899153-fe65e180-fb61-11e9-8e2e-fd3acd711d4f.png">

URL: https://<site>/admin/pireps?search=status:0 (after clicking on Pending)
Result:
<img width="1440" alt="Screenshot 2019-10-30 at 22 10 28" src="https://user-images.githubusercontent.com/12763807/67899219-1fc6cd80-fb62-11e9-9ec7-aed2ad9f8bfa.png">

**Comment by nabeelio** [comment]
Hmm, that's strange, it seems to be showing up for me:

![image](https://user-images.githubusercontent.com/99736/68127291-90b01180-fee3-11e9-8509-e7ef96a1bc46.png)

Lemme investigate the code. It uses the Repository search functionality (https://github.com/andersao/l5-repository#example-the-criteria)

**Comment by nabeelio** [comment]
Is this still open?
