### ISSUE TITLE
proc_open workaround

### ISSUE THREAD

**Issue by rebal154** [nabeelio/phpvms#455]
Hi there, I am on shared hosting, and I do not have access to proc_open. I am using phpVMS 7, and this is the error I get:

`The Process class relies on proc_open, which is not available on your PHP installation.`

Could I bypass these dependencies somehow?

Thanks!

**Comment by nabeelio** [comment]
Hey, what were you doing when you got this error?

**Comment by rebal154** [comment]
I had just installed it, and had opened up my site to set it up

**Comment by nabeelio** [comment]
Can you attach the logs in `storage/logs`?

**Comment by rebal154** [comment]
[laravel-2019-12-05 (1).log](https://github.com/nabeelio/phpvms/files/3928373/laravel-2019-12-05.1.log)

Here it is

**Comment by nabeelio** [comment]
Is that the only file? I see a bunch of database errors. Did a `env.php` and `config.php` get created?

**Comment by rebal154** [comment]
No

**Comment by rebal154** [comment]
There are no other files in 'storage/logs' apart from '.gitignore'

**Comment by nabeelio** [comment]
Ok so an env.php and config.php didn't get created?

**Comment by rebal154** [comment]
<img width="1440" alt="Screenshot 2019-12-05 at 18 06 19" src="https://user-images.githubusercontent.com/58567591/70261279-02e96f80-178a-11ea-92a3-52eda82eb8b4.png">

Here is a screenshot if it helps of the error

**Comment by rebal154** [comment]
No

**Comment by nabeelio** [comment]
Interesting... which version is this? That error page looks pretty old.

**Comment by rebal154** [comment]
<img width="1440" alt="Screenshot 2019-12-05 at 18 07 32" src="https://user-images.githubusercontent.com/58567591/70261336-1e547a80-178a-11ea-965c-d93aebd99edf.png">

**Comment by rebal154** [comment]
How do I check?

**Comment by rebal154** [comment]
Ah in `VERSION` it says this: `7.0.0+191119.a335ed`

**Comment by rebal154** [comment]
> Interesting... which version is this? That error page looks pretty old.

Ok, I reinstalled it, I still get the same error. the version is: `7.0.0+191119.a335ed`

Here is the error log:

[laravel-2019-12-05 (2).log](https://github.com/nabeelio/phpvms/files/3928440/laravel-2019-12-05.2.log)

**Comment by rebal154** [comment]
All I did was download the ZIP file, upload to my website, and extracted it.

**Comment by nabeelio** [comment]
Which zip file? Dev or one of the beta versions?

**Comment by rebal154** [comment]
One of the beta versions: beta 2

**Comment by nabeelio** [comment]
Ok, lemme dig into it and see what's going on.

**Comment by nabeelio** [comment]
Who's your host?

**Comment by rebal154** [comment]
Ok thank you. My host is heliohost.org

**Comment by rebal154** [comment]
Ive asked heliohost whether they can add `proc_open` however they have said no due to security reasons. Any way around this?

**Comment by nabeelio** [comment]
I'm trying to figure out where `proc_open` is even being used

**Comment by nabeelio** [comment]
It looks like it's something in Laravel itself:

https://github.com/laravel/framework/issues/30054

**Comment by rebal154** [comment]
Ah i see. Should I use phpVMS 5, then, as it is not built on the Laravel framework?

**Comment by nabeelio** [comment]
Not yet, lets try this workaround someone put

**Comment by rebal154** [comment]
Ok, could you show me how to do it? I'm slightly confused

**Comment by rebal154** [comment]
Ok, what do I do with that?

**Comment by rebal154** [comment]
Do I add a file named flare.php?

**Comment by nabeelio** [comment]
Do you know how to work with git? You can checkout the branch, or, grab this file:

https://raw.githubusercontent.com/nabeelio/phpvms/a63e4d4e4480a302eccb7f53e5602d8af13731d9/config/flare.php

Place it in the `config` directory. You might have to delete everything in the `bootstrap/cache` folder if it doesn't do anything.

**Comment by rebal154** [comment]
Ok thanks, except now, I have this error:

`Illuminate\Database\QueryException
SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) (SQL: select `type`, `value` from `settings` where `id` = general_theme)
http://ifhub.heliohost.org/phpvms/`

**Comment by rebal154** [comment]
<img width="1440" alt="Screenshot 2019-12-05 at 19 13 52" src="https://user-images.githubusercontent.com/58567591/70265949-6330df00-1793-11ea-9edf-292c21579469.png">

**Comment by nabeelio** [comment]
Delete the `env.php` and `config.php` files and then try reinstalling. I think something else went wrong during the installer.

**Comment by rebal154** [comment]
ok

**Comment by rebal154** [comment]
Sorry, where are the `env.php` and the `config.php` files?

**Comment by rebal154** [comment]
And its definitely for this error, right?

<img width="1440" alt="Screenshot 2019-12-05 at 21 31 34" src="https://user-images.githubusercontent.com/58567591/70275755-b52f3000-17a6-11ea-81f4-0a91599aef79.png">

**Comment by nabeelio** [comment]
They'd be in the root of the install

**Comment by rebal154** [comment]
Ok thank you I'll try again

**Comment by rebal154** [comment]
And all I need to do is upload the files to my `public_html` folder and open up the website to run the installer? I dont need to setup any databases or anything?

**Comment by nabeelio** [comment]
You need to configure the database, like create it, and create the credentials. You'll need those when you run the installer. 

http://docs.phpvms.net/setup/installation

**Comment by rebal154** [comment]
Ok thank you. I'll let you know if I run into any other issues

**Comment by rebal154** [comment]
<img width="1440" alt="Screenshot 2019-12-05 at 21 50 07" src="https://user-images.githubusercontent.com/58567591/70276910-37205880-17a9-11ea-9da0-23fa169d925e.png">

Still getting this error!

Any help is (again) appreciated

**Comment by nabeelio** [comment]
When you start the installer, it should prompt you to enter your database credentials. If you enter them and click test, does that work?

**Comment by nabeelio** [comment]
I added a screenshot to the installer docs page on the MySQL Database Wizard in cPanel that you need to use.

**Comment by rebal154** [comment]
No that is what I get when I start the installer, it hasnt even asked my to enter database credentials yet!

**Comment by rebal154** [comment]
No that is what I get when I start the installer, it hasnt even asked my to enter database credentials yet!

**Comment by rebal154** [comment]
(as in I haven't seen the installer yet, I have just opened the website, and this is what I get)

**Comment by rebal154** [comment]
Dont worry, it works great with the latest dev release. Thanks for the help!
