### ISSUE TITLE
Two Virtual Airlines in one database

### ISSUE THREAD

**Issue by NevaPortal** [nabeelio/phpvms#472]
Hello,

I want to have option in settings page show routes, pilots start with some Icao code.
Example;
I have 2 virtual airlines but i want to have one database. One airlines AAL other is DAL
in AAL website i want to see only AAL pilots and pilots can see only route starts with AAL and DAL website i want to see DAL pilots and pilots can see only routse start with DAL... Is it possible to do it?

**Comment by nabeelio** [comment]
It's not possible now, but this is something I can potentially look at for 7.1 as an option

**Comment by NevaPortal** [comment]
Ok thanks. This would help a lot to want to have multiple virtual airline owners.

**Comment by vgpastor** [comment]
I think that it's better use two differents installations for this propose.

**Comment by FatihKoz** [comment]
Isn't this already possible ? By using different database prefixes you can have two different installations in the same database.

For example;

**myairlines.com/aal** is the first airlines root folder , during setup select your database , change the **prefix to aal_** , cotinue setup and finish.

**myairlines.com/dal** is the second airlines root folder , during setup select your database , change the **prefix to dal_** , cotinue setup and finish.

You can use two different subdomains or two different domains as you wish like (aal.myairlinegroup.com and dal.myairlinegroup.com, or aalvirtual.com and dalvirtual.com if your hosting provider allows this) but you will have one database.

You will have two completely different setups in the same database ... Only negative side affect of this setup is you will have two different admin sections, meaning that you will have to manage two different airlines.

Also if you want to have multiple airlines in one setup but restrict users to the airline they selected, this is still possible via current options in the admin manel (restrict the flights to company) ... Users will see the flights of their airline and will be able to select that airlines fleets for flights. Only side affect of this that your user lists (aka pilots) will show all pilots by default but this can be easily changed and the pilots table can be adjusted to display only the pilots of an airline too.

Admins may see all the pilots, but a pilot of aal will see only the pilots of aal while a pilot from dal will see only the pilots of dal. (Just a little code improvement at users/table.blade will do the trick)
