### ISSUE TITLE
Flights CSV import fails if no distance stipulated

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#478]
Import of Flights fails if no distance value is stipulated.
Given this is marked as a non required field, this seems like a bug

Valid Work around: enter a value of 0.

NOTE: Distance is not automatically calculated if value is 0.

**Comment by nabeelio** [comment]
Is the field in the CSV being omitted or just blank?

**Comment by ANA-Haruka** [comment]
blank

**Comment by nabeelio** [comment]
Should be fixed in latest dev
