### ISSUE TITLE
Fatal Error in subfleet page when importing routes with new aircraft

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#479]
Facade\Ignition\Exceptions\ViewException
Trying to get property 'name' of non-object (View: /resources/views/admin/subfleets/table.blade.php)

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
:18
resources/views/admin/subfleets/table.blade.php:18

                <a href="{{ route('admin.aircraft.index') }}?subfleet={{$subfleet->id}}">

                {{ $subfleet->name }}

                </a>

            </td>

            **<td>{{ $subfleet->airline->name }}</td>**

            <td>{{ $subfleet->type }}</td>

            <td>{{ $subfleet->aircraft->count() }}</td>

            <td class="text-right">

                {{ Form::open(['route' => ['admin.subfleets.destroy', $subfleet->id], 'method' => 'delete']) }}

This occurs in the dev version

Steps to replicate:
Import a route which contains a subfleet type that has not previously been added, the system will automatically add the subfleet type however the airline name property will be missing, causing this error.

**Comment by ANA-Haruka** [comment]
Looks like this is trying to access an object when its actually an array, fixed by modifying the line:
<td>{{ $subfleet->airline->name }}</td>
to
<td>{{ $subfleet->airline['name'] }}</td>

**Comment by nabeelio** [comment]
Hmm, do you have a CSV which breaks it? It looks like the subfleet isn't being assigned properly to an airline (either it doesn't exist or something0. I'm not sure why `$subfleet->airline['name']` would work but not `->name`, since the array access isn't actually proper

**Comment by ANA-Haruka** [comment]
I do, but I think it should be easily replicable without such large CSVs as youd need to add subfleet and airport CSVs before my flights CSV can even replicate this.

Basically here is how I would replicate:
create an airline code JJP, create one subfleet A320, ensure subfleet A321 does not exist.
import the attached flights CSV.
[flightsFinalEK.zip](https://github.com/nabeelio/phpvms/files/4000547/flightsFinalEK.zip)

**Comment by nabeelio** [comment]
This test sort of covers that, I should be able to add and duplicate it from here: https://github.com/nabeelio/phpvms/blob/dev/tests/ImporterTest.php#L463
