### ISSUE TITLE
Pilots cannot use the dashboard or flights without admin rights

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#480]
Pilots are unable to see any of the functional aspects of the vms, including access the dashboard or flight search unless the role admin is assigned.

I tested creating a new role with no special permissions, same result.
I tested creating a new role with all permissions, same result.

it appears only the admin role has been given permission to see these pages.

**Comment by nabeelio** [comment]
Do you mean within the admin or the frontend of the site?

**Comment by ANA-Haruka** [comment]
front end, wouldnt be expected non admins to access admin

**Comment by nabeelio** [comment]
Is this a new user, just with no roles assigned? It seems like the base "user" role isn't being assigned maybe

**Comment by ANA-Haruka** [comment]
there is no base "user" role. by default role is blank, if I save from admin under this condition, it will error out:
```
ErrorException
Invalid argument supplied for foreach()
```
```
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
:247
app/Http/Controllers/Admin/UserController.php:247

```
To sidestep this I created a Role "pilot" with no special rights, however this role cannot see the dashboard. giving the role all the rights does not resolve the issue.

**Comment by nabeelio** [comment]
Is it still an issue in the latest dev? I'll look at the foreach one in a
few

**Comment by ANA-Haruka** [comment]
Tested on both Beta 2 and latest dev branch

**Comment by nabeelio** [comment]
But on the latest dev, can they get to the dashboard/flights? That should be working, I fixed that in the routes file

**Comment by ANA-Haruka** [comment]
They cannot

**Comment by nabeelio** [comment]
Please re-open if this is a problem still.

**Comment by afr1098** [comment]
Hello,

I confirm the bug has not been corrected

**Comment by nabeelio** [comment]
Can you give me exact instructions on how to duplicate this? I haven't been able to.

**Comment by NevaPortal** [comment]
I add regular user now and he can use dashboard without any problem.
