### ISSUE TITLE
Default Theme unusable on Mobile

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#485]
Currently the main navbar elements are impossible to access on a mobile browser, making the default theme completely inaccessible in mobile.

**Comment by nabeelio** [comment]
https://forum.phpvms.net/topic/26735-toggle-drop-down-menu/?tab=comments#comment-136817

**Comment by elcapitan787** [comment]
Fix was for Beta 1, Confirmed Unusable in Beta 2 with new Drop Down, Fix would work if returned to original CSS.

**Comment by nabeelio** [comment]
Please give the latest dev branch a shot. Some pages need some work on mobile, but overall it should be working.

I need to do the same fix for the admin
