### ISSUE TITLE
Status not changing when importing CSV for aircraft

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#486]
When importing a CSV containing existing aircraft, the Status attribute is not being updated.

For example, if you have a fleet of 738s, and you change the status from "A" to "S" for a large chunk of aircraft, the status will remain as A

**Comment by nabeelio** [comment]
This looks like it affect multiple imports

**Comment by nabeelio** [comment]
Should be fixed now in latest dev.
