### ISSUE TITLE
Pilot Pay route modifier

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#487]
Just as there is a way to change the rate of pay for pilots per subfleet, there should be a way to change the pay rate for each route. 

Sometimes, airlines will want to give incentives to fly certain shorter routes, currently it seems there is no way to change the rate of pay for a route, only for an aircraft.

**Comment by nabeelio** [comment]
@ANA-Haruka did you want this to be regardless of rank, like a fixed rate?
