### ISSUE TITLE
Fares assigned to flights not working/overwritten by Subfleet

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#488]
Fares are usually derived from a route, not from the aircraft operated within that route. While some airlines may charge a small premium to, say, fly the wide body or superjumbo flight from kjfk-egll, its safe to say that route has a somewhat standard price that is slightly modified by the aircraft chosen.

Currently it seems the value of the fare placed in the subfleet overrules the value assigned to the flight. it also seems to be impossible to assign fares to a route that has fares attached to it, if the aircraft does not.

**Comment by nabeelio** [comment]
This was done to simplify things, since a lot of airlines have hundreds of flights, but there is flexibility to derive from fares, or set fixed amounts. This does seem like a bug. 

http://docs.phpvms.net/concepts/finances

Does the wording make sense in the above docs?

**Comment by ANA-Haruka** [comment]
It makes sense.

**Comment by nabeelio** [comment]
Merged this into dev, lemme know how it looks

**Comment by nabeelio** [comment]
You can reopen this if it's still broken, I just want to close it so I have a clearer view
