### ISSUE TITLE
Installation Error step2

### ISSUE THREAD

**Issue by HabubException** [nabeelio/phpvms#491]
If i enter the Database Credentials and click on check its says its ok but if i click on next the page reloads and nothing happends.. i get this error erverytime and cannot to anything on this site.

Here is a demonstration Video: https://www.youtube.com/watch?v=ql-a2UTrlic&feature=youtu.be

Website for testing: 
http://HeldAir-Virtual.eu

**Comment by HabubException** [comment]
Here is a demonstration Video: https://www.youtube.com/watch?v=ql-a2UTrlic&feature=youtu.be

**Comment by joooseb** [comment]
I had the same error, do you have a ssh connection throw your server?

solved clearing cache and config with artisan and reload apache service (Ubuntu 19.10)

php artisan config:clear

php artisan cache:clear

sudo service apache2 reload

**Comment by joooseb** [comment]
If you don't have a way to connect throw ssh I can give you a php script to run artisan commands

**Comment by HabubException** [comment]
It didn't fixed it🙄

**Comment by nabeelio** [comment]
Can you attach the `storage/logs/laravel.log` (or the one for the correct date) and just make sure there's no passwords in it?

**Comment by HabubException** [comment]
https://pastebin.com/9Y0KSkHj

**Comment by nabeelio** [comment]
Thanks, this is super helpful. Is this the latest beta or dev version?

**Comment by HabubException** [comment]
This is the newest version from github

**Comment by nabeelio** [comment]
Hmm, do you have the full log? I think there's some stuff missing. I'm trying to duplicate it, but can't. I see the error but can't quite trace why/where it's coming from

**Comment by nabeelio** [comment]
And can you try this branch: `491-Installation-Errors`? From the above PR

**Comment by HabubException** [comment]
this is the full log from /storage/logs

**Comment by nabeelio** [comment]
Hmm interesting. Have you been able to try that branch above?

**Comment by HabubException** [comment]
I don't know what you mean with this

**Comment by nabeelio** [comment]
Are you testing the dev branch directly or just the latest beta?

**Comment by nabeelio** [comment]
Try the latest dev, I've merged in what I think the fix would need to be, at least according to the logs.

**Comment by HabubException** [comment]
After uploading what command do I have to execute?

**Comment by nabeelio** [comment]
No commands, just try what you were trying before

**Comment by HabubException** [comment]
I have to do something because now the error comes with vendor

Warning: require(/var/www/html/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bootstrap/autoload.php on line 17

Fatal erro

**Comment by nabeelio** [comment]
Sorry, you need to then run `composer install`.  Or use this download, which already has all of the dependencies packaged up:

http://downloads.phpvms.net/phpvms-7.0.0-dev.tar.gz

**Comment by HabubException** [comment]
Didnt work :/

**Comment by nabeelio** [comment]
What didn't? Is it just redirecting back to the form again?

**Comment by HabubException** [comment]
yes same problem as before

**Comment by nabeelio** [comment]
Can you post the logs? There should be a line that starts with `"Error on db setup: "`, before it redirects you back

**Comment by HabubException** [comment]
[2020-01-14 19:28:08] prod.ERROR: Error on db setup: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'heldair.users' doesn't exist (SQL: UPDATE `users` SET `pilot_id`=`id`)

**Comment by nabeelio** [comment]
Can you post the entire log? And do you have Discord? Can you message me?

**Comment by HabubException** [comment]
Yes

**Comment by HabubException** [comment]
https://pastebin.com/t67pmdum

**Comment by HabubException** [comment]
Here is the entire log: https://pastebin.com/t67pmdum

You can add me or i can add you
My Tag: FBI#6884

**Comment by nabeelio** [comment]
In the root, do you have `config.php` and `env.php` files? Can you delete the both of those and retry? In the logs, it looks like the credentials aren't there. Also, delete you database and recreate it from scratch. Thanks!

**Comment by HabubException** [comment]
The two files are not even created (html folder is 777 and owner is www-data)

**Comment by nabeelio** [comment]
Contact me on Discord, please

**Comment by nabeelio** [comment]
https://discord.gg/2GWt84Q

**Comment by nabeelio** [comment]
Error was with permissions, closing.
