### ISSUE TITLE
Pirep not in KG

### ISSUE THREAD

**Issue by chris1971nrw** [nabeelio/phpvms#493]
I have phpVMS 7 values in kg for fuel , but Manuel Pirep Formular has lbs on Input box.

**Comment by ANA-Haruka** [comment]
I can confirm this bug is present in latest dev version, this is of course after setting the units to kilo

**Comment by nabeelio** [comment]
Please check the latest dev

**Comment by PhotographyFlow** [comment]
Looks like still not fixed in 7.0.4
