### ISSUE TITLE
Installation error with external databases

### ISSUE THREAD

**Issue by joooseb** [nabeelio/phpvms#494]
**Describe the bug**
There is not a way to configure external databases from installer, so Laravel throw an error trying to get a field "default theme from setting" in SQL database.
The unique way to avoid the error is configuring the external database parameters into laravel config file (because there's not a .env with configs). But new error appear (404 not found)... no way to run installer.

**Version**
7.0.0-beta.2

**To Reproduce**
1. Go to phpvms url
2. See error

**Expected behavior**
Installer views and logic.

**Example**:
http://www.dutchairwaysva.com/phpvms

**Comment by nabeelio** [comment]
I wonder if this is related to #491. But I'm not 100% what you mean, if you enter the hostname and port properly, it should just work. Is the remote port open? 

Trying to go to: http://www.dutchairwaysva.com/phpvms/install

It looks like URL rewrite isn't configured

**Comment by joooseb** [comment]
No, isn't related to these issue, remote port is open and credentials in config/database.php has been entered properly. I will look the url rewrite, could it be the error there and laravel log file too.

**Comment by nabeelio** [comment]
Yeah, I was gonna ask for the Laravel log next. There's nothing that I'm aware of that should block a remote DB - that's how I test it infact, with the included docker-compose file - the database is running in a separate container, and it connects to it through its hostname

**Comment by web541** [comment]
Not sure if this helps, but it looks like it could be a URL rewrite issue as the installer can be viewed by adding the /public to the end which you shouldn't have to do now.

[http://www.dutchairwaysva.com/phpvms/public/install](http://www.dutchairwaysva.com/phpvms/public/install)

**Comment by joooseb** [comment]
> Not sure if this helps, but it looks like it could be a URL rewrite issue as the installer can be viewed by adding the /public to the end which you shouldn't have to do now.
> 
> http://www.dutchairwaysva.com/phpvms/public/install

it works, but I changed the url setting in index.php to public/ and no lucky and in boostratp/app.php changed to phpvms/public and no lucky too with http://www.dutchairwaysva.com/phpvms/install but now the styles load correctly

**Comment by nabeelio** [comment]
Who's your host?

**Comment by nabeelio** [comment]
Can you try this, if you're on Apache: https://github.com/nabeelio/phpvms/issues/411#issuecomment-566176924

**Comment by nabeelio** [comment]
I'm going to close this for now. Also, I'm going to put a note on the docs that running phpVMS in a subfolder isn't going to work very well, especially under cPanel. The best way is to create a subdomain, and have that point to the `/public` folder. I'll create instructions on the docs site for this.
