### ISSUE TITLE
Error 500 when trying to access Dashboard.

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#498]
I have been running the latest dev branch of phpvms, last few days as I get more and more PIREPS in there seem to be increasing errors in the laravel logs. 
These mostly appear to be failures on GeoService.php and seem to relate to waypoints in pireps,
I can grant you access to the server if you want to see the specific logs or send the file via email.

Currently Dashboard cannot be accessed and gives a 500 error (pilot side, admin is fine)

**Comment by nabeelio** [comment]
Gonna need the logs, esp for the GeoService errors.

I'm going to revert a change on the vacentral side of things too, that should help with some errors.

**Comment by ANA-Haruka** [comment]
Whats the easiest way to send you the logs? its like 14mb

**Comment by nabeelio** [comment]
If you tar/zip it, you can attach it to a comment here. Or send it over
discord

**Comment by ANA-Haruka** [comment]
whats discord address?

**Comment by ANA-Haruka** [comment]
[laravel-2020-01-14.zip](https://github.com/nabeelio/phpvms/files/4065088/laravel-2020-01-14.zip)

**Comment by nabeelio** [comment]
https://discord.gg/wvAmMnd

**Comment by nabeelio** [comment]
I see the GeoService errors, which page is this on that you're trying to access?

**Comment by nabeelio** [comment]
Or, can you give me steps to duplicate? I'm trying to replicate it on https://demo.phpvms.net (login is admin@phpvms.net/admin)

**Comment by ANA-Haruka** [comment]
basically the Dashboard is the one that is not loading anymore

**Comment by nabeelio** [comment]
Ok, delete the logs, and then load the latest dev version: http://downloads.phpvms.net/phpvms-7.0.0-dev.tar.gz

The GeoService error should go away, and then hopefully only the dashboard error will show up, then upload those logs if you can

**Comment by nabeelio** [comment]
I think this is fixed now?
