### ISSUE TITLE
Null-able fuel values on PIREP

### ISSUE THREAD

**Issue by ANA-Haruka** [nabeelio/phpvms#510]
Currently the fuel values are required. 
For some airlines tracking fuel expenditure is not part of their operations and therefore such values are irrelevant.
/
The system currently supports an input of 0, could we just assume if null then = 0 so we can simplify this process for airlines that dont care and therefore render that field optional?

**Comment by nabeelio** [comment]
Makes sense, that's actually optional on the API too.
