### ISSUE TITLE
Storage folders, etc, still visible in /public mode (.htaccess doesn't block)

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#511]
- Subfolders in storage, etc, are not blocked (testing on http://vmsdemo.space)
- Happens when put into subfolder (e.,g https://vmsdemo.space/subfolder)

refs #411

**Comment by nabeelio** [comment]
Can't duplicate this, so it could be down to how a host's cpanel is setup.

**Comment by barf** [comment]
Unable to reproduce this, and have phpVMS git master installed in a subdir here. The rewrite rules in `public/.htaccess` need modifying to work in a subdirectory:

```# Disable index view
Options -Indexes

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /phpVMS/$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ /phpVMS/index.php [L]
</IfModule>
```

**Comment by nabeelio** [comment]
Thanks, I might include that in the docs... "officially" I'm not supporting subdirectory installs, mainly because Laravel doesn't behave well with it.

**Comment by YashGovekar** [comment]
Alright, let me start from the oldest bug.
I would like to solve it @nabeelio

**Comment by nabeelio** [comment]
@YashGovekar actually this one I can close, it seems to be fixed
