### ISSUE TITLE
Cron Job

### ISSUE THREAD

**Issue by NevaPortal** [nabeelio/phpvms#553]
When i add cron job for [https://prnt.sc/r2hmw0](url)
from webmin i get this error [https://prnt.sc/r2hmbc](url)
i add cron job with root user and still get same problem. My other cron jobs works well.

**Comment by nabeelio** [comment]
What's the PHP command you use for the other cron jobs? That command might be wrong. Is this a shared host or your own?

**Comment by NevaPortal** [comment]
Examples
`/etc/webmin/virtualmin-awstats/awstats.pl mydomain.com`
`php-cgi -f /home/nevact/domains/mydomain.com/public_html/index.php a=CLI ng=console/5069397886 >/dev/null 2>&1`

**Comment by nabeelio** [comment]
I think you need to contact your host about that, I'm not sure why it would
be giving a permission denied. It could be the the PHP executable doesn't
have the right permissions

**Comment by NevaPortal** [comment]
Ok i will contact with them tomorrow. I was trying with root user but let's see what they will say tomorrow...

**Comment by nabeelio** [comment]
Let me know what they say. I'm guessing it's the wrong executable

**Comment by NevaPortal** [comment]
Ok. I talked with them and they said was my fault that i add the cron job wrong way and they fixed for me. Now cron job working well. But i still have that warning [https://prnt.sc/r3gzxb](url) so didn't disappear.

**Comment by nabeelio** [comment]
What should the cron have looked like? Lemme look at the warning message.
Is there a storage/logs/cron.log file? Can you attach that? If it doesn't
exist it means there's a chance the cron isn't actually running

**Comment by NevaPortal** [comment]
Dosen't  exist. But when i run cron job manually i see this [https://prnt.sc/r3jozi](url)

**Comment by nabeelio** [comment]
Can you remove the > and everything after it and run it again?

>

**Comment by NevaPortal** [comment]
This is what i get [https://prnt.sc/r3l3y4](url)

**Comment by nabeelio** [comment]
Are there two dots at the end of the command?

>

**Comment by NevaPortal** [comment]
No. Which dots? Sorry i am not to good with cron commands.
Here is the full command change the way you like and i'll run it again.
`cd /home/ottomanva/public_html && /usr/bin/php-cgi7.2 artisan schedule:run >> /dev/null 2>&1`

**Comment by nabeelio** [comment]
Run just this, without any spaces:

```
cd /home/ottomanva/public_html && /usr/bin/php-cgi7.2 artisan schedule:run
```

**Comment by NevaPortal** [comment]
No i tried this before and now get the same 
`PHP Notice:  Undefined index: argv in /home/ottomanva/public_html/vendor/symfony/console/Input/ArgvInput.php on line 52
PHP Warning:  array_shift() expects parameter 1 to be array, null given in /home/ottomanva/public_html/vendor/symfony/console/Input/ArgvInput.php on line 56

In ArgvInput.php line 246:
                                           
  Invalid argument supplied for foreach()  
                                           

Content-type: text/html; charset=UTF-8`

**Comment by nabeelio** [comment]
That's very strange, it's like extra arguments are getting added somewhere. Can you contact your host again?

**Comment by nabeelio** [comment]
That looks like it's being run with the php-cgi executable, it needs to be run with php-cli. Can they give you the path to that?

**Comment by nabeelio** [comment]
And try this command:

```
cd /home/ottomanva/public_html && /usr/bin/php-cgi7.2  -d register_argc_argv=On artisan schedule:run
```

**Comment by NevaPortal** [comment]
It worked.

**Comment by nabeelio** [comment]
That's ok, that output is normal. Was that with the command above?

**Comment by nabeelio** [comment]
That's ok, that output is normal. Was that with the command above?

**Comment by NevaPortal** [comment]
Sorry i am late to answer. Yes with the command above.

**Comment by FroztIkon** [comment]
Fresh install of phpvms 7 beta 3,  

`cd /home/gridexva/public_html && /usr/bin/php-cgi7.2 -d register_argc_argv=On artisan schedule:run >> /dev/null 2>&1`

solved a similar issue.

**Comment by nabeelio** [comment]
Sounds good. I have to add a note there that it's a suggested command, it's hard to detect the exact executable to use and you have to ask your host for which to specifically to use.
