### ISSUE TITLE
I can't change Current Theme

### ISSUE THREAD

**Issue by NevaPortal** [nabeelio/phpvms#554]
I add new theme resources/views/layouts
From admin panel settings tab i don't see new theme.

**Comment by nabeelio** [comment]
How did you add a new theme? Is there a `theme.json` file in it and the `name` is different?

**Comment by NevaPortal** [comment]
I just copy the default them folder and rename the folder.

**Comment by NevaPortal** [comment]
I've changed the name in `theme.json` but still the same.
