### ISSUE TITLE
Error while creating database

### ISSUE THREAD

**Issue by yashris** [nabeelio/phpvms#56]
$ php artisan database:create
Using connection "local"
Running "sqlite3 C:\xampp\htdocs\phpvms\database\testing.sqlite """

  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "sqlite3 C:\xampp\htdocs\phpvms\database\testing.sqlite """ fai
  led.
  Exit Code: 1(General error)
  Working directory: C:\xampp\htdocs\phpvms
  Output:
  ================
  Error Output:
  ================
  'sqlite3' is not recognized as an internal or external command,
  operable program or batch file.

I am getting this error when I bash php artisan database:create

**Comment by nabeelio** [comment]
You need to install sqlite3
