### ISSUE TITLE
Pilot Profile Page Error

### ISSUE THREAD

**Issue by NevaPortal** [nabeelio/phpvms#560]
`Facade\Ignition\Exceptions\ViewException
Undefined variable: acars (View: /home/ottomanva/public_html/resources/views/layouts/default/profile/index.blade.php)
http://www.ottomanva.com/profile/1`

[https://prnt.sc/r54ad7](url)

**Comment by nabeelio** [comment]
Hmm this is a weird one

**Comment by FroztIkon** [comment]
Is this fixed?

**Comment by nabeelio** [comment]
In the latest dev version it is.
