### ISSUE TITLE
Map Center Coords

### ISSUE THREAD

**Issue by NevaPortal** [nabeelio/phpvms#566]
When you change the coords you get error - https://prnt.sc/r5moz0
```
UnexpectedValueException
The stream or file "/home/ottomanva/public_html/storage/logs/laravel-2020-02-21.log" could not be opened: failed to open stream: Permission denied
```
`Monolog\Handler\StreamHandler::write
:110
vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110

        if (!is_resource($this->stream)) {

            if (null === $this->url || '' === $this->url) {

                throw new \LogicException('Missing stream url, the stream can not be opened. This may be caused by a premature call to close().');

            }

            $this->createDir();

            $this->errorMessage = null;

            set_error_handler([$this, 'customErrorHandler']);

            $this->stream = fopen($this->url, 'a');

            if ($this->filePermission !== null) {

                @chmod($this->url, $this->filePermission);

            }

            restore_error_handler();

            if (!is_resource($this->stream)) {

                $this->stream = null;

 

                throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened: '.$this->errorMessage, $this->url));

            }

        }

 

        if ($this->useLocking) {

            // ignoring errors here, there's not much we can do about them

            flock($this->stream, LOCK_EX);

        }

 

        $this->streamWrite($this->stream, $record);

 

        if ($this->useLocking) {

            flock($this->stream, LOCK_UN);

        }

    }

 `

**Comment by nabeelio** [comment]
That error looks unrelated, it's saying permission denied to the log file
