### ISSUE TITLE
No way to add files to fleet

### ISSUE THREAD

**Issue by NevaPortal** [nabeelio/phpvms#567]
I am trying to add files in to fleet with url or choose file i get this error - [https://prnt.sc/r5n9gf](url)
same with subfleet and airport add files.

`UnexpectedValueException
The stream or file "/home/ottomanva/public_html/storage/logs/laravel-2020-02-21.log" could not be opened: failed to open stream: Permission denied`

`Monolog\Handler\StreamHandler::write
:110
vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110

        if (!is_resource($this->stream)) {

            if (null === $this->url || '' === $this->url) {

                throw new \LogicException('Missing stream url, the stream can not be opened. This may be caused by a premature call to close().');

            }

            $this->createDir();

            $this->errorMessage = null;

            set_error_handler([$this, 'customErrorHandler']);

            $this->stream = fopen($this->url, 'a');

            if ($this->filePermission !== null) {

                @chmod($this->url, $this->filePermission);

            }

            restore_error_handler();

            if (!is_resource($this->stream)) {

                $this->stream = null;

 

                throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened: '.$this->errorMessage, $this->url));

            }

        }

 

        if ($this->useLocking) {

            // ignoring errors here, there's not much we can do about them

            flock($this->stream, LOCK_EX);

        }

 

        $this->streamWrite($this->stream, $record);

 

        if ($this->useLocking) {

            flock($this->stream, LOCK_UN);

        }

    }`

**Comment by nabeelio** [comment]
Same as the other ticket, looks like permission denied to the log file. Are the permissions on the `storage/logs` folder correct?

**Comment by NevaPortal** [comment]
Storage 0775 - Logs 0775 - laravel-2020-02-21.log 0644 I've changed laravel-2020-02-21.log to 0775 but the same problem.

**Comment by NevaPortal** [comment]
Ok here what happens. Each day logs comes to that folder but comes with owner root. When i change the owner to ottomanva then works well. Let's see tomorrow.

**Comment by nabeelio** [comment]
Where's the root user coming from? You probably need to change that wherever its getting written out as root

**Comment by NevaPortal** [comment]
Well i am root user also ottomanva user. I am everything for this server. :)

**Comment by nabeelio** [comment]
Right, but if the file gets created by root, then other users can't access, esp if your web process are running on a different user.

**Comment by NevaPortal** [comment]
Yeah, i don't know why root created the file  folder and all others owner is ottomanva user. I will see it tomorrow and i will let you know.

**Comment by nabeelio** [comment]
Is the cron running under root?

**Comment by NevaPortal** [comment]
Yes cron job running under root. Today also new log comes with root. I will change it to ottomanuser now and i will check tomorrow again.

**Comment by NevaPortal** [comment]
Also why have log everyday? It will be a problem who doesn't have big hosting space. Is it ok, auto clean up option each week or month?

**Comment by nabeelio** [comment]
It's to make going through the logs easier. It should be deleting them
after a week, I can double check that setting
