### ISSUE TITLE
Flights Page Search Subfleet Column

### ISSUE THREAD

**Issue by NevaPortal** [nabeelio/phpvms#574]
I see this by default.

[https://prnt.sc/r6fj4f](url)

**Comment by nabeelio** [comment]
Uhh that's really weird, showing a list of flights. Would you be able to do a SQL dump of your subfleets and aircraft tables and attach them as a file to a comment?

**Comment by NevaPortal** [comment]
[Downloads.zip](https://github.com/nabeelio/phpvms/files/4241782/Downloads.zip)

**Comment by nabeelio** [comment]
Are you still getting this with the latest dev?

**Comment by nabeelio** [comment]
Let me know if this is still open in the latest dev versions
