### ISSUE TITLE
Updater not working because Source repository [github] is not defined

### ISSUE THREAD

**Issue by jcabala14** [nabeelio/phpvms#575]
**Describe the bug**
When try to update phpVMS 7.0.0 beta 3, source repository doesn't configure.
InvalidArgumentException: Source repository [github] is not defined.

**Version**
phpVMS 7.0.0

**To Reproduce**
1. Go to admin/maintenance
2. Click on Update button.
3. Click on Run button.
4. See error.

**Expected behavior**
Expected autoupdate phpvms version.

**Screenshots**
![image](https://user-images.githubusercontent.com/3659173/75111549-7b4e2700-563b-11ea-88bd-d052adf93ceb.png)

**Comment by nabeelio** [comment]
What version are on you specificially? There won't be a update available but this error shouldn't be showing up anyway

**Comment by nabeelio** [comment]
Oh, you'll need the latest dev version for this to work. It'll attempt to upgrade from dev to beta, though that'll actually be a downgrade. This functionality will only work on release versions.

**Comment by jcabala14** [comment]
Perfect nabeelio!

I have the latest version of commits from the dev branch to try the application and help in issues report ^^

**Comment by nabeelio** [comment]
No problem, thanks! I actually found a different bug with versioning issues. But I'm not sure why you're still getting that error. Do you have a `config/self-update.php` file? Is the `repository` stuff all filled in pointing to this repo?

**Comment by jcabala14** [comment]
Yep, I have this file with this code (only paste repository part):

`'type'                 => 'github',
            'repository_vendor'    => 'nabeelio',
            'repository_name'      => 'phpvms',
            'repository_url'       => 'https://github.com/nabeelio/phpvms',
            'download_path'        => storage_path('app'),
            'private_access_token' => '',
            'use_branch'           => '',`

**Comment by nabeelio** [comment]
I'll close this for now, when I release the next beta (maybe tomorrow) we can see if it'll work properly when updating from dev
