### ISSUE TITLE
Support Composer

### ISSUE THREAD

**Issue by Vansers** [nabeelio/phpvms#58]
To ease installing/updating phpVMS v4 in the future, why not support composer that way people wouldn't have to download and upload/extract phpVMS v4.

Easy way for folks who has SSH access and use composer update command.

**Comment by Vansers** [comment]
Basically create a composer.json file in your public_html and add the following lines...

`{
    "require": {
     "nabeel/phpvms": "dev-master"
}`

Then if you have SSH access, you can easily run this command "composer update" and it'll do all the work. This requires to have composer installed, more details -> https://getcomposer.org/doc/00-intro.md

If required, I can provide more details how to install composer on a shared hosting account.

**Comment by nabeelio** [comment]
So do you want a pre-built `composer.json` file that can be the installed? Or is it two packages, one for something like `nabeel/phpvms-core` and then `nabeel/phpvms`, the latter being the one that people download?

**Comment by Vansers** [comment]
Okay, I'm getting close on this...I need to figure out how to define a directory where we exactly want to install. I'll check out composer docs. We need to ensure that dev-master is in the parameters as we don't have a stable release yet.

`composer create-project nabeel/phpvms phpvms/ dev-master`

With this command, it'll grab the full package from git, but when I ran this, I got this error...

`Package egeloen/http-adapter is abandoned, you should avoid using it. Use php-http/httplug instead.
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? n
> php artisan key:generate


  [ErrorException]
  file_get_contents(/**********/public_html/phpvmsv4test/*/.env): failed to
  open stream: No such file or directory


Script php artisan key:generate handling the post-create-project-cmd event returned with error code 1`

But that's normal, we still haven't done the installer or other stuff, we might need make some changes for new installs, but for sure, updates and trigger the command artisan migrate.

**Comment by Vansers** [comment]
Okay, in SSH, make sure your in the public_html directory. To do this, cd public_html

Once you typed that command in, then run `composer create-project nabeel/phpvms phpvms dev-master` and it'll create a folder phpvms in public_html.

But it'll still spit out the error as mentioned. That's normal, we still haven't got a workaround for this, we still need to edit our .env file.

Go into the directory where you installed phpVMS, find the ".env.dev.example" file, edit the details for your database connection details, and then save as .env file.

Back in your SSH, change the directory to your installation by `cd phpvms`

Run the following commands...

`php artisan database:create
php artisan migrate:refresh --seed
`
We probably don't need the first line but for events when we want to use MySQL, but this case if we want to use SQLLite3, then we need the first line command for sure.

Then everything should work from there.

**Comment by Vansers** [comment]
#59

**Comment by Vansers** [comment]
a9ea54a7c024ed610a6cc6236d49b63a8e217672

**Comment by Vansers** [comment]
Commit a9ea54a7c024ed610a6cc6236d49b63a8e217672

**Comment by Vansers** [comment]
#a9ea54a7c024ed610a6cc6236d49b63a8e217672

**Comment by Vansers** [comment]
Corrected file copy error - #59 

Updates, to be looked in.
