### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by Vansers** [nabeelio/phpvms#63]
Create 404 page, or maybe redirect back to the page where they were with a 404 error? That way people won't see Laravel's long list of errors.

**Comment by nabeelio** [comment]
and the other error codes:

* 401 - Unauthorized
* 503 - Error

**Comment by Vansers** [comment]
https://laravel.com/docs/5.4/errors#custom-http-error-pages

**Comment by Vansers** [comment]
#64

**Comment by Vansers** [comment]
Pull request pending approval. This can be closed once approved.
