### ISSUE TITLE
.: Links to pilot profiles :.

### ISSUE THREAD

**Issue by 21Insight** [nabeelio/phpvms#655]
**Bug**
Error entering the pilots profile from the page that lists the pilots `./pilots`

[Example error](https://flareapp.io/share/OmVbJwm8)

**Version**
commit 3c0cd34071ace5ccdd4b7a8cf2ac6ca3f45272af

**To Reproduce**
1. Go to `./pilots`
2. Click on `names of some pilot`
3. See error

**Expected behavior**
Unlike the dashboard that links to `./profile/n`, on the page that lists the `./pilots` pilots it doesn't happen that way since here it links to `./p/n`

**Screenshots**

![Pilots](https://user-images.githubusercontent.com/59656796/78332346-79865600-754d-11ea-81fc-19399444d632.png)
![dash](https://user-images.githubusercontent.com/59656796/78332359-8145fa80-754d-11ea-9e66-71c948a82d72.png)

**Comment by nabeelio** [comment]
Thanks, I will take a look!
