### ISSUE TITLE
Pilot Names -  Pilots ID

### ISSUE THREAD

**Issue by ProAviaAZ** [nabeelio/phpvms#656]
On main site page - pilots name shows full first and last. Can that be changed to show full first and only first letter of last name?

Actually, anywhere on the public side - whether logged in or not - show only full first name and first letter of last name for privacy/security reasons. On admin side show full first and full last names.

Also, on 'Pilots' page - show pilot ID (airline code and pilot number - "VMS001") and set default sort order by pilot ID. Possibly allow sorting by other columns, but default to pilot ID.

**Comment by nabeelio** [comment]
Great idea
