### ISSUE TITLE
Center live map to custom location

### ISSUE THREAD

**Issue by Luxuryceo** [nabeelio/phpvms#661]
1.Change map center in admin panel instead of directly in file

2.Able to Log into site using pilot ID or email instead of just email. 

3.Possible add directions on how to set up a cron job

**Comment by nabeelio** [comment]
Hi,

For 1, I believe that's left over, you should be able to in the admin. 
2. I will take a look into this, you should be able to as well
3. There's some docs here: http://docs.phpvms.net/developers
But I believe you are correct that cron job docs are missing. I will add those

**Comment by Luxuryceo** [comment]
Ah ok just I can't find the option to move the live map to Europe  its sitting at America atm lol

What about admin emails to pilots and a hubs system as well  I've left a few things on phpvms.net as well     just trying to help you with errors that I find and ideas  hope it helps you

**Comment by nabeelio** [comment]
Yeah, it's much appreciated! I'll check into the map centering. I renamed this issue. Can you create a new issue for emailing all users? It's easier for me to keep track with separate GH issues. Thanks!

**Comment by nabeelio** [comment]
If you go to the admin panel, under settings, there's a section for ACARS. It's located there:

![image](https://user-images.githubusercontent.com/99736/78999655-15e5c500-7b19-11ea-9bb4-40378f52e3d6.png)

**Comment by nabeelio** [comment]
I'm closing this; if the above setting doesn't work, please reopen it and I'll take a look
