### ISSUE TITLE
Emails/notifications not sent

### ISSUE THREAD

**Issue by barf** [nabeelio/phpvms#675]
**Describe the bug**
Emails/notifications not sent

**Version**
phpVMS 7 Beta 3

**To Reproduce**
1. Install on Ubuntu with Apache and MariaDB
2. Configure SMTP settings in config.php
3. Register new user

**Expected behavior**
SMTP connection is made to server configured in config.php and emails are sent to new user on registration.

**Additional context**
Log messages:
`[2020-05-02 16:00:47] prod.INFO: NotificationEvents::onUserRegister: VNZ0002 is Active, sending active email`
`[2020-05-02 16:00:47] prod.INFO: User registered:  {"id":2,"pilot_id":2,"name":"foo barf","email":"barfbarf@gmail.com","airline_id":1,"rank_id":1,"country":"nz","home_airport_id":"NZCH","curr_airport_id":"NZCH","last_pirep_id":null,"flights":0,"flight_time":0,"transfer_time":25200,"avatar":null,"timezone":"UTC","status":0,"state":1,"toc_accepted":true,"opt_in":true,"active":null,"last_ip":null,"created_at":"2020-05-02 16:00:47","updated_at":"2020-05-02 16:00:47","deleted_at":null,"journal":{"id":3,"ledger_id":null,"type":1,"balance":{"App\\Support\\Money":"$0.00"},"currency":"NZD","morphed_type":"App\\Models\\User","morphed_id":2,"created_at":"2020-05-02 16:00:47","updated_at":"2020-05-02 16:00:47"},"rank":{"id":1,"name":"New Pilot","image_url":null,"hours":0,"acars_base_pay_rate":"50.00","manual_base_pay_rate":"25.00","auto_approve_acars":false,"auto_approve_manual":false,"auto_promote":true,"auto_approve_above_score":0,"auto_approve_score":null,"created_at":null,"updated_at":null},"airline":{"id":1,"icao":"VNZ","iata":null,"name":"Virtual RNZAF","country":"nz","logo":null,"active":true,"total_flights":0,"total_time":0,"created_at":"2020-05-02 15:36:18","updated_at":"2020-05-02 15:36:18"}}`

**Comment by nabeelio** [comment]
Are you able to send emails using mail or something from that SMTP server?

**Comment by barf** [comment]
yes absolutely, the php mail() function works here and so does drupal etc.

I even gave up and tried mailgun but it does not send either.

**Comment by nabeelio** [comment]
Hmm, nothing in the logs either? I'm taking a look

**Comment by barf** [comment]
Thanks nabeelio!

Nothing relevant from the app here, other than this message saying "sending active email". The log level is configured as debug and same problem with the git dev branch too.

I have control over my SMTP server but no connection is received by it (Postfix), although other PHP webapps on the same host can connect and send mail OK. I'll keep looking into my environment but can't find any fault with it yet, simple PHP mail() test scripts work and so does drupal's SMTP client FWIW.

**Comment by barf** [comment]
After some more testing I'm pretty confident my PHP environment, SMTP server and laravel SMTP settings are configured correctly because I'm receiving backup notification emails from phpVMS, but upon registration (or approval of a pending registration) nothing is received still.

Maybe I should have asked first, is it actually supposed to send a confirmation email on signup/registration? (I'm just going by this 'sending mail' line in the logs)
Does phpVMS verify email addresses with one-time URLs?

**Comment by nabeelio** [comment]
Thanks for looking at this... it uses the default Laravel user system, so I don't think there's a confirmation email with verification, but instead, like the "legacy" phpvms, the user is confirmed by an admin.

There are some unit tests for user registration which verify an email is sent out... email was working but I changed it to the new "notifyables" Laravel interface... which I thought was working.

I assume you have command-line access, I can add an artisan dev command to test it in a new branch, I'll post it up in a few

**Comment by nabeelio** [comment]
Apparently the notification fake in the tests doesn't check if `toMail()` gets called, only that a notification is fired. If you can check out this branch: `675-Email-Fixes`

On the command line, run:

```
php artisan phpvms new-user-email 1
```

(Assuming 1 is your user id). See if you get a notification email/errors in the log. It uses the same mechanism as the events. I'm digging into it more, seems like something is wrong here. The new notification stuff is a bit convoluted so I'm trying to wrap my head around it again.

**Comment by nabeelio** [comment]
Ok, I think it's fixed in the above PR, if you can double-check. It looks like it was getting queued and not actually sent

**Comment by barf** [comment]
emails are working is now! thanks nabeelio!!!
sorry i took a while to respond, had an accident with git when i tried switching branch :sweat_smile:
