### ISSUE TITLE
Error submitting PIREP: Aircraft not at departure airport (but is)

### ISSUE THREAD

**Issue by barf** [nabeelio/phpvms#685]
**Describe the bug**
An error occurs when submitting a manual PIREP after booking a flight configured for the user's airline, rank and location.

**Version**
git master branch

**To Reproduce**
1. Install / configure airline and users
2. Create Fleet and associated aircraft
3. Create routes/flights
4. Bid on a flight and submit a manual PIREP

**Expected behavior**
PIREP accepted/submitted

**Additional context**
```
[2020-05-05 14:19:57] prod.INFO: Aircraft 29 not at departure airport NZWP, erroring out  
[2020-05-05 14:20:07] prod.INFO: Aircraft 29 not at departure airport NZWP, erroring out  
[2020-05-05 14:21:14] prod.INFO: Aircraft 29 not at departure airport NZWP, erroring out  
```

**Comment by barf** [comment]
FYI it is possible to work around this by saving the PIREP as a draft, then submitting.

**Comment by nabeelio** [comment]
Hmm... interesting on the draft workaround. I think someone else was reporting this too (but on the API side)

**Comment by nabeelio** [comment]
@vangelisb is this the error you're seeing?

**Comment by barf** [comment]
Thanks for looking at this nabeelio! If I can figure out this laravel thing I'll try fix it myself

Not sure if related but when importing a fleet via CSV there is no location column, and I just expected one given there's a location column on the fleet table (altho' more of a feature request probably)

**Comment by vangelisb** [comment]
Among others yes but it was on the json response of the api and as i told you it was because some info where empty

**Comment by nabeelio** [comment]
@barf that sounds like a bug. I have a issue here to update aircraft through the scheduler nightly to make sure their location is at their latest... but I don't think that's it.

**Comment by nabeelio** [comment]
Hi, is this still an issue on the latest dev?

**Comment by hcshires** [comment]
This has been fixed. I have tested the update and it works even with ACARS

**Comment by YashGovekar** [comment]
@nabeelio I suppose this one is also fixed?

**Comment by nabeelio** [comment]
Yup, thanks!
