### ISSUE TITLE
Erroneous data format for unserializing 'Symfony\Component\Routing\CompiledRoute'

### ISSUE THREAD

**Issue by vangelisb** [nabeelio/phpvms#691]
**Describe the bug**
A clear and concise description of what the bug is. Please upload the Laravel logs as well from `storage/logs/laravel.log` (or the file with the correct date)

**Version**
version 7.0.0-dev

**To Reproduce**
1. Reset Cache all of them 

**Expected behavior**
Remove ghost airplanes from map

**Comment by nabeelio** [comment]
Hey. I need more info... what page is this on or api call? Need logs and what's going on

**Comment by vangelisb** [comment]
[laravel-2020-05-13.log](https://github.com/nabeelio/phpvms/files/4623420/laravel-2020-05-13.log)

**Comment by nabeelio** [comment]
Have you seen this again?
