### ISSUE TITLE
Pilot ID Login

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#698]
Is it possible to login using your pilot ID?

Thanks!

**Comment by nabeelio** [comment]
Not yet, and I thought I had an issue open for that. I will just use this one :)

**Comment by nickkecooper** [comment]
Okay sounds good didn't see that other thread!

**Comment by nabeelio** [comment]
I can't find it either for some reason, which is probably why I overlooked it. It should be implemented now
