### ISSUE TITLE
Error exporting expenses

### ISSUE THREAD

**Issue by nabeelio** [nabeelio/phpvms#701]
> Array to string conversion

**Comment by YashGovekar** [comment]
Can you please explain this?

**Comment by nabeelio** [comment]
This is a good one to look at. Go to the admin panel, and then try to export expenses, it'll give an error. 
https://flareapp.io/share/OmV8Qjw7

This might take some figuring out. I export them in a certain format so it could be a problem with how that's being done

**Comment by nabeelio** [comment]
It does it on the demo site, too

**Comment by YashGovekar** [comment]
Sure, I'll check it out. Thanks!
