### ISSUE TITLE
Skin: Live Map

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#702]
I am in the process of skinning out V7.0 and all has been good so far. I did how ever come across an issue with the live map on the skin. It looks like the PHP code is returning on the page as regular text. 

`{ pirep.airline.icao }{ pirep.flight_number }
{ pirep.dpt_airport.name } ({ pirep.dpt_airport.icao }) to { pirep.arr_airport.name } ({ pirep.arr_airport.icao })
`

I also am getting a error in my live console reporting "Uncaught ReferenceError: phpvms is not defined" 

Any thoughts would be greatly appreciated!

**Comment by nabeelio** [comment]
Those are placeholders for the rivets.js code. My first guess would be that you're missing the JS imports. See the notes in the templates themselves,

* [notes about the lines required in the header](https://github.com/nabeelio/phpvms/blob/dev/resources/views/layouts/default/app.blade.php#L11-L32). There are also corresponding required lines in the footer.
* [notes about how the live map template works](https://github.com/nabeelio/phpvms/blob/dev/resources/views/layouts/default/widgets/live_map.blade.php#L5)

**Comment by nickkecooper** [comment]
I made sure all of the required header information and the footer script within the live-maps page was there. I do not see the live-map.js included in any of the scripts though.

**Comment by nabeelio** [comment]
That's all compiled into a single js file using webpack. The `phpvms` namespace is defined [is here](https://github.com/nabeelio/phpvms/blob/dev/resources/js/bootstrap.js), and then its built into the main `app.js` file [here](https://github.com/nabeelio/phpvms/blob/3b1936e110c12dde2f2a336dd283a7a244a1f036/webpack.mix.js#L143)

Do you have the app.js script included? Is there a way I can see the `app.blade.php` file?

**Comment by nickkecooper** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>@yield('title') - {{ config('app.name') }}</title>

  {{-- Start of required lines block. DON'T REMOVE THESE LINES! They're required or might break things --}}
  <meta name="base-url" content="{!! url('') !!}">
  <meta name="api-key" content="{!! Auth::check() ? Auth::user()->api_key: '' !!}">
  <meta name="csrf-token" content="{!! csrf_token() !!}">
  {{-- End the required lines block --}}

  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <link href="{{ public_asset('vual-assets/img/favicon.ico') }}" rel="icon">
  <link href="{{ public_asset('vual-vual-assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">


  <link href="{{ public_asset('vual-assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/animate.css/animate.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/icofont/icofont.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/venobox/venobox.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/owl.carousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/aos/aos.css') }}" rel="stylesheet">

  <link href="{{ public_asset('vual-assets/css/style.css') }}" rel="stylesheet">

  <style type="text/css">
     @yield('css')
   </style>
   
    <script>
      @yield('scripts_head')
    </script>
</head>

<body>


  
  <header id="header" class="fixed-top header-transparent">
    <div class="container">

      <div class="logo float-left">
     <a href="{{ url('/') }}"><img src="{{ public_asset('vual-assets/img/vual_logo.png') }}" alt="" class="img-fluid"></a>
      </div>


      <nav class="nav-menu float-right d-none d-lg-block">

        @include('nav')

      </nav>

    </div>
  </header>

  
  <section id="hero" class="d-flex justify-cntent-center align-items-center">

  </section>

  <main id="main">

    @yield('content')

  </main>

  
  <footer id="footer">



    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{{ url('/') }}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About Us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/register">Application</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Legal</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Partners</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="http://www.vatsim.net/">Vatsim</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="https://www.phpvms.net/">phpVMS</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="http://www.vatstar.com/">VATSTAR</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="http://www.simbrief.com/">Simbrief</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="https://www.simfdr.com/">SimFDR</a></li>
            </ul>
          </div>


          <div class="col-lg-6 col-md-6 footer-info">
            <h3>About Us</h3>
            <p>We pride ourselves in being a fun, light hearted virtual airline, that accepts pilots at all skill levels. Join us today and take to the virtual skies with Virtual United Airlines!</p>

            <a href="/register" class="get-started-btn">Apply Today!</a>
            <div class="social-links mt-3">
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="youtube"><i class="bx bxl-youtube"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright {{ date('Y') }} <strong><span>Virtual United Airlines</span></strong>. All Rights Reserved. Virtual United Airlines is not affiliated with or sponsored by United Air Lines, Inc.
      </div>

    </div>
  </footer>



  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>


  <div class="modal fade bs-modal-sm log-sign" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-body">

<h3>Pilot Login</h3>

          {{ Form::open(['url' => url('/login'), 'method' => 'post', 'class' => 'form-horizontal']) }}

              <fieldset>
              
              

                 <div class="group">

      {{
        Form::text('email', old('email'), [
          'id' => 'email',
          'type' => 'text',
          'class' => 'input',
          'required' => true,
        ])
      }}

      <span class="highlight"></span><span class="bar"></span>
      <label class="label" for="date">Email address</label></div>

              
              <div class="group">

                {{
                    Form::password('password', [
                        'name' => 'password',
                        'type' => 'password',
                        'class' => 'input',
                        'required' => true,
                    ])
                }}

  <span class="highlight"></span><span class="bar"></span>
      <label class="label" for="date">Password</label>
      </div>

              
              <div class="control-group">
                <label class="control-label" for="signin"></label>
                <div class="controls">
                  <button id="signin" name="signin" class="btn btn-primary btn-block">Log In</button>
                </div>
              </div>

              <div class="forgot-link" align="center">
               <a href="{{ url('/password/reset') }}"> I forgot my password</a>
               </div>
              </fieldset>

              {{ Form::close() }}
        </div>
      </div>
    </div>
  </div>



  <script src="{{ public_asset('vual-assets/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/jquery.easing/jquery.easing.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/php-email-form/validate.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/venobox/venobox.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/waypoints/jquery.waypoints.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/counterup/counterup.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/owl.carousel/owl.carousel.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/aos/aos.js') }}"></script>

  <script src="{{ public_asset('vual-assets/js/main.js') }}"></script>

  @yield('scripts')

</body>

</html>
`

**Comment by nabeelio** [comment]
You might have to put the `app.blade.php` into a gist or something.

**Comment by nickkecooper** [comment]
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>@yield('title') - {{ config('app.name') }}</title>

  {{-- Start of required lines block. DON'T REMOVE THESE LINES! They're required or might break things --}}
  <meta name="base-url" content="{!! url('') !!}">
  <meta name="api-key" content="{!! Auth::check() ? Auth::user()->api_key: '' !!}">
  <meta name="csrf-token" content="{!! csrf_token() !!}">
  {{-- End the required lines block --}}

  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  <link href="{{ public_asset('vual-assets/img/favicon.ico') }}" rel="icon">
  <link href="{{ public_asset('vual-vual-assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">


  <link href="{{ public_asset('vual-assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/animate.css/animate.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/icofont/icofont.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/venobox/venobox.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/owl.carousel/assets/owl.carousel.min.css') }}" rel="stylesheet">
  <link href="{{ public_asset('vual-assets/vendor/aos/aos.css') }}" rel="stylesheet">

  <link href="{{ public_asset('vual-assets/css/style.css') }}" rel="stylesheet">

  <style type="text/css">
     @yield('css')
   </style>
   
    <script>
      @yield('scripts_head')
    </script>
</head>

<body>


  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top header-transparent">
    <div class="container">

      <div class="logo float-left">
     <a href="{{ url('/') }}"><img src="{{ public_asset('vual-assets/img/vual_logo.png') }}" alt="" class="img-fluid"></a>
      </div>


      <nav class="nav-menu float-right d-none d-lg-block">

        @include('nav')

      </nav><!-- .nav-menu -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex justify-cntent-center align-items-center">

  </section><!-- End Hero -->

  <main id="main">

    @yield('content')

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">



    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{{ url('/') }}">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About Us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/register">Application</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Legal</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Partners</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="http://www.vatsim.net/">Vatsim</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="https://www.phpvms.net/">phpVMS</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="http://www.vatstar.com/">VATSTAR</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="http://www.simbrief.com/">Simbrief</a></li>
              <li><i class="bx bx-chevron-right"></i> <a target="_blank" href="https://www.simfdr.com/">SimFDR</a></li>
            </ul>
          </div>


          <div class="col-lg-6 col-md-6 footer-info">
            <h3>About Us</h3>
            <p>We pride ourselves in being a fun, light hearted virtual airline, that accepts pilots at all skill levels. Join us today and take to the virtual skies with Virtual United Airlines!</p>

            <a href="/register" class="get-started-btn">Apply Today!</a>
            <div class="social-links mt-3">
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="youtube"><i class="bx bxl-youtube"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright {{ date('Y') }} <strong><span>Virtual United Airlines</span></strong>. All Rights Reserved. Virtual United Airlines is not affiliated with or sponsored by United Air Lines, Inc.
      </div>

    </div>
  </footer>



  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>


  <div class="modal fade bs-modal-sm log-sign" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">

        <div class="modal-body">

<h3>Pilot Login</h3>

          {{ Form::open(['url' => url('/login'), 'method' => 'post', 'class' => 'form-horizontal']) }}

              <fieldset>
              <!-- Sign In Form -->
              <!-- Text input-->

                 <div class="group">

      {{
        Form::text('email', old('email'), [
          'id' => 'email',
          'type' => 'text',
          'class' => 'input',
          'required' => true,
        ])
      }}

      <span class="highlight"></span><span class="bar"></span>
      <label class="label" for="date">Email address</label></div>

              <!-- Password input-->
              <div class="group">

                {{
                    Form::password('password', [
                        'name' => 'password',
                        'type' => 'password',
                        'class' => 'input',
                        'required' => true,
                    ])
                }}

  <span class="highlight"></span><span class="bar"></span>
      <label class="label" for="date">Password</label>
      </div>

              <!-- Button -->
              <div class="control-group">
                <label class="control-label" for="signin"></label>
                <div class="controls">
                  <button id="signin" name="signin" class="btn btn-primary btn-block">Log In</button>
                </div>
              </div>

              <div class="forgot-link" align="center">
               <a href="{{ url('/password/reset') }}"> I forgot my password</a>
               </div>
              </fieldset>

              {{ Form::close() }}
        </div>
      </div>
    </div>
  </div>



  <script src="{{ public_asset('vual-assets/vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/jquery.easing/jquery.easing.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/php-email-form/validate.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/venobox/venobox.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/waypoints/jquery.waypoints.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/counterup/counterup.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/owl.carousel/owl.carousel.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ public_asset('vual-assets/vendor/aos/aos.js') }}"></script>

  <script src="{{ public_asset('vual-assets/js/main.js') }}"></script>

  @yield('scripts')

</body>

</html>

```

**Comment by nabeelio** [comment]
I don't see this block near the footer:

https://github.com/nabeelio/phpvms/blob/dev/resources/views/layouts/default/app.blade.php#L78

**Comment by nickkecooper** [comment]
Man I missed that one! Sorry for the topic. Ill let you know if that works

**Comment by nabeelio** [comment]
No problem. I recommend usually that people start with the main app template and just remove what they don't need. But there's only a couple of sections that are required.

**Comment by nickkecooper** [comment]
Hmm now it looks like this. See attached photo. 
![Capture](https://user-images.githubusercontent.com/51838412/82345736-39731980-99bb-11ea-8c5b-a378205ceb3c.PNG)

**Comment by nabeelio** [comment]
I think that's something in the CSS which is messing with the map CSS and stretching it out like that. Use the inspector/console to drill down the styles and see what's causing it. I'd remove all of your own CSS and see if it's doing it with the bare one

**Comment by nickkecooper** [comment]
Hmm this is what is coming out of my console. 

```
DevTools failed to load SourceMap: Could not load content for chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars"}
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars/geojson"}
leaflet-src.js:1192 Uncaught (in promise) TypeError: Cannot read property 'lat' of undefined
    at N.getCenter (leaflet-src.js:1192)
    at live_map.js:190
getCenter @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
v @ app.js:1
d @ app.js:1
(anonymous) @ livemap:322
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars"}
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars/geojson"}
leaflet-src.js:1192 Uncaught (in promise) TypeError: Cannot read property 'lat' of undefined
    at N.getCenter (leaflet-src.js:1192)
    at live_map.js:190
getCenter @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
v @ app.js:1
setInterval (async)
d @ app.js:1
(anonymous) @ livemap:322
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars"}
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars/geojson"}
leaflet-src.js:1192 Uncaught (in promise) TypeError: Cannot read property 'lat' of undefined
    at N.getCenter (leaflet-src.js:1192)
    at live_map.js:190
getCenter @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
v @ app.js:1
setInterval (async)
d @ app.js:1
(anonymous) @ livemap:322
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars"}
request.js:28 {baseURL: "", headers: {…}, url: "/api/acars/geojson"}
leaflet-src.js:1192 Uncaught (in promise) TypeError: Cannot read property 'lat' of undefined
    at N.getCenter (leaflet-src.js:1192)
    at live_map.js:190
getCenter @ app.js:1
(anonymous) @ app.js:1
Promise.then (async)
v @ app.js:1
setInterval (async)
d @ app.js:1
(anonymous) @ livemap:322
```

**Comment by nabeelio** [comment]
I see this error:

> leaflet-src.js:1192 Uncaught (in promise) TypeError: Cannot read property 'lat' of undefined
    at N.getCenter (leaflet-src.js:1192)
    at live_map.js:190
getCenter @ app.js:1

But I think that's unrelated... I think you have a CSS issue. Though I will fix that getCenter() problem (that actually might be in the admin, in settings, the map center might be blank? I have to check that code)

**Comment by nickkecooper** [comment]
Gotcha I will take a look and try to get down to the CSS issues. But I do not know why CSS would display some of the code and such.

**Comment by nabeelio** [comment]
I'm looking at the console on http://demo.phpvms.net/livemap and I see the same error, but I know that map does work

**Comment by nickkecooper** [comment]
Very true I will continue diving into this. I will report what fixes it.

**Comment by nickkecooper** [comment]
```  <link href="{{ public_mix('/assets/global/css/vendor.css') }}" rel="stylesheet"/> ```

Was missing in my app.blade.php! Once again thank you for working through this with me.

**Comment by nabeelio** [comment]
Awesome! Glad you found it

**Comment by nabeelio** [comment]
I'm opening #704 to address the error you were seeing and it not centering
