### ISSUE TITLE
Rank & Awards Page

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#703]
Would love to see a page populated with awards and ranks within the virtual airline.

**Comment by nickkecooper** [comment]
If I wanted to create a ranks page and I were to update the version of phpvms that would cancel out my page right? As I would be creating controllers and adding routes to the RouteServiceProvider?

**Comment by nabeelio** [comment]
Not if it's in a module. The module wouldn't be affected.

**Comment by nickkecooper** [comment]
I was thinking of making it a module, but then there would be two "Rank" spots in the admin panel right?

**Comment by nabeelio** [comment]
What do you want to make? A page that's listing everyone's ranks? Because if you create at as part of the full install (not a module), in a PR, I can just have it included part of the default install

**Comment by nickkecooper** [comment]
Yea I will go ahead and create a Frontend awards page and controller. I'll try to learn how to submit commits and such.

**Comment by nabeelio** [comment]
Fork this repo, then create a new branch (`git checkout dev` and then `git checkout -b 703-Ranks-Page` - that's the convention I've been using), and then create a pull-request against the dev branch

**Comment by nickkecooper** [comment]
Ranks Page Information:
1. Create Ranks folder under Resources/Views/Layouts/"Your Theme" 
2. Create index.blade.php & table.blade.php within Ranks folder.

3. Add the following to index.blade.php:

```
@extends('app')
@section('title', trans_choice('common.ranks', 2))

@section('content')
  <div class="row">
    <div class="col-md-12">
      <div class="section-title">
      <h2>Ranks</h2>
    </div>

      @include('ranks.table')
    </div>
  </div>


@endsection
```

4. Add the following to table.blade.php:
```
<table class="table table-hover" id="ranks-table">
  <thead>
    <th></th>
    <th style="text-align: center">Rank</th>
    <th style="text-align: center">Hours Required</th>
    <th style="text-align: center">Aircraft</th>

  </thead>
  <tbody>
  @foreach($ranks as $rank)
    <tr>
      <td class="text-center"><img src="{{ $rank->image_url }}" /></td>
      <td class="text-center align-middle">{{ $rank->name }}</td>
      <td class="text-center align-middle">{{ $rank->hours }}</td>
      <td class="text-center align-middle">
      @foreach($rank->subfleets as $sf)
      {{ $sf->name }} ({{ $sf->type }})
      @endforeach
      </td>
    </tr>
  @endforeach
  </tbody>
</table>
```

5. Create RankController.php in App/Http/Controllers/Frontend

6. Add the following into RankController.php:
```
<?php

namespace App\Http\Controllers\Frontend;

use App\Contracts\Controller;
use App\Repositories\RankRepository;
use Cache;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
use Prettus\Repository\Criteria\RequestCriteria;

class RankController extends Controller
{
    private $fleetSvc;
    private $rankRepository;
    private $subfleetRepo;

    /**
     * RankController constructor.
     *
     * @param FleetService       $fleetSvc
     * @param RankRepository     $rankingRepo
     * @param SubfleetRepository $subfleetRepo
     */
    public function __construct(
        RankRepository $rankingRepo
    ) {
        $this->rankRepository = $rankingRepo;
    }

    /**
     * Get the available subfleets for a rank
     *
     * @param $rank
     *
     * @return array
     */
    protected function getAvailSubfleets($rank)
    {
        $retval = [];
        $all_subfleets = $this->subfleetRepo->all();
        $avail_subfleets = $all_subfleets->except($rank->subfleets->modelKeys());
        foreach ($avail_subfleets as $subfleet) {
            $retval[$subfleet->id] = $subfleet->name.
                ' (airline: '.$subfleet->airline->code.')';
        }

        return $retval;
    }

    /**
     * Display a listing of the Ranking.
     *
     * @param Request $request
     *
     * @throws \Prettus\Repository\Exceptions\RepositoryException
     *
     * @return mixed
     */
    public function index(Request $request)
    {
        $this->rankRepository->pushCriteria(new RequestCriteria($request));
        $ranks = $this->rankRepository->all();

        return view('ranks.index', [
            'ranks' => $ranks,
        ]);
    }



}
```

*Note common title names are available in Resources/lang/"Your language"/common.php. You will need to add the rank.common variable.*

**Comment by Da-Geek** [comment]
@nabeelio If this feature request is still open, I wouldn't mind giving these suggestions by @nickkecooper a quick run over, maybe create the PR for them, It may even give me some ideas of for the "Awards" display I want to add to the "Pilot Profile" page.

**Comment by nabeelio** [comment]
Sure thing. For now, i think adding a section to the user's profile will be the best/easiest way, it's one less page to navigate to and having all the user's info on one page would be nice

**Comment by Da-Geek** [comment]
I agree, the Pilot Profile is the right place, I'll have a closer look at this code to see how it was being suggested, to see if it will be able to help me get it working on the Pilot Profile Page, and create a PR against this issue if I get it working.
