### ISSUE TITLE
Calculate distance for all flights

### ISSUE THREAD

**Issue by joshhicks1** [nabeelio/phpvms#709]
**Is your feature request related to a problem? Please describe.**
I have to go through and manually calculate the distance for individual flights

**Describe the solution you'd like**
A button on the maintenance page, like the one on PHPVMS5 that calculates the distance for every flight

**Describe alternatives you've considered**

**Additional context**
<img width="1073" alt="Screen Shot 2020-05-21 at 1 15 41 pm" src="https://user-images.githubusercontent.com/39217010/82519516-3caa0900-9b65-11ea-9762-9f39a9bb4ada.png">

**Comment by nabeelio** [comment]
Thanks, I've added this to the roadmap
