### ISSUE TITLE
Error with MySQL syntax when creating database.

### ISSUE THREAD

**Issue by IKnowBashFu** [nabeelio/phpvms#71]
So, I decided to give your software a try, and while your site seems to lack a download link at all, I decided to try cloning this repository. When creating the database, these errors occur.

![image](https://user-images.githubusercontent.com/19581276/33511706-b5c5a838-d6ed-11e7-9109-3ac548c72a6b.png)

When I tried switching to `local` for db_connection, I received these errors:

![image](https://user-images.githubusercontent.com/19581276/33511718-1b8654e2-d6ee-11e7-896c-15c10bc0b0b3.png)

This last one seems like it may be my fault somehow. Perhaps a missing php library?

EDIT: Yep. Installed php7.1-sqlite3, and that seemed to solve the local database error.

**Comment by nabeelio** [comment]
I will take a look at the SQL errors. In terms of the `could not find driver`, you need the php sqlite extension installed and enabled. Are you using mysql in the first screenshot?

There's no download link because this isn't even in an alpha state.

**Comment by nabeelio** [comment]
RE your edit, sounds good. I'll take a look at what's up with mysql. I haven't gotten that setup in travis just yet.

**Comment by IKnowBashFu** [comment]
That first screenshot is indeed MySQL. Specifically, `mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper`

**Comment by nabeelio** [comment]
Fixed in bf2a624. BTW, a default (admin) login is admin@phpvms.net/phpvms. It's set in the dev seed file, so as long as your `APP_ENV=dev`, that should work.

**Comment by IKnowBashFu** [comment]
Just looked at that seeder, actually. I'll go ahead and pull changes and let ya know what else I manage to break.

**Comment by nabeelio** [comment]
Sounds good. It's still very much a WIP.

**Comment by IKnowBashFu** [comment]
I'm aware. Currently setting up dev environment to help where I can. I'm not a Laravel master by any stretch of the imagination, but I know enough to at least start diving in and trying to fix small things.
