### ISSUE TITLE
Creating Modules

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#714]
This is less of a bug and more of a user error. I went ahead and am going about creating a module. However I can not access the module when I go to /admin/MODULENAME. I did follow the brief steps on the GIT for phpvms module. Any help would be appreciated!

**Comment by nabeelio** [comment]
Have you checked out the docs and sample module?

http://docs.phpvms.net/developers/add-ons-and-modules
https://github.com/nabeelio/phpvms-module

**Comment by nickkecooper** [comment]
Yes I did follow those instructions. It does create the folder structure and I changed composer.json as described. But when I try to access the module page from the admin center I get:

> Symfony\Component\HttpKernel\Exception\NotFoundHttpException

**Comment by nickkecooper** [comment]
It also wont show up on the addon menu items.

**Comment by web541** [comment]
Did you add the routes to the Http/Routes/web.php file?
http://docs.phpvms.net/developers/add-ons-and-modules#web-routes

**Comment by nabeelio** [comment]
If you add this into the service provider, does the link show up? I'm assuming that you do that have that there:

https://github.com/nabeelio/phpvms-module/blob/master/Providers/SampleServiceProvider.php#L41

This is pretty early code, I think I need to write an interface to make sure all the required methods are there.

**Comment by nabeelio** [comment]
Yeah, also like @web541 said, there's the web routes file, which in the sample is here: https://github.com/nabeelio/phpvms-module/blob/master/Providers/SampleServiceProvider.php#L53

In the main phpvms, I removed the web.php file and all that because of performance issues and probably will do that in the sample one soon too

**Comment by nickkecooper** [comment]
Okay so running that command showed my module in the menu link.

@nabeelio Yes I took the SampleServiceProvider.php and copied it into my modules provider folder. I then replaced all sample references to my module. 

@web541 Yes I have those routes in place.

**Comment by nabeelio** [comment]
Are the routes working now? You can also use the command to generate the module... I believe when you do that, it should be activated by default. I really need to do #466 so there's an interface that's not the command line to enable/disable

**Comment by nickkecooper** [comment]
So here were my steps.

1. php artisan module:make EventCenter
2. php artisan module:make-controller EventCenterController EventCenter
3. Copy SampleServiceProdvider.php to my module and replaced references to sample.
4. At this point the module was not viewable on the admin addon menu, and I could not route to the module page.
5. php artisan module:enable EventCenter
6. I was able to view the menu link under addons, but still was unable to route to the module page.

So currently I still can not see my module on all views, frontend, api and admin.  

Hope this helps possibly

**Comment by nabeelio** [comment]
Looks like the service provider creation is missing from the module generation, so that's a definite bug.

In that route provider, it looks something like this:

```php
Route::group([
            'as'         => 'installer.',
            'prefix'     => 'install',
            'middleware' => ['web'],
            'namespace'  => 'Modules\Installer\Http\Controllers',
        ]
```

You need that prefix, can you paste in the route group and other definition?

**Comment by nickkecooper** [comment]
Which file would this need to go into? Sorry

**Comment by nabeelio** [comment]
Like this in the service provider:
https://github.com/nabeelio/phpvms-module/blob/master/Providers/SampleServiceProvider.php#L53

**Comment by nickkecooper** [comment]
```
        /*
         * Routes for the frontend
         */
        Route::group([
            'as'     => 'eventcenter.',
            'prefix' => 'eventcenter',
            // If you want a RESTful module, change this to 'api'
            'middleware' => ['web'],
            'namespace'  => 'Modules\EventCenter\Http\Controllers',
        ], function () {
            $this->loadRoutesFrom(__DIR__.'/../Http/Routes/web.php');
        });
```

That is what mine looks like. Sorry I am not understand what needs to get changed in it

**Comment by nabeelio** [comment]
What does the web.php file look like? The route would be /eventcenter/whatever, with the prefix that's defined there

**Comment by nickkecooper** [comment]
```
<?php

Route::group(['middleware' => [
    'role:user' # leave blank to make this public
]], function() {
    # all your routes are prefixed with the above prefix
    # e.g. yoursite.com/sample
    Route::get('/', 'EventCenterController@index');
});
```

**Comment by nabeelio** [comment]
Remove that role:user. Your route should just be /eventcenter. Let me debug this tomorrow, it's possible something broke in the generator when upgrading to Laravel 7, esp since you had to copy the service provider in. I don't think it's getting generated properly

**Comment by nickkecooper** [comment]
Yea I tried that but no luck. I think its something in the back-end that isn't routing it properly. I look forward to debug! Thanks for the help

**Comment by nickkecooper** [comment]
I'd also like to note that I did this install on cPanel. Not sure if that will change how the commands will work.

**Comment by web541** [comment]
@nabeelio I can also confirm the ServiceProvider isn't automatically being created.

@nickkecooper I got it working doing everything you did in your steps above making sure that EventCenter or eventcenter is case sensitive in all places in the Module/EventCenter/Providers/EventCenterServiceProvider.php, so change them to lowercase where the sample one is lowercase and vice-versa.

After that in your Module/EventCenter/Http/Routes/web.php file, replace everything with this
`Route::get('/', 'EventCenterController@index');` and it should load now.

**Comment by nickkecooper** [comment]
@web541 I changed the file to that and it still wouldn't route.

**Comment by nickkecooper** [comment]
When I run this command php artisan route:list I do not see EventCenter in that list.

**Comment by web541** [comment]
As in it's still showing the 'Page Not Found' 404? Have you checked that your url is case sensitive too, so site.com/modulename where modulename is the 'prefix'.

Can you do
`php artisan module:list`
then `php artisan module:enable EventCenter`
then `php artisan route:list --name=EventCenter`

**Comment by nickkecooper** [comment]
Got it to work! I needed to run ```php artisan route:clear``` I also left all route files the same.

**Comment by nickkecooper** [comment]
It isn't grabbing the module name from the config file. But its routing at least.

**Comment by web541** [comment]
Ahh yeah it was probably cached. Good job 👍 
You mean `{{ config('eventcenter.name') }}` isn't giving what is in Modules/EventCenter/Config/config.php?

**Comment by nickkecooper** [comment]
Correct. I also noticed this within views/admin/index.blade.php:

```@section('actions')
    <li>
        <a href="{{ url('/eventcenter/admin/create') }}">
            <i class="ti-plus"></i>
            Add New</a>
    </li>
@endsection```

Looks like maybe the generator also reverses that when you create a module?

**Comment by nickkecooper** [comment]
I also noticed the following design difference in my generated views/admin/index.blade.php file.
```
@section('content')
    <div class="card border-blue-bottom">
        <div class="header"><h4 class="title">Admin Scaffold!</h4></div>
      <div class="content">
            <p>This view is loaded from module: {{ config('eventcenter.name') }}</p>
        </div>
    </div>
@endsection
```

**Comment by nickkecooper** [comment]
I was able to get my module name to show up by running this command:

```
php artisan config:clear
```

**Comment by web541** [comment]
I'm guessing that would be the generator. Perhaps the config is cached as well?

**Comment by nickkecooper** [comment]
I will leave this open, I'm sure @nabeelio will want it for some fixes. Ill open up any additional bugs in new articles.

**Comment by nabeelio** [comment]
Nice finds! The Laravel caching is really frustrating at times. In your config.php, in the `cache` section, what do you have set there?

You can leave it all in this thread, I can go through and clean them up

**Comment by nabeelio** [comment]
Bleh, I think there's a problem in the module generator... it's supposed to be calling the other generators but it doesn't seem to be doing it. I'll have a PR up shortly, maybe you can check out that branch and test it out

**Comment by nabeelio** [comment]
I opened an issue here with some of the stuff I'm running into: https://github.com/nWidart/laravel-modules/issues/995

Hopefully it's just something I'm doing wrong on my part. I'm mainly getting a 'Module not found' error - did you guys see this when generating?

**Comment by nabeelio** [comment]
Try out this branch:
https://github.com/nabeelio/phpvms/pull/716

I'm still running into issues it seems but I can't seem to figure out where from exactly. I have an issue open in the module repo so maybe the author has an idea

**Comment by nickkecooper** [comment]
I do not have my server setup to pull any new files down via Github releases. If I am bug testing I should get that setup though lol

**Comment by nabeelio** [comment]
Cool, just checkout the dev branch, and then do a checkout from there

**Comment by web541** [comment]
Yeah I did get the "Module Not Found" error after doing the `php artisan module:make {name}` command. It still made it though (without the ServiceProvider), but after it threw that error. I'll check out that branch.

**Comment by nabeelio** [comment]
It didn't have a the `AppServiceProvider` either? This is what I get:

```
$ tree modules/TestModule
modules/TestModule
├── Config
│   └── config.php
├── Console
├── Database
│   ├── factories
│   ├── migrations
│   └── seeds
├── Http
│   ├── Controllers
│   │   ├── Admin
│   │   │   └── AdminController.php
│   │   ├── Api
│   │   │   └── ApiController.php
│   │   └── Frontend
│   │       └── IndexController.php
│   ├── Middleware
│   ├── Requests
│   └── Routes
│       ├── admin.php
│       ├── api.php
│       └── web.php
├── Listeners
│   └── TestEventListener.php
├── Models
├── Providers
│   ├── AppServiceProvider.php
│   ├── EventServiceProvider.php
│   └── RouteServiceProvider.php
├── Resources
│   ├── assets
│   ├── lang
│   └── views
│       ├── admin
│       │   └── index.blade.php
│       ├── index.blade.php
│       └── layouts
│           ├── admin.blade.php
│           └── frontend.blade.php
├── composer.json
├── module.json
└── tests
```

**Comment by web541** [comment]
No that was before, just tested the `714-Module-Interface` branch and I get the same structure as you (with the AppServiceProvider now). Still getting the `Page Not Found` by default, but that's because it wasn't enabled. Any way to enable the module after generating by default?

Also, after enabling I get this:
```
Declaration of Modules\TestMod\Providers\AppServiceProvider::boot() must be compatible with App\Contracts\Modules\ServiceProvider::boot(): void
```
Still get the "Module Not Found" after generating though, but I saw you opened an issue on that.

**Comment by nabeelio** [comment]
I just pushed an update to fix the declarations, give that a try

So it does work after you manually enable it? I'm trying to figure out the 'Module Not Found" error, making sure it's not something I'm doing wrong. I'm stepping through the code now. I'm assuming that the latest step is enabling the module, but because it's crashing, it's not doing it.

I'm trying to avoid wrapping the command for new module creation, but it seems like I may have to `php artisan phpvms:create-module <module name>` which will wrap the module create, but also clear routes/caches. But it looks like a problem might be if someone drops a new module in (by uploading or something), it won't show up until after some caches are cleared, which might be ok but still is annoying

**Comment by web541** [comment]
It did work after enabling it, but I think that was a fluke. Tried again and it failed because of the declarations, so I added them then it failed on this:
```
require(/Users/code/Documents/Apps/phpvms7dev3/modules/TestMod/Providers/../$PATH_CONFIG$/config.php): failed to open stream: No such file or directory
```
But changing the '$PATH_CONFIG$' to 'Config' in the AppServiceProvider fixed it, so it may not be reading it properly?
Also, by running `php artisan module:make-controller Frontend/TestModController TestMod` it still names the class of that file 'IndexController`.

**Comment by nabeelio** [comment]
D'oh. Ok, try that branch again. The variable substitutions are confusing to me, they should just be global. But I've hardcoded a few of those in now which should be fine for being generated, and it doesn't prevent someone from moving things around afterwards

**Comment by nabeelio** [comment]
Except the stub for the controller isn't working now from the module generate. I think something is really broken upstream

**Comment by nickkecooper** [comment]
Just a note on this one. I was able to create a module with no pulls of the new version without doing any clearing of cache. I can write up a how to if you'd like.

**Comment by nabeelio** [comment]
New version meaning dev?

**Comment by nickkecooper** [comment]
Correct, I used the one I had when I first did. But still, of course, had to copy a sampleserviceprovider and the the changes.

**Comment by nabeelio** [comment]
Gotcha, but there's still an issue because the service provider should be generated, and we're seeing those errors in the generation itself. I'm going to downgrade the composer version and see if it's still doing it.

**Comment by nickkecooper** [comment]
Okay. I am creating a module now that will talk to the UserRepo but it seems like I am having an issue. I am trying to simply display the users in a created module. For some reason it isnt showing. 

Module Controller *ONLY PART OF IT*:
```
<?php

namespace Modules\Staff\Http\Controllers\Admin;


use App\Contracts\Controller;
use Illuminate\Http\Request;
use App\Repositories\UserRepository;

/**
 * Class AdminController
 * @package Modules\Staff\Http\Controllers\Admin
 */
class AdminController extends Controller
{
    /**
     * Display a listing of the resource.
     */
     private $userRepo;

     public function __construct(
         UserRepository $userRepo
     ) {
         $this->userRepo = $userRepo;
     }


    public function index(Request $request)
    {
      try {
      $users = $this->userRepo->searchCriteria($request, false)
          ->orderBy('created_at', 'desc');
        } catch (RepositoryException $e) {
          }
          return view('staff::admin.index', [
              'users'   => $users,
          ]);

    }
```

**Comment by nabeelio** [comment]
For a repo, just use the regular model find/findWhere methods. Also look at the other controllers for users (like the frontend one) to see how its done, might be missing a call.

Repository docs: https://github.com/andersao/l5-repository

**Comment by nabeelio** [comment]
Also I'd ask questions like this on the forum, since it might be of interest to others and it's questions about using/developing

**Comment by nabeelio** [comment]
I'm really sorry for the delay, this took a while to figure out. Can you test this out now and see if it's working?

**Comment by nickkecooper** [comment]
I will get this tested out asap.

**Comment by nabeelio** [comment]
I think I'm just gonna merge this. Any news, @nickkecooper ?

**Comment by nabeelio** [comment]
Still open, main service provider generated is incorrect

**Comment by YashGovekar** [comment]
@nabeelio You may close this one.
