### ISSUE TITLE
Skin Module

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#715]
I believe that if I make a module face the user and not just the admin page, it does not take on the skin assigned in the settings. It will revert to the default skin. Not sure if this is a bug or something I need to change on each of my modules to skin them to my current main frame skin.

**Comment by nickkecooper** [comment]
Seems like 404 pages and others don't take the the skin assigned as well.

**Comment by nabeelio** [comment]
I suspect this is because the `web` middleware is missing. I'll fix this as part of the other ticket. Can you try adding that? If you see the Installer module:

```
Route::group([
            'as'         => 'installer.',
            'prefix'     => 'install',
            'middleware' => ['web'],
            'namespace'  => 'Modules\Installer\Http\Controllers',
        ]
```

**Comment by nickkecooper** [comment]
```
<?php

Route::group(['middleware' => [

# leave blank to make this public
]], function() {
    # all your routes are prefixed with the above prefix
    # e.g. yoursite.com/sample
    Route::get('/', 'EventCenterController@index');
});
```

That is my code in web.php in my module's routes folder. Do I add yours to that?

**Comment by nabeelio** [comment]
Change it to this and see if the skin works:

```
Route::group(['middleware' => [
    'web',
]], function() {
    # all your routes are prefixed with the above prefix
    # e.g. yoursite.com/sample
    Route::get('/', 'EventCenterController@index');
});
```

I'm working on refactoring the module creation right now... it's super out of date with how Laravel does things (was originally written with Laravel 4... jeez, I need to get this thing out before we're on Laravel 8)

**Comment by nickkecooper** [comment]
It still looks like its using the default skin with using that.

**Comment by nickkecooper** [comment]
Like I said the 404 error pages are also default to the original skin. I also noticed that the 404 error pages don't point to the changed skin folder, but to the default one.

**Comment by nickkecooper** [comment]
I was able to get my module to work by using this code in web.php:

```
Route::group([
    'middleware' => ['web', 'theme'],
],  function() {
    # all your routes are prefixed with the above prefix
    # e.g. yoursite.com/sample
    Route::get('/', 'EventCenterController@index');
});
```

**Comment by nickkecooper** [comment]
If you would like the page to be only for logged in users:

```
<?php

Route::group([
    'middleware' => ['web', 'theme', 'auth'],
],  function() {
    # all your routes are prefixed with the above prefix
    # e.g. yoursite.com/sample
    Route::get('/', 'EventCenterController@index');
});
```

**Comment by nickkecooper** [comment]
I am still having an issue with error pages (ie. 404) to view in the custom skin.

**Comment by nickkecooper** [comment]
@nabeelio I made those changes but it seems the 404 error page is still set on default. Should I clear cache?

**Comment by nabeelio** [comment]
I have a good (I think) in that pull request I'm trying to merge, that should do it

**Comment by nabeelio** [comment]
Ok, try the latest dev branch. Seems like Github was having some issues and the build didn't report a status.

**Comment by nickkecooper** [comment]
I cant pull the latest. So I changed the files as the commits had them but no change.

**Comment by nickkecooper** [comment]
It started working after a couple hours of me developing so... maybe a cache issue. Thanks for the fix!

**Comment by nabeelio** [comment]
I see where the problem is, it's in the error handler. I think some behavior here changed in Laravel 7. I'm trying to fix it now

**Comment by nabeelio** [comment]
Ok, I'm merging a fix in. I think some behavior changed in the combo of Laravel 7 and the theme package.
