### ISSUE TITLE
Airlines marked as inactive still show up

### ISSUE THREAD

**Issue by joshhicks1** [nabeelio/phpvms#718]
**Describe the bug**
When an airline is marked as inactive, it still shows up on the Airlines section of the registration page.

**Version**
phpVMS7 beta 3

**To Reproduce**
Steps to reproduce the behaviour:
1. Create Airline
2. Mark as inactive
3. Go to registration page and look at airlines

**Expected behaviour**
I expected it not to appear in the options for choosing airlines

**Screenshots**

<img width="1062" alt="Screen Shot 2020-05-23 at 12 30 26 pm" src="https://user-images.githubusercontent.com/39217010/82719794-321c7a80-9cf1-11ea-98a8-fb65994397f0.png">

<img width="665" alt="Screen Shot 2020-05-23 at 12 30 58 pm" src="https://user-images.githubusercontent.com/39217010/82719808-4496b400-9cf1-11ea-85c4-1ecb8beff25f.png">

**Comment by nabeelio** [comment]
This one is a little more involved, so if an airline is inactive, I won't show schedules, etc.

**Comment by joshhicks1** [comment]
Right okay, I'll be marking them as active in that case as it would suit us better but I thought I'd let you know for the purpose of the bug report

**Comment by nabeelio** [comment]
I'm working on it right now, should be done soon.
