### ISSUE TITLE
People ON_LEAVE cannot log in

### ISSUE THREAD

**Issue by joshhicks1** [nabeelio/phpvms#719]
**Describe the bug**
People changed to on leave status cannot log in, it would appear the code has not been added to the LoginController.php file yet.
When they login it just refreshes the page and does nothing.

**Version**
Beta 3

**To Reproduce**
1. Change status to on leave
2. Get them to log in
3. It won't work

**Expected behavior**
It should let them log in, then once they have filed a PIREP it changes them back to active.

**Screenshots**
<img width="473" alt="Screen Shot 2020-05-23 at 2 09 32 pm" src="https://user-images.githubusercontent.com/39217010/82721268-07d1b980-9cff-11ea-9da2-1f813ad52cd3.png">

**Additional context**
Just quickly, I know you'll commit this to the next build, but do you mind providing me with the line of code to add to it now? We just changed over 100 pilots to on leave and we will have to change them all back to active if we can't get this sorted as soon as possible. Cheers

**Comment by web541** [comment]
Not sure what Nabeel plans to do with handling the On Leave users but this will do for you now:
Change
`if ($user->state !== UserState::ACTIVE) {` to this
```php
if ($user->state !== UserState::ACTIVE && $user->state !== UserState::ON_LEAVE) {
```
and it should work.

**Comment by joshhicks1** [comment]
You are a lifesaver, thanks heaps!

**Comment by nabeelio** [comment]
Thanks @web541! I added a PR and will merge: https://github.com/nabeelio/phpvms/pull/720

It also adds in a notice on the dashboard that the user is on leave
