### ISSUE TITLE
notifyAllUsers does not work

### ISSUE THREAD

**Issue by joshhicks1** [nabeelio/phpvms#722]
**Describe the bug**
I noticed in the EventHandler code, when you add a news article it is meant to email it to all users, however it would appear this is not the case.

**Version**
Beta 3

**To Reproduce**
1. Create a news article

**Expected behavior**
An email to be sent to all pilots with the news article

**Screenshots**
<img width="605" alt="Screen Shot 2020-05-24 at 12 23 32 am" src="https://user-images.githubusercontent.com/39217010/82733082-cec43400-9d54-11ea-93b8-add4d0d5228a.png">

**Comment by nabeelio** [comment]
What's it doing instead?

**Comment by joshhicks1** [comment]
Nothing - the news adds fine but it doesn't email anyone anything

**Comment by nabeelio** [comment]
Are users getting the emails about the pirep accept/reject?

**Comment by joshhicks1** [comment]
Yep, they are getting all other emails except the news ones

**Comment by stickbear2015** [comment]
referencing issue #795 as that issue ties into this one.

**Comment by nabeelio** [comment]
This should be fixed now, it wasn't wired up correctly.
