### ISSUE TITLE
Live Flights Pilot

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#726]
I am trying to get the pilot id and name to show up on the table under the live map. I was able to display a pilot name by adding 

```
         $pirep = $pirepRepo->findWithoutFail('1');
         $pilot_callsign = $pirep->user->ident;
         $pilot_name = $pirep->user->name;
```

to the LiveMap.php. However I need a way to input the pirep id and have it correlate to the correct row. Any help would be appreciated!

**Comment by nabeelio** [comment]
Are you talking about `widgets/live_map.blade.php`? That table is generated through Javascript. You'd use `{ pirep.user.name }` as a value - it's bound with rivet.js. If you look at the requests using the JS console, you should be able to see the data that's passed down.

**Comment by nickkecooper** [comment]
I was unaware of where I could find the variables I can pass along but thank you!

**Comment by nabeelio** [comment]
I think it's in the template notes itself. Do you have any suggestions on a better way of documenting these things?

**Comment by nickkecooper** [comment]
Where can I find rivet.js?

**Comment by nabeelio** [comment]
It's a 3rd party library that's built and bundled into the `vendor.js`: http://rivetsjs.com

I assume you're looking for the live map code, which is here: https://github.com/nabeelio/phpvms/blob/dev/resources/js/maps/live_map.js

That's also then build and bundled into an app.js file

**Comment by nickkecooper** [comment]
Gotcha okay I will take a look and see. I was also trying to pass the pilots current hub as well. I am also trying to change the maps design to just a standard map.

**Comment by nabeelio** [comment]
You can use `{ pirep.user.home_airport_id} }`. The list of fields for the user are here: 
https://github.com/nabeelio/phpvms/blob/dev/app/Models/User.php#L13

**Comment by nabeelio** [comment]
Also if you're showing their name, I would use the `name_private` field.

**Comment by nickkecooper** [comment]
Gotcha thank you!

**Comment by nabeelio** [comment]
For the map itself, there is this: https://github.com/nabeelio/phpvms/issues/290 
I have to do some extra work to expose the map type that's being loaded.

**Comment by nickkecooper** [comment]
Is name_private if they dont want their name shown it wont?

**Comment by nabeelio** [comment]
It uses an initial for their last name, like you see on the dashboard, etc. For privacy

**Comment by nickkecooper** [comment]
Hmm doesn't look like it is displaying:

```
              <td>{pirep.user.name_private}</td>
```

**Comment by nickkecooper** [comment]
Airport Id is not working as well. Maybe they don't pass in that live-maps JS?

**Comment by nabeelio** [comment]
Can you look at the rest request in the js console and see what's passed in? maybe there's an error in there

**Comment by nickkecooper** [comment]
Okay so it looks like in the array passed to JS the home airport:

```
user:
airline: {id: 1, icao: "UAL", iata: null, name: "Virtual United Airlines", country: "us", …}
avatar: "https://www.gravatar.com/avatar/3915031986eb9678b03a396ee527c347?d=https%3A%2F%2Fen.gravatar.com%2Fuserimage%2F12856995%2Faa6c0527a723abfd5fb9e246f0ff8af4.png"
curr_airport: "KEWR"
email: "XXXX@gmail.com"
flight_time: 0
flights: 0
home_airport: "KEWR"
id: 1
ident: "XXX0001"
last_pirep_id: null
name: "Nicholas Cooper"
pilot_id: 1
rank_id: 1
state: 1
timezone: "GMT"
```
It does not appear it passes `name_private`

**Comment by nabeelio** [comment]
Ah, it follows this:

https://github.com/nabeelio/phpvms/blob/dev/app/Http/Resources/User.php

So for now, change `name` to return `name_private`:
https://github.com/nabeelio/phpvms/blob/dev/app/Http/Resources/User.php#L18

Looks like `home_airport` is there.

**Comment by nickkecooper** [comment]
Sweet! As I get more familiar I wont have so many questions!

**Comment by nabeelio** [comment]
No worries! Glad it's making sense!

**Comment by nickkecooper** [comment]
Still was not able to change the map to just a standard google map design.

**Comment by nabeelio** [comment]
I'm going to address that in the other ticket. I think the Google Map integration requires some extra stuff like an API key and whatnot, and there's no interface for that right now. I'm going to close this ticket for the time being. Thanks!
