### ISSUE TITLE
Airport Expenses - Financial Module

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#729]
**Describe the bug**
If you set Airport Expenses "per flight", the expense will be applied for every airport, not just the arrival airport

**Version**
version 7.0.0-beta.4

**To Reproduce**
1. Go to 'Airport'
2. Add on 'Add Expenses Per Flight in several airports`
3. File Pirep
4. Check finance report of the flight you will notice that all the airports with expenses are calculated in the report.

https://imgur.com/a/4Zda6f0

Only should apply the destinantion Airport ICAO

**Comment by nabeelio** [comment]
Thanks for the report, should be fixed in the latest dev
