### ISSUE TITLE
FLEETS  Cost Per Hour |Cost Delay Per Minute, not saving/aplying settings

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#731]
Not aplying or saving settings in FLEETS Costs per hour/delay

7.0 Beta4

1. Go to 'Fleets'
2. Click on 'Edit Fleet'
3. Change Values in "Cost per hour/delay'
4. Save Settings
5.Check if settings have been saved or keep original values.

https://imgur.com/a/rThOmTB  (VIDEO STEP BY STEP)

**Comment by rking93** [comment]
Also having this issue.
