### ISSUE TITLE
Editing Rejected Pirep ERROR - Facade\Ignition\Exceptions\View Exception

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#732]
Editing a REJECTED pirep result in a error 

7.0 b4

1. Go to 'pireps`
2. Click on 'Edit any rejected pirep'

https://flareapp.io/share/KPg9VW5a

https://imgur.com/a/jo0ZuNL (video capture)

**Comment by nabeelio** [comment]
Was the aircraft used removed?

**Comment by macofallico** [comment]
well,  yes the aircraft was deleted or modified
