### ISSUE TITLE
Live Flight Progress

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#733]
Would love to be able to get a percentage of progress completed on the live flights table. Been trying to get this to work but to no avail am I able to.

**Comment by nickkecooper** [comment]
I think I might have gotten it but wanted your thoughts. I add the below code to Pirep.php. It seems to be working but I am not sure if it will fail down the line?

```
        $res['progress'] =  ($this->distance) / ($this->planned_distance) * '100';
```

**Comment by nabeelio** [comment]
It could, because there might not be a value for planned_distance. You can check on the PIREP template itself what I do to show the progress

**Comment by nickkecooper** [comment]
Where can I find that template?

**Comment by nabeelio** [comment]
It's one of the front end pirep ones, maybe the "show". I'm not at a computer right now to check

**Comment by nickkecooper** [comment]
Okay thank you sir!

**Comment by nickkecooper** [comment]
It looks like the progress on that page is still using the "planned_distance" value in the pirep database. If that's the case mine should work

**Comment by nabeelio** [comment]
Cool, it should hopefully just work.
