### ISSUE TITLE
Flash Error Messages

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#739]
It does not look like the flash messages on the front end are working, when a custom skin is placed. I made sure ```  @include('flash.message') ``` this was in my app.blade.php file. I also looked within the source code to see if it was maybe hiding due to CSS, but that wasn't the case.

Any help would be appreciated!

**Comment by web541** [comment]
Do they work on the default skin? Maybe try this (from the official flash documentation):
```
@include('flash::message')
```
Not sure if Nabeel's re-routed it or if it has been changed due to a conflict with the modules.

**Comment by nabeelio** [comment]
@web541 I think I rerouted it because of the skinning, by default that goes to the flash module's resources.

But yeah, see if it works on the default one. It could be something that changed with Laravel 7 and that library being updated.

**Comment by nickkecooper** [comment]
Looks like its broken on the default theme as well.

**Comment by nickkecooper** [comment]
@web541 Your suggestion fixed this!

**Comment by web541** [comment]
@nabeelio Ahhh ok. It's also listed as `flash::message` in your [admin/settings/index.blade.php](https://github.com/nabeelio/phpvms/blob/59d09c0cec1bc06fbab74633cab53839ca5c49c6/resources/views/admin/settings/index.blade.php#L5) file. Not sure which one you would prefer.

**Comment by nabeelio** [comment]
Did it respect the skin? I might've made a mistake, then.

**Comment by nickkecooper** [comment]
```
@include('flash::message')
```

That worked with my custom skin.

**Comment by nickkecooper** [comment]
Well nope that actually breaks it when you visit the site for the first time with no cache.

**Comment by nabeelio** [comment]
Looks like using `flash::message` isn't going to the skin

**Comment by nabeelio** [comment]
So there were updates to the original templates I had to bring in. Should be fixed now. Those templates were updated 3 years ago... didn't seem like that long ago! Heh

**Comment by nickkecooper** [comment]
It looks like now the only flash error message I get, is when I visit an admin page without being an admin. I get the following:

```
Facade\Ignition\Exceptions\ViewException
Call to a member function toArray() on array (View: /home/virtualual/phpvms/resources/views/layouts/vual/flash/message.blade.php)
```
