### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by nickkecooper** [nabeelio/phpvms#741]
I am having an issue where my date scripts were not showing items of things on today's date. I went ahead and checked the time with a php function. My time seems to be off by 6 or 7 hours. When I check my servers time it is correct.

Is there anywhere I can go to change the time correctly for my timezone?

**Comment by nabeelio** [comment]
All times are stored in UTC. In your profile, is the timezone set to your own? If you convert it from UTC to your local, are they correct?

**Comment by nickkecooper** [comment]
@nabeelio I just changed my profile to be NY but I still get the time being 2020-06-04 when I add this line.

```
$today = today()->format('Y-m-d');
echo $today;
```

**Comment by nickkecooper** [comment]
I came across this as I want the events (module I am creating) to still show on the date of the event. It was working for most of the day, but because of the sight difference it disappeared.

**Comment by web541** [comment]
I could be wrong but I think `today()` would take the timezone set in the app.php file which should be UTC. I know there's a phpVMS helper called show_date() that accepts a date string or Carbon instance, but it only returns a string and not a Carbon instance so you wouldn't be able to format it (unless you created another Carbon date off the new string).
For example:
```
show_date(today()) // returns string, but not in your format
show_date(today())->format('Y-m-d'); // ideal scenario if it returned a Carbon instance

// Or
use Illuminate\Support\Facades\Auth;

$timezone = Auth::user()->timezone ?: 'UTC';
$date = today()->timezone($timezone); // Carbon instance of today's date
$date->format('Y-m-d'); // returns formatted string
```

Not sure if there's a phpVMS "default date format" setting somewhere that changes it by default or if there's another helper hidden away.

**Comment by nabeelio** [comment]
@web541 is correct, there is a [show_date()](https://github.com/nabeelio/phpvms/blob/dev/app/helpers.php#L236) helper which should be used to show the date. It will output it in "Dec 25, 1975" type format; it'll end up calling the `toFormattedDateString()` Carbon date method

I can maybe add a `show_datetime_format(string|Carbon $datetime)` method. I suggest always using Carbon, it just makes things easier

**Comment by web541** [comment]
Yeah that would be great

**Comment by nickkecooper** [comment]
Thanks for the tips guys. It looks like running this:

```
         $timezone = Auth::user()->timezone ?: 'UTC';
         $date = Carbon::now($timezone);
         $today = $date->format('Y-m-d h:i');
```

Is doing the trick. I will need to default this to NewYork if a user is not logged in. But Ill let you know if this seems to be the final work around.

Thanks!

**Comment by nickkecooper** [comment]
@nabeelio Would this work as well?

```
         if (isset(Auth::user()->timezone)){
         $timezone = Auth::user()->timezone ?: 'UTC';
         }else{
         $timezone = "America/new_york";
         }
         $date = Carbon::now($timezone);
         $today = $date->format('Y-m-d h:i');
```

**Comment by nabeelio** [comment]
I would do the auth check the way I'm doing it:

https://github.com/nabeelio/phpvms/blob/dev/app/helpers.php#L302

The problem with yours is that if `Auth::user()` is null, calling `->timezone` will fail/cause an exception

**Comment by nabeelio** [comment]
You can also use `optional()` - 

```php
$timezone = optional(Auth::user())->timezone ?? 'America/New_York';
```
