### ISSUE TITLE
Unable to clear Cache

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#759]
In the latest dev a error is thrown when trying to clear the Application cache:

LogicException
Unable to prepare route [logout] for serialization. Another route has already been assigned name [logout]. 

https://flareapp.io/share/DPy8Z6m9

**Comment by nabeelio** [comment]
Is this through the admin panel?

**Comment by ollimaz** [comment]
Yes its a new and clean install and through the admin panel

**Comment by ollimaz** [comment]
Error still occurs with latest dev-branch: 
https://flareapp.io/share/VP6aNRmJ

**Comment by nabeelio** [comment]
Reference for myself: https://github.com/Laravel-Backpack/CRUD/issues/2523
