### ISSUE TITLE
Error thrown on login with not existing PilotID

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#760]
When trying to Login with a PilotID that does not exist a error is thrown:

ErrorException
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior 

see: https://flareapp.io/share/RmrkGbPz

**Comment by nabeelio** [comment]
What're you entering? A blank string?

**Comment by nabeelio** [comment]
And what's the airline IATA?

**Comment by ollimaz** [comment]
> What're you entering? A blank string?

Every String without "@" causes this error

**Comment by ollimaz** [comment]
> And what's the airline IATA?

It was on a fresh install of phpvms. I Think no IATA has been set

**Comment by nabeelio** [comment]
Weird, I'm not seeing this but it could be the blank IATA. Thanks, I'll have a patch for that soon

**Comment by nabeelio** [comment]
Please try the latest dev if you get a chance

**Comment by ollimaz** [comment]
Ok... the next Chance is in about 2 Weeks... i will test it
