### ISSUE TITLE
Add weight to aircraft editor

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#775]
**Is your feature request related to a problem? Please describe.**
No

In "Aircraft Information" we have:
> Name: 
> IATA:
> ICAO:
> Registration:

But Weight is missing.
In Fares section there a field that say:

> "Capacity: Max seats or capacity available. This can be adjusted in the subfleet"

But this options is missing too.

**Describe the solution you'd like**
Add missing fields MTOW and Seats (may be by class? Economy, First, Bussines or user write field?)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nabeelio** [comment]
Seats are handled by fares. I will add MTOW

**Comment by arv187** [comment]
http://phpvms7.argavirtual.com/admin/aircraft/1 
```
BadMethodCallException
Method Illuminate\Validation\Validator::validateNumber does not exist.
```
```
Illuminate\Validation\Validator::__call
vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1382
```

**Comment by nabeelio** [comment]
Sorry, should be fixed in the new dev
