### ISSUE TITLE
Add language option to nav bar

### ISSUE THREAD

**Issue by hcshires** [nabeelio/phpvms#777]
**Describe the solution you'd like**
Since phpvms supports multiple languages, it would be useful to add the option for site users to select their language of choice. Particularly, adding an option on the nav bar or in an additional location that's easily accessible would be a huge advantage when running airlines that are international.

**Describe alternatives you've considered**
Other options may be adding /{your_language}/ to the URL or adding a setting in the Admin panel

**Comment by ollimaz** [comment]
Does #1020 solve this issue?

**Comment by hcshires** [comment]
Yes it does
