### ISSUE TITLE
Can't install phpvms because of SQL-Error / no SQLLite installation possible

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#779]
When Trying to install phpvms I always get the following error:
`Illuminate\Database\QueryException {#3418 ▼
  #sql: "alter table `phpvms_airlines` drop index `airlines_iata_unique`"
  #bindings: []
  #message: "SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'airlines_iata_unique'; check that column/key exists (SQL: alter table `phpvms_airlines` drop index `airlines_iata_unique`) ◀"
  #code: "42000"
  #file: "/var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
  #line: 671
  -previous: Doctrine\DBAL\Driver\PDOException {#3534 ▶}
  +errorInfo: array:3 [▼
    0 => "42000"
    1 => 1091
    2 => "Can't DROP 'airlines_iata_unique'; check that column/key exists"
  ]
  trace: {▼
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Connection.php:631 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Connection.php:465 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php:102 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:290 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php:151 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/app/Database/migrations/2020_03_28_174238_airline_remove_nullable.php:13 {▼
      AirlineRemoveNullable->up() …
      ›         $table->dropUnique('airlines_iata_unique');
      ›     });
      › }
      arguments: {▶}
    }
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:392 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:401 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:200 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:165 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:110 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:72 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:541 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:81 {▶}
    Illuminate\Database\Console\Migrations\MigrateCommand->handle() {}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:37 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Container/Util.php:37 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:95 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:39 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php:596 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php:134 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/symfony/console/Command/Command.php:258 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php:121 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/symfony/console/Application.php:911 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/symfony/console/Application.php:264 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/symfony/console/Application.php:140 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php:93 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php:185 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:263 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/app/Services/Installer/MigrationService.php:68 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/modules/Installer/Http/Controllers/InstallerController.php:249 {▶}
    Modules\Installer\Http\Controllers\InstallerController->dbsetup() {}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php:239 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php:196 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:685 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/app/Http/Middleware/SetActiveTheme.php:40 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:116 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:62 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/app/Http/Middleware/InstalledCheck.php:29 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:687 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:662 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:628 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php:617 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:165 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:58 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:63 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/app/Http/Middleware/TrustProxies.php:38 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:140 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:109 {▶}
    /var/www/vhosts/royalevest.de/httpdocs/public/index.php:23 {▶}
  }
}`

All credentials are correct.
Futhermore you can't select sqllite. When clicking next on the installer with sqllite selected noting happens...

EDIT: Occurs only when a database prefix is set!!!!

**Comment by nabeelio** [comment]
I haven't tested sqlite in a while. You're trying to install to that? I need to remove it from the installer. Unless you're intending to use sqlite?

**Comment by ollimaz** [comment]
No I'm not using it. I just thought I'll give it a try. You can remove it
