### ISSUE TITLE
Navbar button on mobile admin page doesn't work

### ISSUE THREAD

**Issue by hcshires** [nabeelio/phpvms#782]
**Describe the bug**
This bug is only present when viewing phpVMS on a mobile device or mobile viewport. The 3-line icon button to open the nav page in the admin panel does nothing, disabling the user to access other admin pages easily

**Version**
v7.0.0beta4

**To Reproduce**
1. Go to the admin page on a mobile-sized viewport
2. Attempt to click on the "3-line" nav button
3. Observe nothing resembling a navbar is displayed

**Expected behavior**
The nav bar to navigate through pages in the Admin panel should open when the button is clicked

**Screenshots**
![image](https://user-images.githubusercontent.com/25646224/89350848-64920e80-d676-11ea-96c2-a3ef473d099f.png)

**Comment by ArthurHetem** [comment]
@nabeelio , cant reproduce here, probably #994  fixed.

**Comment by nabeelio** [comment]
ty
