### ISSUE TITLE
Cron error

### ISSUE THREAD

**Issue by arv187** [nabeelio/phpvms#784]
**Describe the bug**
1. In manteinance -> cron I get a error:
* * * * * cd /home/argavirt/phpvms7.argavirtual.com && /opt/cpanel/ea-php73/root/usr/bin/php artisan schedule:run >> /dev/null 2>&1
There was a problem running the cron; make sure it's setup and check logs at storage/logs/cron.log. See the docs

2. I did clear all caches and Get this: 
Unable to prepare route [logout] for serialization. Another route has already been assigned name [logout].
http://phpvms7.argavirtual.com/ 

Illuminate\Routing\AbstractRouteCollection::addToSymfonyRoutesCollection
vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:212

```
            $this->add($route);

        } elseif (! is_null($symfonyRoutes->get($name))) {

            throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
```

----------------

3. In pilot profile:

Facade\Ignition\Exceptions\ViewException
Undefined variable: userFields (View: /home/argavirt/phpvms7.argavirtual.com/resources/views/layouts/default/profile/index.blade.php)
http://phpvms7.argavirtual.com/profile/2 

Possible typo $userFields
Did you mean $user?

$userFields is undefined
Make the variable optional in the blade template. Replace {{ $userFields }} with {{ $userFields ?? '' }}

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
resources/views/layouts/default/profile/index.blade.php:136
`@foreach($userFields as $field)`

**Version**
7.0.0-dev+200813.e5ed66

**To Reproduce**
Described above

**Expected behavior**
No errors

**Screenshots**

**Additional context**
/phpvms7.argavirtual.com/storage/logs
[laravel-2020-08-13.log](https://github.com/nabeelio/phpvms/files/5071462/laravel-2020-08-13.log)

Server is a shared hosting, maind domain with phpvms v2, subdomain with phpvms v7, updated uploading files and executing update option in admin panel DB don't changed (previous version installed 2020/07/Jun).

**Comment by nabeelio** [comment]
Dupe #759
