### ISSUE TITLE
Livemap: Map info box does not appear after clicking on a plane

### ISSUE THREAD

**Issue by hcshires** [nabeelio/phpvms#791]
**Describe the bug**
When clicking on a plane in the livemap widget, the map info box (transparent gray div on the bottom portion of the map that displays flight/pirep-specific information) does not appear. The class "map-info-box" has a display: none CSS property that is not cleared when the onClick event is triggered.

**Version**
v7.0.0.dev-latest-build

**To Reproduce**
1. Go to /livemap
2. Click on a plane icon that represents a live flight
3. Observe that the flight-specific box does not appear

**Expected behavior**
The map info box should appear when a flight/plane is clicked on.

**Screenshots**
Expected behavior:
![unknown-2.png](https://user-images.githubusercontent.com/25646224/90414232-21bc3780-e075-11ea-864a-a49107e8084e.png)

Actual Result:
![unknown.png](https://user-images.githubusercontent.com/25646224/90414154-081af000-e075-11ea-8d27-64cd13ee531e.png)

**Comment by MANFahrer-GF** [comment]
when is a solution to be expected

**Comment by nabeelio** [comment]
When I get around to it, this is lower on the priority list
