### ISSUE TITLE
users receiving e-mails but administrators are not.

### ISSUE THREAD

**Issue by stickbear2015** [nabeelio/phpvms#795]
a friend and I are starting up a virtual airline, based on PHPVMS 7. We're running into a weird problem where, when emails are sent through Mailgun, when someone registers, the new user gets an email, but administrators don't. The logs are not helpful, as they don't show any errors. We're using the latest PHPVMS 7 from Git, Debian 10, PHP 7.3, Apache. Any advice?
We were originally pointed at issue #675 but that issue was closed as fixed, so that doesn't seem to be the issue.

**Comment by nabeelio** [comment]
#722 is what I was thinking of. I have to investigate this one, I believe it's a code issue

**Comment by nabeelio** [comment]
It seems to me this is working, those users do have the admin role?

![image](https://user-images.githubusercontent.com/99736/92129366-69f78b80-edd1-11ea-81f6-88bba923812d.png)
