### ISSUE TITLE
When I was installing, when I click to go to the installation program, I reported an error of 404

### ISSUE THREAD

**Issue by donggua2096** [nabeelio/phpvms#796]
When I was installing, when I click to go to the installation program, I reported an error of 404

**Comment by nabeelio** [comment]
Can you check this on the uploading of files? It's likely a htaccess thing with your host


https://docs.phpvms.net/installation/installation

**Comment by donggua2096** [comment]
Please help me to see if the pictures are all in，Thanks






生活
wangxuan244@qq.com



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nabeelio/phpvms"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月30日(星期天) 凌晨0:28
收件人:&nbsp;"nabeelio/phpvms"<phpvms@noreply.github.com&gt;;
抄送:&nbsp;"A-----1a"<2096155326@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nabeelio/phpvms] When I was installing, when I click to go to the installation program, I reported an error of 404 (#796)





 
Can you check this on the uploading of files? It's likely a htaccess thing with your host
 
https://docs.phpvms.net/installation/installation

**Comment by donggua2096** [comment]
I didn't find these under home
/home/youruser
  phpvms
  public_ftp
  public_html

**Comment by nabeelio** [comment]
That's an example. Are you on cPanel?

**Comment by donggua2096** [comment]
No, I uploaded it directly

**Comment by nabeelio** [comment]
Sure, but do you use cPanel? Or your using a virtual host within Apache or nginx?

**Comment by donggua2096** [comment]
nginx

**Comment by donggua2096** [comment]
Here is the content of htaccess
# Disable index view
Options -Indexes

RewriteEngine On

# Handle Authorization Header
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

# Deny all these files/folders
RedirectMatch 403 ^/.git/.*?$
RedirectMatch 403 ^/.travis/.*?$
RedirectMatch 403 ^/app/.*?$
RedirectMatch 403 ^/bootstrap/.*?$
RedirectMatch 403 ^/config/.*?$
RedirectMatch 403 ^/modules/.*?$
RedirectMatch 403 ^/node_modules/.*?$
RedirectMatch 403 ^/resources/.*?$
RedirectMatch 403 ^/storage/.*?$
RedirectMatch 403 ^/tests/.*?$
RedirectMatch 403 ^/vendor/.*?$
RedirectMatch 403 ^/.bowerrc$
RedirectMatch 403 ^/.env
RedirectMatch 403 ^/artisan$
RedirectMatch 403 ^/composer.json
RedirectMatch 403 ^/composer.lock
RedirectMatch 403 ^/composer.phar
RedirectMatch 403 ^/env.php.*?$
RedirectMatch 403 ^/env.php
RedirectMatch 403 ^/env.php$
RedirectMatch 403 ^/Makefile
RedirectMatch 403 ^/package.json
RedirectMatch 403 ^/package-lock.json
RedirectMatch 403 ^/phpunit.xml
RedirectMatch 403 ^/webpack.mix.js
RedirectMatch 403 ^/yarn.lock

RewriteRule ^(.*)$ public/$1 [L]

**Comment by donggua2096** [comment]
Is there a solution?

**Comment by nabeelio** [comment]
On nginx, point the vhost to the public directory. I need to add that to the docs

**Comment by nabeelio** [comment]
I've updated the docs here to include a sample nginx vhost configuration that's similar to what I use on the demo site:

https://docs.phpvms.net/installation/vhost#nginx

**Comment by donggua2096** [comment]
This is the configuration file of the site. How do you want to change it
server
{
    listen 80;
    server_name 111.67.207.17;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/111.67.207.17;
    
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #SSL-END
    
    #ERROR-PAGE-START  错误页配置，可以注释、删除或修改
    error_page 404 /404.html;
    error_page 502 /502.html;
    #ERROR-PAGE-END
    
    #PHP-INFO-START  PHP引用配置，可以注释或修改
    include enable-php-72.conf;
    #PHP-INFO-END
    
    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    include /www/server/panel/vhost/rewrite/111.67.207.17.conf;
    #REWRITE-END
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log off;
    }
    
    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log off; 
    }
    access_log  /www/wwwlogs/111.67.207.17.log;
    error_log  /www/wwwlogs/111.67.207.17.error.log;

**Comment by donggua2096** [comment]
This is the site directory/www/wwwroot/111.67.207.17

**Comment by donggua2096** [comment]
I have this problem
ERROR:
nginx: [emerg] "server" directive is not allowed here in /www/server/nginx/conf/vhosts/111.67.207.17.conf:1
nginx: configuration file /www/server/nginx/conf/nginx.conf test failed

**Comment by nabeelio** [comment]
You need to put the `server {}` blocks in a separate vhost. I would look up a tutorial on setting up nginx vhosts, it could be different on your distro
