### ISSUE TITLE
Flight database

### ISSUE THREAD

**Issue by lorlandi** [nabeelio/phpvms#818]
Regarding flights database. There is a column called "visible" which in the administration panel cannot be changed.
I updated the flights database via CSV several times and in some cases there are flights that do not appear on the page because they are entered as "visible 0". On the left side there is another column called "active" and all flights are at "1".
Will be possible to add the function of editing the "visible" column in the control panel?

Thanks.

**Comment by nabeelio** [comment]
Ok, I think `visible` is an internal field. I have to figure out what the fix is

**Comment by nabeelio** [comment]
Try the latest dev, I'll just brute force it to true.

**Comment by lorlandi** [comment]
Solved, old database was deleted and imported with visible flag to "1" now all flights are visible.
Great and Thanks
