### ISSUE TITLE
Unable to remove alternate airport

### ISSUE THREAD

**Issue by dotalchemy** [nabeelio/phpvms#820]
**Describe the bug**
When creating a route, if an alternate airport is added, it cannot be removed - no option to return that field to blank is available.

**Version**
7.0.0-beta.4

**To Reproduce**
Add a flight
Select an alternate airport
Attempt to change it to blank

**Expected behavior**
A blank airport should be selectable to remove the current alternate and set the flight back to being without alternate.

**Comment by YashGovekar** [comment]
> **Describe the bug**
> When creating a route, if an alternate airport is added, it cannot be removed - no option to return that field to blank is available.
> 
> **Version**
> 7.0.0-beta.4
> 
> **To Reproduce**
> Add a flight
> Select an alternate airport
> Attempt to change it to blank
> 
> **Expected behavior**
> A blank airport should be selectable to remove the current alternate and set the flight back to being without alternate.

If you see correctly, there is a little blank space above the first airport in that list. Just click on it.

**Comment by FatihKoz** [comment]
This should be closed too, selecting the blank was possible back then and still possible (with latest dev of course, not sure about the beta4)
