### ISSUE TITLE
Flight database and User Database data reset

### ISSUE THREAD

**Issue by lorlandi** [nabeelio/phpvms#823]
After "Clean up of phpvms backups" and "Successful new backup of phpvms" both messages sent by Cpanel, "User" database were reset to "0" on flights, flight_time and transfer_time. This issue was checked on Sept. 11 and 12th.
On "flights" database some flights were rest to "visible" flag to "0".

Sample message as follow:
Hello!
Great news, a new backup of phpvms was successfully created on the disk named local.
Application name: phpvms
Backup name: phpvms
Disk: local
Newest backup size: 120.08 MB
Number of backups: 6
Total storage used: 740.97 MB
Newest backup date: 2020/09/13 02:03:07
Oldest backup date: 2020/09/06 02:01:45

Regards,
phpvms

**Comment by nabeelio** [comment]
Sorry I'm a little lost, what's happened?

**Comment by lorlandi** [comment]
Every 24 hours this message appears in my admin email and when checking my site all pilots appear with 0 hours, 0 flights and some flights are not visible.
I have reset the databases twice and after 24 hours the data mentioned appears in 0 again

**Comment by nabeelio** [comment]
Is the cron setup? Can you attach the laravel and cron logs from the storage/logs folder?

**Comment by lorlandi** [comment]
Here the logs.
[cron-2020-09-11.log](https://github.com/nabeelio/phpvms/files/5215419/cron-2020-09-11.log)
[cron-2020-09-12.log](https://github.com/nabeelio/phpvms/files/5215420/cron-2020-09-12.log)
[cron-2020-09-13.log](https://github.com/nabeelio/phpvms/files/5215422/cron-2020-09-13.log)
[laravel-2020-09-09.log](https://github.com/nabeelio/phpvms/files/5215423/laravel-2020-09-09.log)
[laravel-2020-09-11.log](https://github.com/nabeelio/phpvms/files/5215424/laravel-2020-09-11.log)
[laravel-2020-09-12.log](https://github.com/nabeelio/phpvms/files/5215425/laravel-2020-09-12.log)

**Comment by nabeelio** [comment]
Thanks, so when it's exported, the current flag states are exported too. If you re-add, does it fix itself the next day?

**Comment by lorlandi** [comment]
So far I have only uploaded the user table again. If do you mean after upload the table again,  all data is present till the nightly cron, after that all data is in 0 hours and 0 flights
I'll upload the user table tonight again.

**Comment by nabeelio** [comment]
I'm not sure what you're trying to do though. It seems like the backups aren't complete?

**Comment by lorlandi** [comment]
I am just trying that the data transferred to the user database not erased every night. I have only transferred the deleted data again and again. That is my query. Why are these data, flights and hours deleted every night?
I have not touched the programming code, I have not done backups and nothing that my hands can cause problems.

**Comment by nabeelio** [comment]
What's transferring it? The cron built in isn't deleting anything

**Comment by lorlandi** [comment]
The data transferred are all the "users" data with the total flights of each one, flight time and transfer hours form the old PHPVMS V5. All data was entered according thew new structure of database.

**Comment by lorlandi** [comment]
![20200915_210426](https://user-images.githubusercontent.com/4042146/93280726-a7302600-f7a0-11ea-91b4-d6b668e92aca.jpg)
Before cron

**Comment by nabeelio** [comment]
You have to use the importer. There's a lot of data. You can use the command line importer

**Comment by lorlandi** [comment]
Thanks i'll try that .

**Comment by nabeelio** [comment]
The tables are a lot more tied together and a missing relationship can throw things out of wack
