### ISSUE TITLE
Trying to get property 'name' of non-object

### ISSUE THREAD

**Issue by xPerr0** [nabeelio/phpvms#824]
When i make an report with an aircraft and then i remove the aircraft error incoming going to dashboard or any page where it calls to this "aircraft".

**Comment by nabeelio** [comment]
Yeah there's an open issue with needing to block the aircraft delete if it's been used

**Comment by nabeelio** [comment]
Well you probably have to go directly into the admin (`/admin`) and remove the PIREP or try to edit it to change the aircraft.

**Comment by xPerr0** [comment]
Same error when i try to modify that pirep from admin panel, and i dont see the "button" to remove the pirep :S

**Comment by nabeelio** [comment]
Sorry - try rejecting it. That will block it from showing up in the frontend.

**Comment by xPerr0** [comment]
Still the error, i tried to accepting and rejecting it again and still the error.

**Comment by nabeelio** [comment]
Ok, I might have to do a patch for you directly to dev

**Comment by xPerr0** [comment]
thanks a lot!! <3

**Comment by nabeelio** [comment]
See if this works out

**Comment by xPerr0** [comment]
/resources/views/admin/pireps/fields.blade.php
it seems here is the error. I made all changes u told me in the 3 files and still the problem.
i let you an gyazo link: https://gyazo.com/41bc59417c22ef37824ac49a75e9ef30

**Comment by nabeelio** [comment]
Another commit to fix that

**Comment by xPerr0** [comment]
Well, im starting to comprend how this works. I cleared the error in fields.blade.php, now says a similar error in pirep_card.blade.php Im still changing the line:
<td>{{ $pirep->aircraft->name }}
   ({{ $pirep->aircraft->registration }})
</td>
for:
<td>{{ optional($pirep->aircraft)->name }}
   ({{ optional($pirep->aircraft)->registration }})
</td>
of all errors. At the moment, with the code that u post, i can enter to modify the pirep, but i still cant delet de manual pirep.

Thanks for fast responding so fast, im still working to solve it!

**Comment by nabeelio** [comment]
Yes there's another issue, #778, which I need to complete. Maybe I'll do that one soon and that should resolve the main issue

**Comment by xPerr0** [comment]
I just solve the issue wich broke the main dashboard website, just adding that u said [optional()] before aircraft name...
But i really need the delete button on rejected pireps (manual at least). Thanks for the help, my issue is solved.

Offtopic question: Does it supports (phpvms7) smartCARS 2?? 

Thanks 4 all nabeelio! ;)

**Comment by nabeelio** [comment]
It does not support phpvms 7

**Comment by nabeelio** [comment]
Ok, glad you got it fixed. I'll fix the other issues under that other ticket
