### ISSUE TITLE
Feature Request: Deletion of PIREPS for admins

### ISSUE THREAD

**Issue by JanPlays** [nabeelio/phpvms#827]
![image](https://user-images.githubusercontent.com/38027694/93362561-74ae2800-f889-11ea-90d7-1691e0b63f0b.png)

I am requesting that phpvms has the "Delete" button. it might have a lot of benefit to clean up rejected and removed "Rejected PIREPS"

**Comment by nabeelio** [comment]
Hey, this is a duplicate of #778, going to close this in favor of that one
