### ISSUE TITLE
Default values for automatically added airports

### ISSUE THREAD

**Issue by dotalchemy** [nabeelio/phpvms#829]
When importing airports from CSV / automatically looking up and adding from Flights import, an airport added has no ground handling value and no Jet-A price.

![image](https://user-images.githubusercontent.com/2215009/93690754-d9879f00-fa90-11ea-8e77-2a322e79a876.png)

Add a default option for ground handling and Jet-A for use during airport importing / automatic addition.

- if value in CSV == missing, use global default
- if value in CSV != missing, use CSV value even if 0
- if value in settings == missing, continue using empty

**Comment by nabeelio** [comment]
@YashGovekar This is another one you can look at. You'll need to add additional unit tests to make sure that the default values are being used if filled in values are missing.

**Comment by YashGovekar** [comment]
Hey @nabeelio  , not so much aware of the tests, although I'll try making one.
Also, I doubt that the `App\Services\Importers\AirportImporter` not being used in the importer proccess right?

**Comment by nabeelio** [comment]
It's being used. I'll try to give some guidance on the tests in a bit

**Comment by YashGovekar** [comment]
Okay, thanks.
