### ISSUE TITLE
User rank not auto promoted changes

### ISSUE THREAD

**Issue by 21Insight** [nabeelio/phpvms#838]
In my airline we have 6 ranks, but only rank 1 has self-promotion, however I assigned manually rank 6 but I do not have the required hours; at the moment of sending a pirep from ACARS it automatically resets my rank to 1 even having the remaining hours for self-promotion to rank 2

**Comment by 21Insight** [comment]
I just noticed that the range is reset when I start the flight with ACARS, because now I am flying with an aircraft that is only rank 6, but the system has already changed me to rank 1.

**Comment by nabeelio** [comment]
Hey, so I added a test in this PR to try to duplicate this: https://github.com/nabeelio/phpvms/pull/840
But I haven't been able to dupe this and have been trying on the demo site too

**Comment by 21Insight** [comment]
A few hours ago I was doing tests with the branch, it continues generating me the error, I am going to try something that seems a little absurd, but that we had always done and was to eliminate that range 1 by default that includes the system. And then I will expose the results and if not I will record a video where it is appreciated what happens.
