### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by Botric** [nabeelio/phpvms#841]
**Is your feature request related to a problem? Please describe.**
The key will show as default when on 1080P in browser, 
**Describe the solution you'd like**
For the key to be hidden,
**Describe alternatives you've considered**
Making the text the same colour as the background would work, however more advance option would be for a click to revel and a click to copy (same type of feature that firefox has when saving password) where the key does not need to be reveled all the time,

**Additional context**
image added for context 

![image](https://user-images.githubusercontent.com/66216920/94371028-4b906180-00eb-11eb-9568-29aff218220e.png)

**Comment by nabeelio** [comment]
Good idea

**Comment by Botric** [comment]
thanks for this is perfect
