### ISSUE TITLE
Skip Registration

### ISSUE THREAD

**Issue by VxnceF** [nabeelio/phpvms#850]

**Comment by vgpastor** [comment]
This problem are based in Laravel reseting password proccess.
[](https://laravel.com/docs/7.x/passwords#after-resetting-passwords)

By default Laravel LogIn user when this reset his account. I thin k that the better solution can be in login controller if the user it's not active the session are logout and redirect user to login.

This comprobation of that the user are active can be improved in a middleware to prevent the sessión has been used to access directly to others pages that don't control the status of the user.

**Comment by nabeelio** [comment]
Nice find, @vgpastor. There's a couple of choices;

- I think we can redirect them to `/logout`, maybe to an intermediate page where it logs them out, and forwards them to login
- Middleware which checks the user's access level, this might be the better option but requires some more work.

What do you guys think?

**Comment by learn-by-flying** [comment]
@nabeelio  I'd write an if statement and use the Auth::logout($user) the either show a view that the user is not registered or send him to the page.

**Comment by nabeelio** [comment]
I'll try to get to this one soon to see if there was an option in Laravel about the behaviour

**Comment by nabeelio** [comment]
This should stay open

**Comment by nabeelio** [comment]
Deferring to #568
