### ISSUE TITLE
CSS Class 'table-condensed' causing a visual bug

### ISSUE THREAD

**Issue by Botric** [nabeelio/phpvms#854]
**Describe the bug**
'table-condensed' is referd to in the Priep_card.blade.php is being used on the 'your last report' section of the dashboard page, this is causing all sections covered under this to be blank however the data is still being plullled, 
/resources/views/layouts/default/dashboard/index.blade.php (L79)
/resources/views/layouts/default/dashboard/pirep_card.blade.php (L40)

 I am also unable to see where the CSS Class is being defined 

**Version**
Current

**To Reproduce**

Code but still active 

**Expected behavior**

for the data to be shown 

**Screenshots**

https://imgur.com/a/ooybOPr
images of the affected code 

the layour works fine if this class is removed and all data is shown

**Comment by Da-Geek** [comment]
So the Dashboard look like this right now https://i.imgur.com/x4K72Fj.png
but should look like this https://i.imgur.com/8LeJX39.png

**Comment by nabeelio** [comment]
Yeah this was on purpose for the front page, designed to look more 'minimal' from the regular table.

**Comment by Botric** [comment]
@nabeelio, looked into the issue and the current look is 
![image](https://user-images.githubusercontent.com/66216920/95395279-27f0c680-08f6-11eb-9444-d765cec9abd5.png)
with the hidden items being shown would look like this 
![image](https://user-images.githubusercontent.com/66216920/95395333-4787ef00-08f6-11eb-8a85-eb1fd67e672f.png)
Action removal of `              <table class="table-condensed" width="100%">` from line 40 of pirep_card.blade.php
for a minimal look 
![image](https://user-images.githubusercontent.com/66216920/95395658-093eff80-08f7-11eb-9a66-f7021a99d885.png)
has been proposed with a new layout and a less 'clunky' look #857

**Comment by nabeelio** [comment]
How does that look on the main PIREPs page? Since they share the same "card" template. Maybe those should be split up?

**Comment by Botric** [comment]
> 
> 
> How does that look on the main PIREPs page? Since they share the same "card" template. Maybe those should be split up?

event with th changes to the blade there is no changes made to layout 
<admin pannel>
![image](https://user-images.githubusercontent.com/66216920/95663192-0598bc00-0b35-11eb-8181-ade776268961.png)
<pirep page>
![image](https://user-images.githubusercontent.com/66216920/95663211-337e0080-0b35-11eb-8232-3230780271ca.png)
<inside pirep > 
![image](https://user-images.githubusercontent.com/66216920/95663218-4abcee00-0b35-11eb-81b8-9a0036c7c595.png)

 is there any other places that the card is used?
