### ISSUE TITLE
Award based on PIREP DEP & ARR Airport?

### ISSUE THREAD

**Issue by Da-Geek** [nabeelio/phpvms#860]
**Describe the solution you'd like**
I would like to create some Awards, that is given if a PIREP is created based on a specific Departure and Arrival Airport.

**Additional context**
I have a bunch "Tours" that are 3 or 5 Legs long,
I want my pilots to be able to fly 1 or more of the legs, and for each
leg they get an Award ONLY if the flight has the correct Departure and Arrival Airports.

**Comment by Da-Geek** [comment]
I think this might need to be another "Award Class", I just need a little help with how to full the PIREP info
during the check() function, and I might be able to create the AwardClass myself, the Award Documentation
URL is showing a 404 right now.

**Comment by nabeelio** [comment]
Yes that would be an award class. Docs are here: https://docs.phpvms.net/developers/awards
See https://docs.phpvms.net/developers/awards#accessing-information for how you can access the user and the last PIREP.

**Comment by Da-Geek** [comment]
Yup it looks like it has enough info in that Document to get me started creating another Award Class, to grab the PIREP info, I'll have a play around with some code and see if I can get it going.
A bit of a blocker for me is not having a clear way to display the current Awards issued to a Pilot, I know I can look at {{ $user->awards }} to give an array, I just need to work out how to Display that in a Friendly way

**Comment by YashGovekar** [comment]
> **Describe the solution you'd like**
> I would like to create some Awards, that is given if a PIREP is created based on a specific Departure and Arrival Airport.
> 
> **Additional context**
> I have a bunch "Tours" that are 3 or 5 Legs long,
> I want my pilots to be able to fly 1 or more of the legs, and for each
> leg they get an Award ONLY if the flight has the correct Departure and Arrival Airports.

You can also add a PIREPAccepted EventListener for your Tour assuming that it is inside your modules folder.

**Comment by nabeelio** [comment]
Like @YashGovekar said, an award class for this probably isn't the best way, though you could do it but it would require a lot of setup. The tour module could just assign a user an award based on some parameters. I might have to expand on this a bit, I have to think about it. I might just change the `user_awards` table a bit.
