### ISSUE TITLE
[Feature Request] VMSAcars Client Download Option via VMS

### ISSUE THREAD

**Issue by Da-Geek** [nabeelio/phpvms#876]
**Describe the solution you'd like**
I would like a feature added to the **VMSAcars Module** that adds a Download Option for Pilots to allow them
to get the VMSAcars.exe from VMS Directly, without an Admin having to share random .exe's around via
Discord/E-Mail and other methods.
Maybe an option in the Module to Allow the admin to upload a version that Pilots can download?

**Describe alternatives you've considered**
I guess this links in with the PR https://github.com/nabeelio/phpvms/pull/875
Once we get a "File Manager" type option we could of course use that, But I was thinking something
a little more integrated and Official with the Module.

**Comment by Da-Geek** [comment]
I know this repo dose not have the VMSAcars Module in it, but this seemed like a good place to add the Feature Request.

**Comment by nabeelio** [comment]
Yes, it likely would go with the generic module where it can be uploaded. I haven't decided how I want to make it available yet since it's behind the protected store paywall at the moment.

**Comment by nabeelio** [comment]
Closing for now, will address this as part of the downloader
