### ISSUE TITLE
Avatar is not uploading

### ISSUE THREAD

**Issue by medibasti05** [nabeelio/phpvms#887]
The Avatar on Profile is not uploading, there is also no error reporting.

**Comment by Da-Geek** [comment]
Unable to reproduce this issue on my install of VMS.
I am able to swap and change my avatar without issue.
![Screenshot 2020-10-23 14 39 36](https://user-images.githubusercontent.com/6429103/97011027-15090380-153e-11eb-92c3-da9bd730613a.png)
![Screenshot 2020-10-23 14 40 22](https://user-images.githubusercontent.com/6429103/97011028-15a19a00-153e-11eb-9c6b-0ecbb6661466.png)
![Screenshot 2020-10-23 14 40 48](https://user-images.githubusercontent.com/6429103/97011030-15a19a00-153e-11eb-9c50-352d87ec021f.png)

**Comment by Da-Geek** [comment]
All I could suggest is check the permissions on the /public/uploads & /public/uploads/avatars directories, and of course
the permissions of your current avatar image (for you you @medibasti05 you should find a file called NDF11.png I am guessing)

Your webserver user needs to have Read & Write access to the /public/uploads directory and everything below it.

**Comment by medibasti05** [comment]
@Da-Geek i will check that, thanks for help

**Comment by medibasti05** [comment]
@Da-Geek But when permissions are not given how can i upload other files?

**Comment by Da-Geek** [comment]
> @Da-Geek But when permissions are not given how can I upload other files?

I am not 100% sure what this means.
I am have idea how your server side is setup, or what permission you currently have on any file or folder.
All I can do is try to work out what might be going on, My initial reaction to this issue you are having would
have to be "are the file/directory permissions correct?"
What ownership & permissions do you see if you run `ls -lR public/uploads` ?
The only other thing that I know of, would be, have you tried viewing your vms in a Private Browser Windows
or Incognito Mode? It may simply be a client-side cache making you think it didn't change????

**Comment by medibasti05** [comment]
The problem must be another one, we changed the permissions but it doesnt changed.
I tried out a airline upload, and it works
![Uploading upload.jpg…]()

**Comment by medibasti05** [comment]
![upload](https://user-images.githubusercontent.com/71891549/97016931-9d42d500-154d-11eb-8c66-58215f24baf4.jpg)

**Comment by nabeelio** [comment]
Logs

**Comment by medibasti05** [comment]
[cron-2020-10-21.log](https://github.com/nabeelio/phpvms/files/5430103/cron-2020-10-21.log)
[cron-2020-10-22.log](https://github.com/nabeelio/phpvms/files/5430104/cron-2020-10-22.log)
[cron-2020-10-23.log](https://github.com/nabeelio/phpvms/files/5430105/cron-2020-10-23.log)
[Uploading laravel-2020-10-21.log…]()

**Comment by medibasti05** [comment]
[laravel-2020-10-22.log](https://github.com/nabeelio/phpvms/files/5430108/laravel-2020-10-22.log)
[laravel-2020-10-23.log](https://github.com/nabeelio/phpvms/files/5430109/laravel-2020-10-23.log)

**Comment by medibasti05** [comment]
[cron-2020-10-21.log](https://github.com/nabeelio/phpvms/files/5430113/cron-2020-10-21.log)
[cron-2020-10-22.log](https://github.com/nabeelio/phpvms/files/5430114/cron-2020-10-22.log)
[cron-2020-10-23.log](https://github.com/nabeelio/phpvms/files/5430115/cron-2020-10-23.log)
[laravel-2020-10-21.log](https://github.com/nabeelio/phpvms/files/5430116/laravel-2020-10-21.log)
[laravel-2020-10-22.log](https://github.com/nabeelio/phpvms/files/5430118/laravel-2020-10-22.log)
[laravel-2020-10-23.log](https://github.com/nabeelio/phpvms/files/5430119/laravel-2020-10-23.log)

**Comment by medibasti05** [comment]
Any Ideas? The Avatars & Files Folder have the same permissions. So it can´t be the problem in my mind.

**Comment by nabeelio** [comment]
Which upload method did you use? Is your public folder separate from the phpvms install itself?

**Comment by medibasti05** [comment]
No its in the same folder.

**Comment by medibasti05** [comment]
This is really a little crazy, a member registered today, without having uploaded a picture, he had a profile picture
![Upload error](https://user-images.githubusercontent.com/71891549/97499400-11c2ad00-196e-11eb-86ad-2152038670eb.jpg)

**Comment by medibasti05** [comment]
It´s a Bug that we found:

If you create an User Field, and make it reqired, it must also be aktivated "Private (Only Visble To Admins)". 

If you doent aktivate "Private (Only Visble To Admins)",you cant update the Profile. (E-Mail, Password, Avatar ect.)

**Comment by Oxymoron290** [comment]
@nabeelio should we re-open this ticket and at the very least provide an error message?

**Comment by Oxymoron290** [comment]
oh I see, it's under #913 okay then.

**Comment by nabeelio** [comment]
Note for myself in case this comes up again later - this happens when the `public` folder is separate from the phpvms folder - fixed in latest dev, for application bootstrap, forcing the IOC container `public.path` instance when the public path is set.
