### ISSUE TITLE
AWARDS are not given / other issues 

### ISSUE THREAD

**Issue by medibasti05** [nabeelio/phpvms#888]
Awards are not given when you have activated auto-accept Pireps. 

Awards are not given when you insert the rule "Pilot Flight Time".

**Comment by Da-Geek** [comment]
> Awards are not given when you have activated auto-accept Pireps.

@nabeelio will have to look into this and confirm.
I will be flying later today and will also try to confirm what is going on.

> Awards are not given when you insert the rule "Pilot Flight Time".
@medibasti05 
Not to be patronising, I just want to confirm, you specified the "Amount of flight time in Minutes at which to give this award"?
So to give an award at 2 hours of flight time, You would enter "120" into the "Award Class Parameters" box.

**Comment by medibasti05** [comment]
Yes i know, it must be edit in minutes, thats what i do. But it does not work.

For "Pilot Flight Route" Award i find out a trick, when auto accept is on, the priep is accepted, then you reject & accept the Pirep for two times, then it registrated the Award. Don´t know why

**Comment by Da-Geek** [comment]
Sorry again @medibasti05 as I said, I didn't mean to be patronising, I just wanted to check :-)
I'll try and have a look to see if I can find anything going wrong, It *Was* working, so something
must have changed somewhere that has stopped it working.

As I said before, @nabeelio will have to look into the Auto-Accept issue, as that should still do the
validation of the Awards, as it does with the Manual "Accept" Button.

> For "Pilot Flight Route" Award i find out a trick, when auto accept is on, the priep is accepted, then you reject & accept the Pirep

I have done this many times while testing the Awards, So I know the "Manual" process works fine :-)

**Comment by nabeelio** [comment]
I thought I had some tests that covered that, but maybe I don't. I'll look sometime today.

**Comment by medibasti05** [comment]
@Da-Geek no problem! 

It partly works that the award is given (only Route Award) with auto accept on. Unfortunately, this only works on my account, with the accounts of my pilots not. Don´t know why. 
The Time Award does not work, same with my account.
