### ISSUE TITLE
User Fields cannot be edited 

### ISSUE THREAD

**Issue by medibasti05** [nabeelio/phpvms#892]
User Fields cannot be edited on the Profil edit Page of the user, so the User cannot change any data of the User Fields

**Comment by Da-Geek** [comment]
Dose this relate to "custom fields" or the standard user fields?

**Comment by Da-Geek** [comment]
I am trying to reproduce this issue, but I am able to change any/all of the standard user fields of myself and other Pilots via the admin panel, without issue, as well as being able to change my own details via my Pilot Profile.

**Comment by medibasti05** [comment]
@Da-Geek "custom fields"

**Comment by exciler** [comment]
This is working for me right now.
Seems this was fixed by @FatihKoz in 6b32073 with #1013 and this issue can be closed
