### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by medibasti05** [nabeelio/phpvms#893]
For Spam protection and protection for registrations with false identities it would be nice that you have to confirm your email at first and get an email with an limited validity link to the registrations page.  

We have put a test before the registration, but thats not enough. We sometimes have registrations with false identities. And the IP is not saefty enough, they can use VPN and get on other IP wich cannot be trace. 

These registrations are annoying... 

Example for my idea:

Test -> E-Mail Adress Field to fill out -> E-Mail confirmation with link (limited validity) -> Registration fields to fill out ->  completion of registration.

**Comment by Da-Geek** [comment]
The 'config.php' file already has the Google "Captcha" settings that you can turn on for registration.
But maybe a "confirm your email" step may also be helpful.

**Comment by medibasti05** [comment]
@Da-Geek I think that would be the best way to protect us for registrations with false identities, because you can fill in an email adress you like, but its not given that this email adress is yours

**Comment by Da-Geek** [comment]
> @Da-Geek I think that would be the best way to protect us for registrations with false identities, because you can fill in an email address you like, but its not given that this email address is yours

The only issue with this would be if phpVMS has not been configured with E-Mail Server Details, so it is unable to send E-Mails.
For instance I do not have my VMS configured to send E-Mails right now, so it wouldn't make a difference to my setup.

Maybe the setting in the Admin section called "Auto Accept New Pilot" is a better option.
This puts accounts into a Disabled State, with no access to anything until an Admin manually enables the accounts.
This is the way my current setup runs.

**Comment by medibasti05** [comment]
It's not about the accounts having access to anything. We have deactivated auto accept.
Specifically, it is about logging in with wrong e-mail addresses and wrong identities. 
We cannot determine the authenticity of these accounts, which is why an e-mail confirmation is more secure and confirms the e-mail address.

**Comment by medibasti05** [comment]
@Da-Geek It is just annoying to have to check every account in detail whether the given e-mail address is the right one. And whether the account was really created by who it claims to be.

**Comment by nabeelio** [comment]
Leaving this here so I can refer to it later: https://laravel.com/docs/7.x/verification

**Comment by ArthurHetem** [comment]
@medibasti05 , does this flow makes sense for your idea? 

User register (with captcha) -> Email sent to verify, with expiration of 24 hours (for example) -> the user can only login if is verified

**Comment by FatihKoz** [comment]
Considering we are now using Laravel10 and in case somebody wants to follow the docs, here is the latest link from Laravel docs;

https://laravel.com/docs/10.x/verification

:)
