### ISSUE TITLE
Bid still reserved after ACARS flight report. 

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#902]
After filing Acars report the BID is still present in the reserve page and won`t let you book another flight (unless you change the settings in admin panel)

Latest dev, Latest Acars

Something strange, if another pilot have the same issue (the bid stuck in the reserve page), his bid will be shown in my acars bid page. 

[https://imgur.com/a/JfXlEPt](url)

**Comment by nabeelio** [comment]
Bids can be shared unless that option is set in the settings. Was the flight loaded from the bid in ACARS?

**Comment by macofallico** [comment]
Yes the flight was loaded from the bid in ACARS

"Bids can be shared unless that option is set in the settings" yes, for sure but the other pilots bids should be shown in the your acars?¿

**Settings in phpvms:**
"Disable flight on bid" Unchecked (disabled)

"Allow multiple bids" Checked (Enabled) if not you cannot bid in another flight because you already have that bid filed (users cannot delete the bid have to manually delete the bid in the database)

**Comment by nabeelio** [comment]
Ok, I'll have to add some more logging in ACARS to see if the bid was picked up, it might be an issue from there

**Comment by macofallico** [comment]
don`t know if related but in certain cases with acars wont let you end the flight too.
