### ISSUE TITLE
Show Pirep Error "Fares"

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#903]
In some flights reported using acars when you open the pirep report you will get an error:

ErrorException
Trying to get property 'name' of non-object (View: /home/asmkcoma/system.aerovirtual.com.ar/resources/views/layouts/aerovirtual/pireps/show.blade.php)
https://system.aerovirtual.com.ar/pireps/dpleo0xweEz8Qn4E

[https://flareapp.io/share/95J8DJBP#F50](url)

Latest dev, Latest Acars

**Comment by medibasti05** [comment]
Nabeel, the Fare problem has not been fixed
https://flareapp.io/share/x7XgwrwP#F48

**Comment by nabeelio** [comment]
Still open?

**Comment by macofallico** [comment]
let me do a quick test

**Comment by macofallico** [comment]
Still, if the fare is deleted, pireps wich used that fare will end up in that error

**Comment by nabeelio** [comment]
Ok, right, thought I had another issue for this open. Thanks

**Comment by ArthurHetem** [comment]
@nabeelio, i think this can be closed after the fares update.
