### ISSUE TITLE
Simbrief Dispatch Error 

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#904]
**Describe the bug**
Error while dispatching using Simbrief, like its  bringing up older simbrief dispatch OFPs.
Its user tied, and flight tied, in some cases it will produce the correct simbrief settings an then report, in some cases will go directly to the simbfief report but will produce some error (wrong ofp, no maps, no flight number, etc)

**Version**
Latest Dev

**To Reproduce**
See youtube video [https://youtu.be/MnU52qRy78E](url)

**Expected behavior**
Create simbrief OFP

**Comment by nabeelio** [comment]
Is the brief correct on the Simbrief site?

**Comment by macofallico** [comment]
Yes, it`s correct, solution manually delete from the database in the table "simbrief" the IDs related to the flights, so it will generate again a new dispatch.

**Comment by macofallico** [comment]
Maybe when the flight is completed and reported or the bid is dropped the simbrief dispatch should be deleted.

**Comment by FatihKoz** [comment]
With the latest merged pr's, this issue is mostly solved ... Users will be able to generate a new simbrief package when needed ;)

**Comment by FatihKoz** [comment]
This may be closed too ... Unless you want to implement some more automation as suggested by Maco. Current build offers a button to re-generate a new simbrief ofp if there is an old one (or the user just wants to create a new one instantly)
