### ISSUE TITLE
Bug when have User Fields activ

### ISSUE THREAD

**Issue by medibasti05** [nabeelio/phpvms#913]
Issue: Profil Edit not possible when you have an User Field activ. 

If you create an User Field, and make it reqired, it must also be aktivated "Private (Only Visble To Admins)". 

If you doent aktivate "Private (Only Visble To Admins)",you cant update the Profile. (E-Mail, Password, Avatar ect.)

**Comment by FatihKoz** [comment]
Issue was fixed months ago with #1013 , should be closed.
