### ISSUE TITLE
Airport select block the page when have houndreds of airports

### ISSUE THREAD

**Issue by vgpastor** [nabeelio/phpvms#916]
In our environment we have more than 15000 airports inside the database, this cause that we can't load any page where the select with airports are present.

Dev version

**To Reproduce**
1. Install phpvms
2. Import database with thousands of airports
3. See error

**Expected behavior**
The system use select2 that provide a function to sarch dinamycally without need load all airports in the select box when load the page

**Comment by arthurpar06** [comment]
I think #1574 closes this one
