### ISSUE TITLE
Set higher limit for texts for custom pages

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#920]
**Describe the bug**
The limit of the legth of the text for the custom pages is very low. 

**To Reproduce**
1. Go to admin
2. Go to 'pages/links'
3. Put a very long text inside the wysiwyg-editor
4. Watch the text beeing shortend 

**Expected behavior**
The full length of the text is beeing shown in the editor and on the actual page.

**Screenshots**

**Additional context**
Add any other context and attach logs (from `storage/logs/laravel-<date>.log`)
![grafik](https://user-images.githubusercontent.com/62832771/98418637-a1a9da80-2083-11eb-91ca-2e091973f87a.png) before

![grafik](https://user-images.githubusercontent.com/62832771/98418669-b71f0480-2083-11eb-9fc4-40ce559a2499.png)
after

**Comment by Da-Geek** [comment]
I have hit this several times, as a work around, I have just been using `Page Type` Link, and just linking outside of VMS :(

**Comment by Da-Geek** [comment]
I guess this is a DB schema issue?
I would need to go look at the DB to see if there is a simple limit on the field that stores this data

**Comment by lorlandi** [comment]
In fact I made the change in body varchar (191) to varchar (15000) and now I can make pages with more information.

**Comment by nabeelio** [comment]
I have a fix for this pending

**Comment by nabeelio** [comment]
Changed the column to a medium text (16MB)
