### ISSUE TITLE
Use Config Weight units in Simbrief Form Template

### ISSUE THREAD

**Issue by trevorhannant** [nabeelio/phpvms#921]
The simbrief_form.blade.php currently defaults to LBS regardless of the weight unit specified in the config settings.

Rather than admins editing the template on every upgrade, set the selected field for the dropdown to the value set in settings.unit_weight (or units_fuel?)

**Comment by macofallico** [comment]
you could easely edit the template or create a custom template and upgrades wont afect you like this:

  <tr>
                  <td>Unidades:</td>
                  <td><select name="units">
                      <option value="LBS">LBS</option>
                      <option value="KGS" selected>KGS</option>
                    </select></td>
                </tr>

I also added a PAX count selector.

**Comment by trevorhannant** [comment]
And how would you call the custom template?   Would the simbrief_form.blade.php file not need a call to that which would then be overwritten on an upgrade?

**Comment by nabeelio** [comment]
You can change it in your customized skin (which you should be using). But this is still something that need to be fixed

**Comment by FatihKoz** [comment]
This issue should be closed too, current simbrief_form checks user settings and applies correct selection for KG/LBS.
