### ISSUE TITLE
Subfleet Fares and Flight Fares Mismatch (Double Fare Issue)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#923]
vmsAcars gets the applicable fares from subfleet only. (Not checking the flight fare)

**Version**
7.0.0-dev+201102.a2de53

**To Reproduce**

1. Create a subfleet (ex. A321N-PGT)
2. Insert some aircrafts to the database and assign them to that subfleet
3. Create some fares like Economy - Domestic (YD) and Economy - International (YI) , assign prices and costs to them
4. Return back to subfleet settings , assign both Economy - Domestic (YD) and Economy - International (YI) fares to the subfleet with defining max seat capacity (239 economy seats)
5. Create two short haul domestic flights with %90 load factor, assign only Economy - Domestic (YD) fare to this flights.

Setup complete, continue on test flight with bid/vmsacars

6. Bid one of the flights you created
7. Generate OFP and check load route fuel etc. Export files as required
8. Start sim, load the aircraft as per flight plan/bid
9. Run vmsAcars, search for bid, select and load bid/flightplan, select aircraft 

**Expected behavior**

At this point you should be able to see one matching fare and maximum capacity only. So vmsAcars should show Economy - Domestic only (with a max capacity of 239 and the autogenerated pax figure should not exceed this value)

**Screenshots**

![3-vmsAcars-flight](https://user-images.githubusercontent.com/74361521/98946199-a39cef00-2504-11eb-9c06-d3cdeea1ebbc.png)
![4-vmsAcars-flight](https://user-images.githubusercontent.com/74361521/98946490-00000e80-2505-11eb-8f9f-f503ee04147a.png)
![5-vmsAcars-flight](https://user-images.githubusercontent.com/74361521/98946510-068e8600-2505-11eb-95f1-359ca9719934.png)

**Comment by nabeelio** [comment]
Still open?

**Comment by FatihKoz** [comment]
I need to re-create the same scenario to see if it is still open ...
