### ISSUE TITLE
Fare Percentage Logic Problem

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#925]
As per the documentations, a percentage can be applied to base fares (by editing subfleet or flight). Which makes us think that this logic should be used for both increasing and descreasing the base fare. Currently it is not working as documented and only increases the base by the percentage provided.

**Version**
7.0.0-dev+201102.a2de53

**To Reproduce**
1. Check and note the base fare from one of your pireps
2. Edit the subfleet or flight fares (which is used on that pirep), set the fare price to 50%
3. Go to admin panel, find that same pirep, click edit and recalculate finances
4. Check the result, your fare will be INCREASED by 50%

**Expected behavior**
If the base fare price is 200, a subfleet (or flight) fare rate set to 50% should give the final result of 100.

**Additional context**
_(Coppied from Docs/Finances/Fare Section)_

When the fare is added for a subfleet or on a flight, the values can be set to a number, or a percentage. The percentage will be from the base fare, and the "base" is 100% - so if you want to increase the fare price for a subfleet to be 10% higher than the base fare for that class, set it to 110%. The percent-sign needs to be included for it to detect that you want to add a percentage.

**Comment by FatihKoz** [comment]
This issue also effects Ground Handling Multiplier logic , where in theory (according to docs) the base price is called as 100% and 115% should increase only by %15, unfortunately it increases the ground handling price by 115% ;)

**Comment by nabeelio** [comment]
It should be working to decrease it too, there are some unit tests which cover this... to decrease though, you should set it to "-50%" as the value. Setting to the "50%" will increase it by 50% of the base fare. So I think this isn't a bug actually, I need to fix the documentation (which I'll do right now). Can you try a negative value?

I know this is a little confusing, so I'm thinking of changing the behavior of this so if you want it to be +25%, set it to 125% (as I guess would be expected)

**Comment by nabeelio** [comment]
Please try this in the latest dev build now. The math should be be correct. I don't know why I did it the way I originally did.

**Comment by FatihKoz** [comment]
Hi @nabeelio ,

Just tested your negative percentage using request with **7.0.0-dev+201123.be1542** build.

Fare Base Price : 100 per ticket

Edit flight , set price field to 100% . Recalc Finances . Result is 200 per ticket
Edit flight , set price field to 200% . Recalc Finances . Result is 300 per ticket
Edit flight , set price field to -50% . Recalc Finances . Result is 50 per ticket

So using negative values worked, if you want to keep this solution docs needs to be changed to reflect the calculation logic.

Should I download the changed files and test again with non negative values as per the docs ?

**Comment by nabeelio** [comment]
Yes please, I'll update the docs. The negative percentage is confusing

**Comment by FatihKoz** [comment]
If you had corrected the math then no need to update the docs I assume ... ( Not tested yet the latest 4 changed files )

**Comment by FatihKoz** [comment]
Hi again @nabeelio ,

Installed latest dev build and tested again (**7.0.0-dev+201126.6b5cf3**)

Fare Base Price : 100 per ticket

Edit flight , set price field to 150% . Recalc Finances . Result is 150 per ticket
Edit flight , set price field to 300% . Recalc Finances . Result is 300 per ticket
Edit flight , set price field to 75% . Recalc Finances . Result is 75 per ticket

Right now, math is correct and it is doing what one expects to do according to docs (and general logic) Thanks for the update.

**Comment by nabeelio** [comment]
Excellent, thanks for checking
