### ISSUE TITLE
PHPVMS not working behind reverse proxy

### ISSUE THREAD

**Issue by richman1000000** [nabeelio/phpvms#929]
**Describe the bug**
links in reverse proxy still contain internal address

**Version**
version 7.0.0-dev 

**To Reproduce**
1 setup a server. and check if it is working (http://internal.local works correctly)
2. Setup a Reverse proxy server (I use Ngingx) and add a proxy path

> location /phpvms {
        proxy_pass http://internal.local/phpvms/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
}

3. Open External link
4. Most part of pages still openned via  http://internal.local which is not accessible from the internet. External link is not working
See error

**Expected behavior**
Site opens correctly from external and internal web pages

**Screenshots**
![image](https://user-images.githubusercontent.com/9943374/99512647-c44cc500-299a-11eb-8151-cc832eb32572.png)

**Additional context**
 I tryed this manual, but it is not working.
https://lavalite.org/blog/using-laravel-routes-in-reverse-proxy

**Comment by nabeelio** [comment]
Laravel does not work well in subdirectories.  You'll need to point it either a subdomain or a root domain. There is an example vhost for nginx here:

https://github.com/nabeelio/phpvms/blob/dev/resources/docker/nginx/default.conf

**Comment by richman1000000** [comment]
No this is not subdomain. this is REVERSE PROXY

**Comment by nabeelio** [comment]
You've set the location block to a subfolder - Laravel doesn't work right in subfolders. The vhost needs to be at the `location /` of either a domain or subdomain or the assets won't be found. You also need to point the vhost to the `/public` folder. Refer to the vhost that I've posted above.
