### ISSUE TITLE
Editing a Subfleet Member Aircraft (Page Returns Back To Full Aircraft List)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#932]
**Admin Panel** When you edit an aircraft and save your changes page returns to full aircraft list instead of subfleet list.

**Version**
7.0.0-dev+201123.be1542

**To Reproduce**
1. Go to Admin - Fleet
2. Click on a subfleet name you created to see its members
3. Select an aircraft from that subfleet and click edit 
4. Make your changes or just simply click cancel

You will have the full aircraft list ( admin/aircraft )

**Expected behavior**
Page should revert back to where it was before (like admin/aircraft?subfleet=7 )

This may not be a bug at all but returning back to the subfleet list would improve the usage of subfleet management and provide easy administration for the va/fleet managers.

**Comment by nabeelio** [comment]
I removed the cancel button; just click back. The code to check/hide if it's in add or edit is overkill
