### ISSUE TITLE
Route Database (Feature Request)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#933]
As you all may know, the routes between cities are not fixed to flights in rw aviation and a route may be used for multiple flights between two cities by multiple airlines/types. In our current system, we need to have a route defined for every flight we insert to our schedule which in theory is too different from how real flight ops work.

So if you are trying to simulate a full schedule of a rw airline, then you will have to insert its flight schedule to your system with multiple flights between city pairs, with changed times and days etc if you seek full schedule realism. Or you may have multiple airlines flying the same city pair maybe with different types of aircrafts and you will insert them to your database too.

This means that you have to use the same route over and over again for multiple flights, in our current logic we need to enter the same route for every flight which is not realistic and time consuming, also hardens the maintanence if something changes (like airac update / airway change , intersection change etc)

To overcome this situation we need a separate route table in our databases, where you can insert at minimum only dep - arr - flight route details and then when inserting (or editing) a flight we should be able to select this route (like we select the expenses, subfleets, expenses etc). If you do not want to restrict a route to only an airline or a subfleet then you should be able to select that route for multiple airlines/flights etc as you wish.

If we have a seperate route database this also provides us to have multiple routing options between city pairs too, for example you may have 2 different routes between EDDL and LGIR one from north via Austria - Hungary another from going south via Switzerland - Italy etc.

When available, our pilots may choose the preffered route according to their wishes (upper air weather situations/distance etc) before generating their flight plan packages via simbrief.

**Comment by dougjuk** [comment]
Great idea, would love to be able to create a series of flights such as a world tour or tour of a Country or area.

**Comment by FatihKoz** [comment]
Moving this to one of my modules 😃  No need to have deep realism in core at the moment. It is already complicated for most of the users, having a route database like real world will make lives harder.

Peacefully closing this request
