### ISSUE TITLE
QueryException when using the table prefixes

### ISSUE THREAD

**Issue by OndrejBakan** [nabeelio/phpvms#934]
**Describe the bug**
When you choose to use table prefix in the installer, it will include the prefix in tables and INDEX NAMES, but the migration (in my case "2020_03_28_174238_airline_remove_nullable.php") is looking for dropUnique('airlines_iata_unique');. Meanwhile the index is named with prefix, so in my case "phpvms_airlines_iata_unique.

**Version**
7.0.0-beta4

**To Reproduce**
1. Run the installer.
2. Choose some prefix for your tables.
3. See error

**Comment by nabeelio** [comment]
Can you try the latest dev? The link is in the docs or the Discord.

**Comment by OndrejBakan** [comment]
@nabeelio Hello, thank you for your quick reply. I just tried the development branch link from docs. I don't see the error anymore, but now I am stuck in a loop:

I run the installer, fill the db information, set the prefix, hit Setup Database. Database is created, but I am redirected back to the Database Setup page. And again and again.

If I try to manually go to the step3, I fill out the VA information and after clicking on Complete Setup I get another error:
SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) (SQL: select count(*) as aggregate from `airlines` where `icao` = TAY)

So it looks like now the config is not created / saved.

**Comment by nabeelio** [comment]
Delete the database and the `config.php` and `env.php` files. And check in the `storage/logs/laravel.log` file (if you can attach it here, that will be helpful). There might be something left over. Delete the `vendor` folder too and reupload, it's possible something isn't properly uploaded there.

**Comment by OndrejBakan** [comment]
So I can confirm that even while using the latest dev version, there is still problem with the prefix. There is no Exception, it just redirects you back to the Database Setup page.

If I try to install without prefix, everything goes fine.

[2020-11-25 21:17:14] prod.ERROR: Error on db setup: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'airlines_iata_unique'; check that column/key exists (SQL: alter table `asl_airlines` drop index `airlines_iata_unique`)

**Comment by nabeelio** [comment]
Thanks, this might be Laravel related. I'll try to debug this soon

**Comment by nabeelio** [comment]
Fixed in the latest dev
