### ISSUE TITLE
Barometer error in METAR decoding

### ISSUE THREAD

**Issue by arthurpar06** [nabeelio/phpvms#948]
On the dashboard page, the current weather forecast for the airport is displayed with a decoding of the metar and therefore its barometer. If we are in America or at least with a metar in InHg and not in hPa. The barometer is displayed in InHg in the Hpa box and therefore in the InHg box it is the conversion of the latter.
It should therefore display the barometer in InHg and its conversion to hPa

![image](https://user-images.githubusercontent.com/41431456/100645671-48109500-333d-11eb-8c0d-78a5735e2a4b.png)
For example at PHNL (Honolulu)

**Comment by FatihKoz** [comment]
Current code always shows the metar reported pressure on the left, then converts it on the right ... Even if you set it to show inHg with $metar['barometer']['inHg'] , it puts the metar recorded value there. As a simple workaround, I removed the unit names from the widget and displaying raw values without units.

Also while checking the metar decoding functions found a little error at **App/Support/Metar.php line 175**

**SKC** means **Sky Clear** (or Clear Skies) but it is translated as "_no significant changes expected_" (which is _NOSIG_)

While checking the pressure problem this little text change would be nice to fix.

**Comment by FatihKoz** [comment]
While working on the TAF update I think I may have found the cause of this problem;

If the airport reports the pressure as hPa (Q1028 for exp) then the display and conversion to inHg is correct. But if the airport reports the pressue as inHg (A3036 for exp) then the conversion is wrong.

My assumption here, that the decoder is always identifying the reported pressure as hPa and building its calculations on that, this also causes the wrongly displayed labels. Decoder always assigns the reported value to hPa.

If needed I can share my solution for the display part, right now I am checking the icao code in the blade (as a workaround) and if the airport resides in a country where pressures are reported as inHg I am using the correct unit type + not showing the wrongly converted value.

As far as I know, there are only 3 countries in the world using inHg as their reported pressure for aviation, these are Canada - Japan and United States. So workaround was easy to manage.

![hpa-inhg](https://user-images.githubusercontent.com/74361521/102720542-094f7880-4306-11eb-958a-79c148d45670.png)
![inhg](https://user-images.githubusercontent.com/74361521/102720545-0d7b9600-4306-11eb-8357-9f792e9b6b14.png)

**Comment by FatihKoz** [comment]
Should be closed ... We had two or more PR's for Metar Decoding and mentioned issue was solved with them.
