### ISSUE TITLE
Formatting on admin pirep page

### ISSUE THREAD

**Issue by asandor42** [nabeelio/phpvms#952]
There is a format issue on the admin pirep page. When you go to look at the pireps, only 2 show at the top, the rest are moved down below the left column.
![Screenshot 2020-11-22 07 35 23](https://user-images.githubusercontent.com/55407757/101196434-93fd5b80-3615-11eb-96ba-efdec679747c.png)

**Comment by FatihKoz** [comment]
Solved/closed by the **7.0.0-dev+201206.883e87** dev build. (Latest dev as of 06DEC2020)

**Comment by FatihKoz** [comment]
@nabeelio , this issue is closed by #953 months ago (last year to be precise)
