### ISSUE TITLE
Metar Decoding Errors

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#963]
Current metar decoding has some errors as described below;

1. Dew point value is not displayed if the reported dew point is zero degrees celcius (ref: LTBJ)
2. IFR/VFR Conditions checks are wrong, given the weather repots and current status that station is %100 IMC (ref: LTFE)
3. Wind direction decoding is missing when the reported winds are VRB / Variable (ref: LTFE)
4. As a general fact there is no VFR/IFR conditions, they are called as VMC/IMC. VFR is Visual Flight Rules, it is the name of a ruleset applicable to a flight, not a type of weather condition. 

**Version**
7.0.0-dev+201207.e95e61 / 7.0.0-dev+201218.e4972e

**To Reproduce**
You may use below raw metars to reproduce the issues
LTBJ 200420Z 00000KT 7000 FEW001 01/00 Q1024 BECMG 4000 BR
LTFE 200420Z VRB02KT 1200 0300W R28/0650U R10/0550N BCFG NSC 02/02 Q1024 NOSIG

**Expected behavior**
1. Dew point value must be displayed at all times, 0 is a value not a useless thing
2. Given the conditions that station must be reported as IMC
3. VRB or Variable may be displayed as the direction
4. VMC/IMC codes should be used instead of VFR/IFR

**Screenshots**
![1](https://user-images.githubusercontent.com/74361521/102705737-ce185f80-429b-11eb-9674-0ca551ee7546.png)
![2](https://user-images.githubusercontent.com/74361521/102705741-d1135000-429b-11eb-89c7-b8b9301bada0.png)

**Additional context**
https://www.skybrary.aero/index.php/Visual_Meteorological_Conditions_(VMC)
https://www.skybrary.aero/index.php/Instrument_Meteorological_Conditions_(IMC)
https://www.skybrary.aero/index.php/Visual_Flight_Rules_(VFR)

**Comment by FatihKoz** [comment]
Just for your info, below items still open

- IFR/VFR Conditions checks are wrong, given the weather repots and current status that station is %100 IMC (ref: LTFE)
- Wind direction decoding is missing when the reported winds are VRB / Variable (ref: LTFE)

**Comment by nabeelio** [comment]
Can you add a new issue for that with a couple of examples when you get a chance? How important are those scenarios?

**Comment by FatihKoz** [comment]
> How important are those scenarios?

Well, for me they are important but I do not need them to be decoded anyway, raw metar is what I use. And this really depends on the persons realism expectations and aviation knowledge.

I do not think that virtual pilots are caring the IMC/VMC difference, in fact they do fly VFR in pure IMC and have fun.

Long story short, not important at all :)

Below raw metar is ok for testing and re-creating the problem

`LTFE 200420Z VRB02KT 1200 0300W R28/0650U R10/0550N BCFG NSC 02/02 Q1024 NOSIG`

Winds should report : From Variable Directions 2 Knots ( or just Variable 2 Knots )
Condition must be : IFR (IMC)

Current code repots no direction for winds (check the image above for LTFE) , and it reports the conditions as VFR.

**Comment by nabeelio** [comment]
Ok, thanks. So I'll just roadmap this eventually and keep it low on the priority list. Thanks!

**Comment by FatihKoz** [comment]
Yeah, that would be good.
