### ISSUE TITLE
Make phpvms ready for php8

### ISSUE THREAD

**Issue by ollimaz** [nabeelio/phpvms#971]
This application is not ready for php 8.
Running this application on php 8 causes : 

`AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of Doctrine\\DBAL\\Driver\\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in ***censored***/phpvms/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 70', referer: https://***censored***/admin/airlines/1/edit`

**Comment by nabeelio** [comment]
There's a task for this I think, I have to see if travis supports php8 yet. Is this the latest dev? Can you reupload the vendor dinner in case something was updated inadvertantly? That seems like the doctrine version differs from the composer lock
