### ISSUE TITLE
Installer Error:  The GET method is not supported for this route. Supported methods: POST. 

### ISSUE THREAD

**Issue by BaradineAllawa** [nabeelio/phpvms#972]
When working thru the installer I get the following.

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The GET method is not supported for this route. Supported methods: POST.
http://phpvms.pg.id.au/install/envsetup 

I've tried this with both Apache2 and Nginx (to eliminate Nginx sometimes rewriting Post as Get). Used both the last release branch, and a git clone. Looking to see if anyone has any suggestions on how I can get thru the installer.

It fails just after I put in the mysql user/password.

If anything else is required please let me know.

**Comment by nabeelio** [comment]
Hmm that's strange. I haven't seen that before. Have you tried the latest dev?

**Comment by BaradineAllawa** [comment]
if you mean latest code via a git clone, then yeah, same issue.

**Comment by nabeelio** [comment]
That page is a POST, after entering your DB info. Are you using fastcgi or something? Lemme see if I can do a fresh install today

**Comment by BaradineAllawa** [comment]
method for git clone was
git clone https://branch.url
cd /path/install
composer install

then fired up the URL in a browser. Used the examples listed on the installation docos to knock up both nginx and apache vhosts. 
Tried nginx/fastcgi with both the last release & dev
Tried apache/mod-php with last release.

All exhibited the same issue when I got to the step after you put in database details.

**Comment by BaradineAllawa** [comment]
Oh wait. I just discovered the issue. Feel free to call me an idiot. It must be something in the nginx reverse proxy I use for external access (The joys of having numerous sites on numerous boxes at home). Testing with internal IP worked. I'll play with it some. If I find the solution, I'll put it in here for continuity sake, in case anyone else strikes it.

**Comment by nabeelio** [comment]
Sounds good, thanks! And no worries, I know that kinda fun in debugging that 😀
