### ISSUE TITLE
Flights Import : Edited Fares | CSV Import (Bug Report)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#974]
When using import function, fares with changed/edited values are not imported correctly. 

Exported file contains **YG?price=75%** as the value for fares field (which is the reduced fare price for that flight and only the prices was changed rest stays inherited). But when importing it is not handled properly and a new fare is created with a name and id **YG?price=75%**

**Version**
7.0.0-dev+201223.18e1d6

**To Reproduce**
Just export your flights and check flights with edited fares, then import back the same csv.

**Expected behavior**
They should be imported with the same fare code (YG) and they should have the edits mentioned (?price=75%) in the csv. If this is not possible then we should use only the fare and any edits should be disregarded (?=....)

**Comment by FatihKoz** [comment]
Above issue happens while importing subfleets with edited fares too. With the issue being open it is not possible to export and re-import flights/subfleets (or import new ones) properly once you edit their fares.

**Comment by lesmar54** [comment]
I am going to look into this now that I have flights with fare codes to test with.  Flights and the Fares table seemed to be linked with a file called 'flight_fare'  which has the details of the flight and the fare codes used 
![Screenshot 2021-09-18 at 17 01 32](https://user-images.githubusercontent.com/22278416/133890242-51e50d8e-a7a5-4fe8-a26d-80393b7ec8b5.png)
h
