### ISSUE TITLE
Flights Import (Update Option)

### ISSUE THREAD

**Issue by FatihKoz** [nabeelio/phpvms#976]
Is it possible to have "update" capability with the flight csv import system ... Currently it only adds new flights, but for mass editing your flights import function (or a new function) should do an update instead of insert.

An export function generating a csv with flight id's and all other details, a new import function reading the ids to match the flights may be needed, or the current functions may be improved (if there is flight_id then update, else insert etc)

It is really hard to edit multiple flights, specially when fares and subfleets needs to be updated. Deleting the whole flight list table and importing a full flights csv may cause problems for old pireps and/or finance calculations (not tried and do not want to try to be honest). This is why I thought about the "update" option.

**Comment by nabeelio** [comment]
It should be updating, this is a bug

**Comment by FatihKoz** [comment]
I am trying to replicate the insert problem to pin down the issue ... Doing updates with smaller amounts of flights (like 50-60 per airline basis) seems working as it should.

Not added new flights to the csv though, only edited current ones and re-imported. Current flights were updated as expected.

**Comment by nabeelio** [comment]
There are unit tests which should cover it
