### ISSUE TITLE
Acars Arrived/On Gate Phase not working Properly. 

### ISSUE THREAD

**Issue by macofallico** [nabeelio/phpvms#997]
Just for pilots that wants to simulate deboarding/on gate, the acars will still show taxi in. (will keep logging taxi time where you are instead deboarding/parked in gate)

Version, 1.0.0.1267

I edit https://docs.phpvms.net/acars/phases    / Arrived status is never shown.  (parking brakes on)

**Comment by ProAviaAZ** [comment]
Are you wanting to continue to record loggable flight time once parked at the gate? Not very realistic. In civil aviation, loggable flight time is start of taxi at departure airport to stop of taxi at arrival airport. Parked only counts for duty time, not flight time. Pilots are free to board/deboard as they deem fit - but shouldn't receive fight time credit for it.

**Comment by arv187** [comment]
Taxi is taxi, If you want that, then define a phase after parking brake to deboarding/on gate.
To finish the flight and send the report add a button in acars or create an airplane power off  trigger or similar. (I think that button is better option because of compatibility and complexity to work with fsuipc and diverse sims/airplanes).

**Comment by macofallico** [comment]
no! that´s the issue! the idea is to change to arrived/parked at the gate (As stated in Acars oficial documentación) because we notice that some pilots still deboarding using 3rd party apps (SLC PACX) and the state in acars remains as TAXI IN, and wont change state to Arrived

**Comment by arv187** [comment]
If there are an issue don't close it. Left to nabeel decide about that.

**Comment by macofallico** [comment]
the issue is that the latest phase is never shown (as stated in acars documentation) if that function is a no go, OK, we can ask to be deleted from the documentation.

**Comment by macofallico** [comment]
> Are you wanting to continue to record loggable flight time once parked at the gate? Not very realistic. In civil aviation, loggable flight time is start of taxi at departure airport to stop of taxi at arrival airport. Parked only counts for duty time, not flight time. Pilots are free to board/deboard as they deem fit - but shouldn't receive fight time credit for it.
> 
> Once on gate, parking brakes set and engines off, pilot should be able to stop flight as part of their shut down checklist. Stop flight should stop the flight time clock. Then they can do a deboard or whatever they want prior to filing the PIREP. Maybe have a rule that after 'x' minutes with parking brake set and engines off at the gate some points get deducted?

I believe you did not understand me, i never stated that i wanted to log taxi parked time as flight time. If the pilot does not
 end the flight the taxi in time will keep going, but in reality the craft is parked at the gate.

**Comment by macofallico** [comment]
> If there are an issue don't close it. Let to nabeel decide about that.

i did not deleted/closed it!

**Comment by arv187** [comment]
Anyway, log parking time must be logged in the future if we want to add tax per parking/jetway use in airports.

**Comment by macofallico** [comment]
> Anyway, log parking time must be logged in the future if we want to add tax per parking/jetway use in airports.

well so if a pilot let the sim on, and acars on in that state, will keep loging taxi in time..... and that will be shown in the report.

**Comment by ProAviaAZ** [comment]
Sorry - my mistake. I did misunderstand your concern. I guess the arrived mode needs to be addressed.

**Comment by nabeelio** [comment]
Yes it should be showing "arrived", this broke somewhere down the line.

**Comment by nabeelio** [comment]
> Anyway, parking time must be registered in the future if we want to add tax per parking/jetway time use in airports.

This would be more complicated; while I can show when the boarding started (based on when they hit start flight), at the tail end, you'd have to hit the button for "at the gate" and then another to end the flight.

**Comment by nabeelio** [comment]
> Taxi is taxi, If you want that, then define a phase after parking brake to deboarding/on gate.
> To finish the flight and send the report add a button in acars or create an airplane power off trigger or similar. (I think that button is better option because of compatibility and complexity to work with fsuipc and diverse sims/airplanes).

That's the "end flight" button. I'll clarify in the docs on the Flight Phases page.

**Comment by arv187** [comment]
> 
> 
> > Anyway, parking time must be registered in the future if we want to add tax per parking/jetway time use in airports.
> 
> This would be more complicated; while I can show when the boarding started (based on when they hit start flight), at the tail end, you'd have to hit the button for "at the gate" and then another to end the flight.

May be counting since parking brakes after taxi in to "End Flight" button.

**Comment by sarcas31** [comment]
> > > Anyway, parking time must be registered in the future if we want to add tax per parking/jetway time use in airports.
> > 
> > 
> > This would be more complicated; while I can show when the boarding started (based on when they hit start flight), at the tail end, you'd have to hit the button for "at the gate" and then another to end the flight.
> 
> May be counting since parking brakes after taxi in to "End Flight" button.

But if deboarding PAX maybe 15min - 20min that time is counted in TAXI IN time/phase. Tha ACARS needs to have ARRIVAL/ON GATE phase without press END FLIGHT....this action (END FLIGHT) comes later...its just my opinion...

**Comment by macofallico** [comment]
maybe something like After, TAXI IN PHASE, ----------> engines off ------->Arrived or parked at the gate.    That will avoid the problem with using parking brake in the "taxi in" phase wich is usual procedure.
